/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CarDealerSystem;

import java.awt.Color;
import java.awt.Font;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Angela
 */
public class AdmEmpList extends javax.swing.JInternalFrame {
    Connection con;
    /**
     * Creates new form AdmEmpSalary
     */
    public AdmEmpList() {
        initComponents();
        
        String url = "jdbc:mysql://localhost:3306/car_dealers";
        String user = "root";
        String pass = "";
        try{
            con= DriverManager.getConnection(url,user,pass);
        }catch(Exception ex){
            System.out.println("Error:" + ex.getMessage());
        }
        
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0)); //no space
        BasicInternalFrameUI bui = (BasicInternalFrameUI) this.getUI();
        bui.setNorthPane(null);
        
        tblmanager.getTableHeader().setFont(new Font ("Segoe UI", Font.PLAIN,16));
        tblmanager.getTableHeader().setOpaque(false);
        tblmanager.getTableHeader().setForeground(new Color(204,0,0));
        tblmanager.setRowHeight(25);
        
        tblemployee.getTableHeader().setFont(new Font ("Segoe UI", Font.PLAIN,16));
        tblemployee.getTableHeader().setOpaque(false);
        tblemployee.getTableHeader().setForeground(new Color(204,0,0));
        tblemployee.setRowHeight(25);
        
        jScrollPane2.getVerticalScrollBar().setUnitIncrement(16);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jtxttotalsalary = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jtxtemployeeID = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jtxtposition = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jtxtname = new javax.swing.JTextField();
        jtxthired = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jtxtphone = new javax.swing.JTextField();
        jtxtmanager = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jtxtsalary = new javax.swing.JTextField();
        jtxtaddress = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblemployee = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblmanager = new javax.swing.JTable();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jtxtsearch = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jtxtposition1 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jtxthired1 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jtxtsalary1 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jtxtmanagerid = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jtxtname1 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jtxtphone1 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jtxtaddress1 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(1002, 900));
        setPreferredSize(new java.awt.Dimension(1002, 900));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane2.setBorder(null);
        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPane2.setFocusable(false);
        jScrollPane2.setMinimumSize(new java.awt.Dimension(1002, 500));
        jScrollPane2.setPreferredSize(new java.awt.Dimension(1002, 500));

        jPanel2.setBackground(new java.awt.Color(204, 0, 0));
        jPanel2.setPreferredSize(new java.awt.Dimension(1002, 1150));
        jPanel2.setLayout(null);

        jButton1.setText("View Employee Lists");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);
        jButton1.setBounds(10, 833, 150, 30);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setText("Add");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2);
        jButton2.setBounds(310, 820, 100, 30);

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton3.setText("Delete");
        jButton3.setMaximumSize(new java.awt.Dimension(55, 23));
        jButton3.setMinimumSize(new java.awt.Dimension(55, 23));
        jButton3.setPreferredSize(new java.awt.Dimension(55, 23));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3);
        jButton3.setBounds(510, 820, 100, 30);

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton4.setText("Update ");
        jButton4.setMaximumSize(new java.awt.Dimension(55, 23));
        jButton4.setMinimumSize(new java.awt.Dimension(55, 23));
        jButton4.setPreferredSize(new java.awt.Dimension(55, 23));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4);
        jButton4.setBounds(410, 820, 100, 30);

        jtxttotalsalary.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtxttotalsalaryKeyReleased(evt);
            }
        });
        jPanel2.add(jtxttotalsalary);
        jtxttotalsalary.setBounds(820, 830, 140, 30);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("EmployeeID ");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(20, 660, 120, 30);

        jtxtemployeeID.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel2.add(jtxtemployeeID);
        jtxtemployeeID.setBounds(140, 660, 150, 30);

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("PositionID");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(310, 710, 110, 30);

        jtxtposition.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel2.add(jtxtposition);
        jtxtposition.setBounds(410, 710, 130, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Date");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(560, 710, 60, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Name");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(310, 660, 90, 30);

        jtxtname.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtxtname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtnameActionPerformed(evt);
            }
        });
        jPanel2.add(jtxtname);
        jtxtname.setBounds(410, 660, 130, 30);

        jtxthired.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel2.add(jtxthired);
        jtxthired.setBounds(670, 710, 150, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("ManagerID");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(20, 760, 120, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Phone No.");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(560, 660, 110, 30);

        jtxtphone.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtxtphone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtphoneActionPerformed(evt);
            }
        });
        jPanel2.add(jtxtphone);
        jtxtphone.setBounds(670, 660, 150, 30);

        jtxtmanager.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel2.add(jtxtmanager);
        jtxtmanager.setBounds(140, 760, 150, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Address");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(20, 710, 80, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Salary");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(560, 760, 60, 30);

        jtxtsalary.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtxtsalary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtsalaryActionPerformed(evt);
            }
        });
        jPanel2.add(jtxtsalary);
        jtxtsalary.setBounds(670, 760, 150, 30);

        jtxtaddress.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel2.add(jtxtaddress);
        jtxtaddress.setBounds(140, 710, 150, 30);

        tblemployee.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "EmployeeID", "Name", "PhoneNumber", "Address", "Position ID", "HiredDate", "ManagerID", "Salary"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblemployee.setFocusable(false);
        tblemployee.setRowHeight(25);
        tblemployee.getTableHeader().setReorderingAllowed(false);
        tblemployee.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblemployeeMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblemployee);
        if (tblemployee.getColumnModel().getColumnCount() > 0) {
            tblemployee.getColumnModel().getColumn(0).setResizable(false);
            tblemployee.getColumnModel().getColumn(1).setResizable(false);
            tblemployee.getColumnModel().getColumn(2).setResizable(false);
            tblemployee.getColumnModel().getColumn(3).setResizable(false);
            tblemployee.getColumnModel().getColumn(4).setResizable(false);
            tblemployee.getColumnModel().getColumn(5).setResizable(false);
            tblemployee.getColumnModel().getColumn(6).setResizable(false);
            tblemployee.getColumnModel().getColumn(7).setResizable(false);
        }

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(10, 870, 950, 220);

        tblmanager.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ManagerID", "Name", "PhoneNumber", "Address", "Position ID", "HiredDate", "Salary"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblmanager.setFocusable(false);
        tblmanager.setIntercellSpacing(new java.awt.Dimension(0, 0));
        tblmanager.setRowHeight(25);
        tblmanager.getTableHeader().setReorderingAllowed(false);
        tblmanager.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblmanagerMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblmanager);
        if (tblmanager.getColumnModel().getColumnCount() > 0) {
            tblmanager.getColumnModel().getColumn(0).setResizable(false);
            tblmanager.getColumnModel().getColumn(1).setResizable(false);
            tblmanager.getColumnModel().getColumn(2).setResizable(false);
            tblmanager.getColumnModel().getColumn(3).setResizable(false);
            tblmanager.getColumnModel().getColumn(4).setResizable(false);
            tblmanager.getColumnModel().getColumn(5).setResizable(false);
            tblmanager.getColumnModel().getColumn(6).setResizable(false);
        }

        jPanel2.add(jScrollPane3);
        jScrollPane3.setBounds(10, 290, 950, 180);

        jButton8.setText("View Manager Lists");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton8);
        jButton8.setBounds(10, 250, 150, 30);

        jButton9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton9.setText("Add");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton9);
        jButton9.setBounds(310, 220, 100, 30);

        jButton10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton10.setText("Delete");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton10);
        jButton10.setBounds(510, 220, 100, 30);

        jButton11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton11.setText("Update ");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton11);
        jButton11.setBounds(410, 220, 100, 30);

        jtxtsearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtxtsearchKeyReleased(evt);
            }
        });
        jPanel2.add(jtxtsearch);
        jtxtsearch.setBounds(790, 250, 160, 30);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("PositionID");
        jPanel2.add(jLabel11);
        jLabel11.setBounds(20, 160, 91, 30);

        jtxtposition1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel2.add(jtxtposition1);
        jtxtposition1.setBounds(130, 160, 130, 30);

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Date");
        jPanel2.add(jLabel12);
        jLabel12.setBounds(280, 160, 70, 30);

        jtxthired1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel2.add(jtxthired1);
        jtxthired1.setBounds(340, 160, 150, 30);

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Salary");
        jPanel2.add(jLabel14);
        jLabel14.setBounds(800, 110, 70, 30);

        jtxtsalary1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel2.add(jtxtsalary1);
        jtxtsalary1.setBounds(800, 140, 140, 30);

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("ManagerID ");
        jPanel2.add(jLabel15);
        jLabel15.setBounds(20, 110, 120, 30);

        jtxtmanagerid.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel2.add(jtxtmanagerid);
        jtxtmanagerid.setBounds(130, 110, 130, 30);

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Name");
        jPanel2.add(jLabel16);
        jLabel16.setBounds(280, 110, 60, 30);

        jtxtname1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel2.add(jtxtname1);
        jtxtname1.setBounds(340, 110, 150, 30);

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Phone No.");
        jPanel2.add(jLabel17);
        jLabel17.setBounds(510, 110, 100, 30);

        jtxtphone1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel2.add(jtxtphone1);
        jtxtphone1.setBounds(610, 110, 150, 30);

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Address");
        jPanel2.add(jLabel18);
        jLabel18.setBounds(510, 160, 90, 30);

        jtxtaddress1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel2.add(jtxtaddress1);
        jtxtaddress1.setBounds(610, 160, 150, 30);

        jLabel19.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 36)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("MANAGER");
        jPanel2.add(jLabel19);
        jLabel19.setBounds(20, 30, 140, 40);

        jLabel20.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 36)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("EMPLOYEE");
        jPanel2.add(jLabel20);
        jLabel20.setBounds(20, 590, 170, 40);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Search");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(760, 830, 60, 30);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Search");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(720, 250, 60, 30);

        jScrollPane2.setViewportView(jPanel2);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1002, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String sql = "select * from Employee ";
        try{
            PreparedStatement pst = con.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();
            DefaultTableModel model = (DefaultTableModel) tblemployee.getModel();
            model.setRowCount(0);
            while(rs.next()){
                model.addRow(new String[]{rs.getString(1), rs.getString(2), rs.getString(3),rs.getString(4),rs.getString(5),rs.getString(6), rs.getString(7), rs.getString(8)});
            }
        }catch(Exception ex){
            System.out.println("Error : " +ex.getMessage());
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String sql ="insert into Employee"
        + "(EmployeeID, Name, PhoneNumber, Address, PositionID, HiredDate, ManagerID, Salary)"
        +"VALUES (?,?,?,?,?,?,?,?)";
        try{

            PreparedStatement pst  = con.prepareStatement(sql);

            DefaultTableModel model = (DefaultTableModel) tblemployee.getModel();

            pst.setString(1,jtxtemployeeID.getText());
            pst.setString(2,jtxtname.getText());
            pst.setString(3,jtxtphone.getText());
            pst.setString(4,jtxtaddress.getText());
            pst.setString(5,jtxtposition.getText());
            pst.setString(6,jtxthired.getText());
            pst.setString(7,jtxtmanager.getText());
            pst.setString(8,jtxtsalary.getText());
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Inserted Successfully");

        } catch (SQLException | HeadlessException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        String sql ="DELETE FROM Employee WHERE EmployeeID =?";
        try{

            PreparedStatement pst  = con.prepareStatement(sql);

            

            DefaultTableModel model = (DefaultTableModel) tblemployee.getModel();

            pst.setString(1,jtxtemployeeID.getText());
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Deleted Successfully");

        } catch (SQLException | HeadlessException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        String sql = "UPDATE Employee SET  Name=?, PhoneNumber=?, Address=?, PositionID=?, HiredDate=?, ManagerID=?, Salary = ? WHERE EmployeeID=?";
        //String sqL = "SET FOREIGN_KEY_CHECKS = 0";
        try{

            PreparedStatement pst  = con.prepareStatement(sql);
            //PreparedStatement psT  = con.prepareStatement(sqL);
            
            DefaultTableModel model = (DefaultTableModel) tblemployee.getModel();

            pst.setString(8,jtxtemployeeID.getText());
            pst.setString(1,jtxtname.getText());
            pst.setString(2,jtxtphone.getText());
            pst.setString(3,jtxtaddress.getText());
            pst.setString(4,jtxtposition.getText());
            pst.setString(5,jtxthired.getText());
            pst.setString(6,jtxtmanager.getText());
            pst.setString(7,jtxtsalary.getText());
            //psT.executeUpdate();
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Updated Successfully");
            

        } catch (SQLException | HeadlessException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jtxtnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtnameActionPerformed

    private void jtxtphoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtphoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtphoneActionPerformed

    private void jtxtsalaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtsalaryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtsalaryActionPerformed

    private void tblemployeeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblemployeeMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) tblemployee.getModel();

        String tblEmployeeID = model.getValueAt(tblemployee.getSelectedRow(),0).toString();
        String tblName = model.getValueAt(tblemployee.getSelectedRow(),1).toString();
        String tblPhoneNumber = model.getValueAt(tblemployee.getSelectedRow(),2).toString();
        String tblAddress = model.getValueAt(tblemployee.getSelectedRow(),3).toString();
        String tblPositionID = model.getValueAt(tblemployee.getSelectedRow(),4).toString();
        String tblHiredDate = model.getValueAt(tblemployee.getSelectedRow(),5).toString();
        String tblManagerID = model.getValueAt(tblemployee.getSelectedRow(),6).toString();
        String tblSalary = model.getValueAt(tblemployee.getSelectedRow(),7).toString();

        jtxtemployeeID.setText(tblEmployeeID);
        jtxtname.setText(tblName);
        jtxtphone.setText(tblPhoneNumber);
        jtxtaddress.setText(tblAddress);
        jtxtposition.setText(tblPositionID);
        jtxthired.setText(tblHiredDate);
        jtxtmanager.setText(tblManagerID);
        jtxtsalary.setText(tblSalary);
    }//GEN-LAST:event_tblemployeeMouseClicked

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        String sql = "select * from Manager ";
        try{
            PreparedStatement pst = con.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();
            DefaultTableModel model = (DefaultTableModel) tblmanager.getModel();
            model.setRowCount(0);
            while(rs.next()){
                model.addRow(new String[]{rs.getString(1), rs.getString(2), rs.getString(3),rs.getString(4),rs.getString(5),rs.getString(6), rs.getString(7)});
            }
        }catch(Exception ex){
            System.out.println("Error : " +ex.getMessage());
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        String sql ="insert into Manager"
        + "(ManagerID, Name, PhoneNumber, Address, PositionID, HiredDate,Salary)"
        +"VALUES (?,?,?,?,?,?,?)";
        try{

            PreparedStatement pst  = con.prepareStatement(sql);

            DefaultTableModel model = (DefaultTableModel) tblmanager.getModel();

            pst.setString(1,jtxtmanagerid.getText());
            pst.setString(2,jtxtname.getText());
            pst.setString(3,jtxtphone.getText());
            pst.setString(4,jtxtaddress.getText());
            pst.setString(5,jtxtposition.getText());
            pst.setString(6,jtxthired.getText());
            pst.setString(7,jtxtsalary.getText());
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Inserted Successfully");

        } catch (SQLException | HeadlessException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        String sql ="DELETE FROM Manager WHERE ManagerID =?";
        try{

            PreparedStatement pst  = con.prepareStatement(sql);

            DefaultTableModel model = (DefaultTableModel) tblmanager.getModel();

            pst.setString(1,jtxtmanagerid.getText());
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Deleted Successfully");

        } catch (SQLException | HeadlessException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
        String sql = "UPDATE Manager SET  Name=?, PhoneNumber=?, Address=?, PositionID=?, HiredDate=?,Salary = ? WHERE ManagerID=?";
        try{

            PreparedStatement pst  = con.prepareStatement(sql);

            DefaultTableModel model = (DefaultTableModel) tblmanager.getModel();

            pst.setString(7,jtxtmanagerid.getText());
            pst.setString(1,jtxtname.getText());
            pst.setString(2,jtxtphone.getText());
            pst.setString(3,jtxtaddress.getText());
            pst.setString(4,jtxtposition.getText());
            pst.setString(5,jtxthired.getText());
            pst.setString(6,jtxtsalary.getText());
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Updated Successfully");

        } catch (SQLException | HeadlessException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jtxtsearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtsearchKeyReleased
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) tblmanager.getModel();
        TableRowSorter<DefaultTableModel> obj=new TableRowSorter<>(model);
        tblmanager.setRowSorter(obj);
        obj.setRowFilter(RowFilter.regexFilter(jtxtsearch.getText()));
    }//GEN-LAST:event_jtxtsearchKeyReleased

    private void jtxttotalsalaryKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxttotalsalaryKeyReleased
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) tblemployee.getModel();
        TableRowSorter<DefaultTableModel> obj=new TableRowSorter<>(model);
        tblemployee.setRowSorter(obj);
        obj.setRowFilter(RowFilter.regexFilter(jtxttotalsalary.getText()));
    }//GEN-LAST:event_jtxttotalsalaryKeyReleased

    private void tblmanagerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblmanagerMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) tblmanager.getModel();
        
        String tblManagerID = model.getValueAt(tblmanager.getSelectedRow(),0).toString();
        String tblName = model.getValueAt(tblmanager.getSelectedRow(),1).toString();
        String tblPhoneNumber = model.getValueAt(tblmanager.getSelectedRow(),2).toString();
        String tblAddress = model.getValueAt(tblmanager.getSelectedRow(),3).toString();
        String tblPositionID = model.getValueAt(tblmanager.getSelectedRow(),4).toString();
        String tblHiredDate = model.getValueAt(tblmanager.getSelectedRow(),5).toString();
        String tblSalary = model.getValueAt(tblmanager.getSelectedRow(),6).toString();
        
       jtxtmanagerid.setText(tblManagerID);
       jtxtname1.setText(tblName);
       jtxtphone1.setText(tblPhoneNumber);
       jtxtaddress1.setText(tblAddress);
       jtxtposition1.setText(tblPositionID);
       jtxthired1.setText(tblHiredDate);
       jtxtsalary1.setText(tblSalary);
    }//GEN-LAST:event_tblmanagerMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jtxtaddress;
    private javax.swing.JTextField jtxtaddress1;
    private javax.swing.JTextField jtxtemployeeID;
    private javax.swing.JTextField jtxthired;
    private javax.swing.JTextField jtxthired1;
    private javax.swing.JTextField jtxtmanager;
    private javax.swing.JTextField jtxtmanagerid;
    private javax.swing.JTextField jtxtname;
    private javax.swing.JTextField jtxtname1;
    private javax.swing.JTextField jtxtphone;
    private javax.swing.JTextField jtxtphone1;
    private javax.swing.JTextField jtxtposition;
    private javax.swing.JTextField jtxtposition1;
    private javax.swing.JTextField jtxtsalary;
    private javax.swing.JTextField jtxtsalary1;
    private javax.swing.JTextField jtxtsearch;
    private javax.swing.JTextField jtxttotalsalary;
    private javax.swing.JTable tblemployee;
    private javax.swing.JTable tblmanager;
    // End of variables declaration//GEN-END:variables
}
