/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CarDealerSystem;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Angela
 */
public class AdmEmpBonuses extends javax.swing.JInternalFrame {
    
    Connection con;
    /**
     * Creates new form AdmEmpBonuses
     */
    public AdmEmpBonuses() {
        initComponents();
        
        String url = "jdbc:mysql://localhost:3306/car_dealers";
        String user = "root";
        String pass = "";
        try{
            con= DriverManager.getConnection(url,user,pass);
        }catch(Exception ex){
            System.out.println("Error:" + ex.getMessage());
        }
        
        this.setBorder(null);
        BasicInternalFrameUI bui = (BasicInternalFrameUI) this.getUI();
        bui.setNorthPane(null); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblbonus = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jtxtemployeeamount = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jButton6 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblpurchaseproducts = new javax.swing.JTable();
        jButton7 = new javax.swing.JButton();
        jtxtsearch = new javax.swing.JTextField();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jtxtproduct = new javax.swing.JTextField();
        jtxtsupplier = new javax.swing.JTextField();
        jtxtpurchaseID = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jtxtpurchase = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jtxtquantity = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jtxtprice = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jtxtbonus = new javax.swing.JTextField();
        jtxtemployee = new javax.swing.JTextField();
        jtxttitle = new javax.swing.JTextField();
        jtxtdate = new javax.swing.JTextField();
        jtxtamount = new javax.swing.JTextField();
        jButton13 = new javax.swing.JButton();
        jtxtsearchbar = new javax.swing.JTextField();

        jButton1.setText("jButton1");

        setMaximumSize(new java.awt.Dimension(1083, 460));
        setMinimumSize(new java.awt.Dimension(1083, 460));
        setPreferredSize(new java.awt.Dimension(1083, 460));

        jPanel1.setBackground(new java.awt.Color(204, 0, 0));
        jPanel1.setLayout(null);

        tblbonus.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "BonusID", "EmployeeID", "Bonus Title", "Date", "Amount"
            }
        ));
        tblbonus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblbonusMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblbonus);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(30, 210, 710, 140);

        jButton3.setText("View Employee Bonuses");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(30, 170, 160, 23);

        jButton2.setText("Check Total");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(40, 360, 130, 40);
        jPanel1.add(jtxtemployeeamount);
        jtxtemployeeamount.setBounds(190, 370, 160, 30);

        jPanel3.setBackground(new java.awt.Color(204, 0, 0));
        jPanel3.setLayout(null);

        jButton6.setText("back");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton6);
        jButton6.setBounds(630, 330, 82, 23);

        tblpurchaseproducts.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "PurchaseID", "SupplierID", "ProductID", "PurchaseDate", "Purchasequantity", "PurchasePrice"
            }
        ));
        jScrollPane3.setViewportView(tblpurchaseproducts);

        jPanel3.add(jScrollPane3);
        jScrollPane3.setBounds(10, 170, 730, 144);

        jButton7.setText("Search");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton7);
        jButton7.setBounds(600, 130, 110, 23);

        jtxtsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtsearchActionPerformed(evt);
            }
        });
        jPanel3.add(jtxtsearch);
        jtxtsearch.setBounds(520, 130, 66, 30);

        jButton8.setText("Update");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton8);
        jButton8.setBounds(380, 130, 100, 23);

        jButton9.setText("Delete");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton9);
        jButton9.setBounds(270, 130, 100, 20);

        jButton10.setText("Add");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton10);
        jButton10.setBounds(170, 130, 80, 23);

        jButton11.setText("Check Expenses");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton11);
        jButton11.setBounds(10, 130, 140, 23);

        jLabel2.setText("PurchaseID");

        jLabel3.setText("SupplierID");

        jLabel4.setText("ProductID");

        jtxtproduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtproductActionPerformed(evt);
            }
        });

        jtxtpurchaseID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtpurchaseIDActionPerformed(evt);
            }
        });

        jLabel5.setText("PurchaseDate");

        jLabel6.setText("Purchase Quantity");

        jLabel7.setText("Purchase Price");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtxtpurchaseID, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtxtsupplier, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtxtproduct, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtxtpurchase, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtxtquantity, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtxtprice, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(62, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtxtpurchaseID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jtxtsupplier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jtxtproduct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jtxtpurchase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jtxtquantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jtxtprice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );

        jPanel3.add(jPanel4);
        jPanel4.setBounds(10, 10, 720, 100);

        jPanel1.add(jPanel3);
        jPanel3.setBounds(0, 0, 0, 0);

        jButton4.setText("Add");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(210, 170, 80, 23);

        jButton5.setText("Delete");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5);
        jButton5.setBounds(300, 170, 80, 23);

        jButton12.setText("Update");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton12);
        jButton12.setBounds(390, 170, 100, 23);

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("EmployeeID");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(250, 70, 90, 15);

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Bonus Title");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(40, 110, 70, 15);

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Date");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(280, 110, 70, 15);

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Amount");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(500, 110, 70, 15);

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("BonusID");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(40, 70, 70, 15);
        jPanel1.add(jtxtbonus);
        jtxtbonus.setBounds(100, 60, 140, 30);
        jPanel1.add(jtxtemployee);
        jtxtemployee.setBounds(340, 60, 140, 30);
        jPanel1.add(jtxttitle);
        jtxttitle.setBounds(120, 100, 120, 30);
        jPanel1.add(jtxtdate);
        jtxtdate.setBounds(340, 100, 140, 30);

        jtxtamount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtamountActionPerformed(evt);
            }
        });
        jPanel1.add(jtxtamount);
        jtxtamount.setBounds(560, 100, 130, 30);

        jButton13.setText("Search");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton13);
        jButton13.setBounds(630, 170, 110, 23);

        jtxtsearchbar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtsearchbarActionPerformed(evt);
            }
        });
        jtxtsearchbar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtxtsearchbarKeyReleased(evt);
            }
        });
        jPanel1.add(jtxtsearchbar);
        jtxtsearchbar.setBounds(499, 170, 120, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 778, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 438, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        String sql = "select * from EmployeeBonuses";
        try{
            PreparedStatement pst = con.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();
            DefaultTableModel model = (DefaultTableModel) tblbonus.getModel();
            model.setRowCount(0);
            while(rs.next()){
                model.addRow(new String[]{rs.getString(1), rs.getString(2), rs.getString(3),rs.getString(4), rs.getString(5)});
            }
        }catch(Exception ex){
            System.out.println("Error : " +ex.getMessage());
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
       try {
    String searchText = jtxtsearchbar.getText();
    String sqlTotalAmount = "SELECT SUM(Amount) AS TotalAmount FROM EmployeeBonuses WHERE " + 
            "BonusID LIKE ? OR EmployeeID LIKE ? OR Bonus_Title LIKE ? OR Date LIKE ? OR Amount LIKE ?";

    PreparedStatement totalAmountStatement = con.prepareStatement(sqlTotalAmount);

    for (int i = 1; i <= 5; i++) {
        totalAmountStatement.setString(i, "%" + searchText + "%");
    }

    ResultSet resultSet = totalAmountStatement.executeQuery();

    if (resultSet.next()) {
        double totalAmount = resultSet.getDouble("TotalAmount");

        String formattedTotalAmount = String.format("%.2f", totalAmount);
        jtxtemployeeamount.setText(formattedTotalAmount);
    } else {
        jtxtemployeeamount.setText("0.00"); 
    }

    resultSet.close();
    totalAmountStatement.close();
} catch (SQLException ex) {
    JOptionPane.showMessageDialog(null, ex);
}
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) tblpurchaseproducts.getModel();
        TableRowSorter<DefaultTableModel> obj=new TableRowSorter<>(model);
        tblpurchaseproducts.setRowSorter(obj);
        obj.setRowFilter(RowFilter.regexFilter(jtxtsearch.getText()));
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jtxtsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtsearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtsearchActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jtxtproductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtproductActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtproductActionPerformed

    private void jtxtpurchaseIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtpurchaseIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtpurchaseIDActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        String sql = "INSERT INTO EmployeeBonuses (BonusID, EmployeeID, Bonus_Title, Date, Amount)  VALUES (?,?,?,?,?)";
        try {
            PreparedStatement pst = con.prepareStatement(sql);
            DefaultTableModel model = (DefaultTableModel) tblbonus.getModel();
            pst.setString(1, jtxtbonus.getText());
            pst.setString(2, jtxtemployee.getText());
            pst.setString(3, jtxttitle.getText());
            pst.setString(4, jtxtdate.getText());
            pst.setString(5, jtxtamount.getText());
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Inserted Successfully");
        } catch (SQLException | HeadlessException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
         String sql ="DELETE FROM EmployeeBonuses WHERE BonusID =?";
        try{

            PreparedStatement pst  = con.prepareStatement(sql);

            DefaultTableModel model = (DefaultTableModel) tblbonus.getModel();

            pst.setString(1,jtxtbonus.getText());
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Deleted Successfully");

        } catch (SQLException | HeadlessException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
        String sql = "UPDATE EmployeeBonuses SET  EmployeeID=?, Bonus_Title=?, Date=?, Amount=? WHERE BonusID=?";
        try{

            PreparedStatement pst  = con.prepareStatement(sql);

            DefaultTableModel model = (DefaultTableModel) tblbonus.getModel();

            pst.setString(5,jtxtbonus.getText());
            pst.setString(1,jtxtemployee.getText());
            pst.setString(2,jtxttitle.getText());
            pst.setString(3,jtxtdate.getText());
            pst.setString(4,jtxtamount.getText());
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Updated Successfully");

        } catch (SQLException | HeadlessException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) tblbonus.getModel();
        TableRowSorter<DefaultTableModel> obj=new TableRowSorter<>(model);
        tblbonus.setRowSorter(obj);
        obj.setRowFilter(RowFilter.regexFilter(jtxtsearchbar.getText()));
    }//GEN-LAST:event_jButton13ActionPerformed

    private void tblbonusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblbonusMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) tblbonus.getModel();
        
        String tblBonusID = model.getValueAt(tblbonus.getSelectedRow(),0).toString();
        String tblEmployeeID = model.getValueAt(tblbonus.getSelectedRow(),1).toString();
        String tblBonusTitle  = model.getValueAt(tblbonus.getSelectedRow(),2).toString();
        String tblDate = model.getValueAt(tblbonus.getSelectedRow(),3).toString();
        String tblAmount= model.getValueAt(tblbonus.getSelectedRow(),4).toString();
                
       jtxtbonus.setText(tblBonusID);
       jtxtemployee.setText(tblEmployeeID);
       jtxttitle.setText(tblBonusTitle);
       jtxtdate.setText(tblDate);
       jtxtamount.setText(tblAmount);
    }//GEN-LAST:event_tblbonusMouseClicked

    private void jtxtsearchbarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtsearchbarKeyReleased
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) tblpurchaseproducts.getModel();
        TableRowSorter<DefaultTableModel> obj=new TableRowSorter<>(model);
        tblpurchaseproducts.setRowSorter(obj);
        obj.setRowFilter(RowFilter.regexFilter(jtxtsearch.getText()));
    }//GEN-LAST:event_jtxtsearchbarKeyReleased

    private void jtxtsearchbarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtsearchbarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtsearchbarActionPerformed

    private void jtxtamountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtamountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtamountActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jtxtamount;
    private javax.swing.JTextField jtxtbonus;
    private javax.swing.JTextField jtxtdate;
    private javax.swing.JTextField jtxtemployee;
    private javax.swing.JTextField jtxtemployeeamount;
    private javax.swing.JTextField jtxtprice;
    private javax.swing.JTextField jtxtproduct;
    private javax.swing.JTextField jtxtpurchase;
    private javax.swing.JTextField jtxtpurchaseID;
    private javax.swing.JTextField jtxtquantity;
    private javax.swing.JTextField jtxtsearch;
    private javax.swing.JTextField jtxtsearchbar;
    private javax.swing.JTextField jtxtsupplier;
    private javax.swing.JTextField jtxttitle;
    private javax.swing.JTable tblbonus;
    private javax.swing.JTable tblpurchaseproducts;
    // End of variables declaration//GEN-END:variables
}
