/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CarDealerSystem;

import java.awt.Color;
import java.awt.Font;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Angela
 */
public class AdminCustomers extends javax.swing.JInternalFrame {
    
    Connection con;
    /**
     * Creates new form AdminCustomers
     */
    public AdminCustomers() {
        initComponents();
        
        String url = "jdbc:mysql://localhost:3306/car_dealers";
        String user = "root";
        String pass = "";
        try{
            con= DriverManager.getConnection(url,user,pass);
        }catch(Exception ex){
            System.out.println("Error:" + ex.getMessage());
        }
        
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0)); //no space
        BasicInternalFrameUI bui = (BasicInternalFrameUI) this.getUI();
        bui.setNorthPane(null);
        
        tblcustomer.getTableHeader().setFont(new Font ("Segoe UI", Font.PLAIN,14));
        tblcustomer.getTableHeader().setOpaque(false);
        tblcustomer.getTableHeader().setForeground(new Color(204,0,0));
        tblcustomer.setRowHeight(25);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AdminCollaborativedesktop = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jtxtcustomerid = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jtxtname = new javax.swing.JTextField();
        jtxtemployee = new javax.swing.JTextField();
        jtxtproduct = new javax.swing.JTextField();
        jtxtproductname = new javax.swing.JTextField();
        jtxtprice = new javax.swing.JTextField();
        jtxtdate = new javax.swing.JTextField();
        jtxtaddress = new javax.swing.JTextField();
        jtxtcontact = new javax.swing.JTextField();
        jtxtsearch = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblcustomer = new javax.swing.JTable();

        setPreferredSize(new java.awt.Dimension(1002, 900));

        AdminCollaborativedesktop.setBackground(new java.awt.Color(204, 0, 0));
        AdminCollaborativedesktop.setMaximumSize(new java.awt.Dimension(1002, 500));
        AdminCollaborativedesktop.setMinimumSize(new java.awt.Dimension(1002, 500));
        AdminCollaborativedesktop.setPreferredSize(new java.awt.Dimension(1002, 500));
        AdminCollaborativedesktop.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setText("View Customer List");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        AdminCollaborativedesktop.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 156, 30));

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton3.setText("Add");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        AdminCollaborativedesktop.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 180, 100, 30));

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton4.setText("Delete");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        AdminCollaborativedesktop.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 180, 100, 30));

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton5.setText("Update ");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        AdminCollaborativedesktop.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 180, 120, 30));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("CustomerName");
        AdminCollaborativedesktop.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 30, 180, -1));

        jtxtcustomerid.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        AdminCollaborativedesktop.add(jtxtcustomerid, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, 120, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ProductID");
        AdminCollaborativedesktop.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 130, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("SoldDate");
        AdminCollaborativedesktop.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 130, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("CustomerID");
        AdminCollaborativedesktop.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 180, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Price");
        AdminCollaborativedesktop.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 80, 60, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("CustomerContact");
        AdminCollaborativedesktop.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 130, 170, 30));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("EmployeeID");
        AdminCollaborativedesktop.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 30, 120, 30));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("ProductName");
        AdminCollaborativedesktop.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 80, 150, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("CustomerAddress");
        AdminCollaborativedesktop.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 130, 170, -1));

        jtxtname.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        AdminCollaborativedesktop.add(jtxtname, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 30, 190, 30));

        jtxtemployee.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtxtemployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtemployeeActionPerformed(evt);
            }
        });
        AdminCollaborativedesktop.add(jtxtemployee, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 30, 150, 30));

        jtxtproduct.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        AdminCollaborativedesktop.add(jtxtproduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, 120, 30));

        jtxtproductname.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        AdminCollaborativedesktop.add(jtxtproductname, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 80, 190, 30));

        jtxtprice.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        AdminCollaborativedesktop.add(jtxtprice, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 80, 150, 30));

        jtxtdate.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtxtdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtdateActionPerformed(evt);
            }
        });
        AdminCollaborativedesktop.add(jtxtdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, 120, 30));

        jtxtaddress.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtxtaddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtaddressActionPerformed(evt);
            }
        });
        AdminCollaborativedesktop.add(jtxtaddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 130, 190, 30));

        jtxtcontact.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        AdminCollaborativedesktop.add(jtxtcontact, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 130, 150, 30));

        jtxtsearch.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtxtsearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtxtsearchMouseClicked(evt);
            }
        });
        jtxtsearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtxtsearchKeyReleased(evt);
            }
        });
        AdminCollaborativedesktop.add(jtxtsearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 210, 150, 30));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Search");
        AdminCollaborativedesktop.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 210, -1, 30));

        jScrollPane1.setBorder(null);

        tblcustomer.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "CustomerID", "CustomerName", "EmployeeID", "ProductID", "ProductName", "Price ", "SoldDate", "Address", "Contacts"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblcustomer.getTableHeader().setReorderingAllowed(false);
        tblcustomer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblcustomerMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblcustomer);
        if (tblcustomer.getColumnModel().getColumnCount() > 0) {
            tblcustomer.getColumnModel().getColumn(0).setResizable(false);
            tblcustomer.getColumnModel().getColumn(1).setResizable(false);
            tblcustomer.getColumnModel().getColumn(2).setResizable(false);
            tblcustomer.getColumnModel().getColumn(3).setResizable(false);
            tblcustomer.getColumnModel().getColumn(4).setResizable(false);
            tblcustomer.getColumnModel().getColumn(5).setResizable(false);
            tblcustomer.getColumnModel().getColumn(6).setResizable(false);
            tblcustomer.getColumnModel().getColumn(7).setResizable(false);
            tblcustomer.getColumnModel().getColumn(8).setResizable(false);
        }

        AdminCollaborativedesktop.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 960, 220));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1002, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(AdminCollaborativedesktop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 870, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(AdminCollaborativedesktop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String sql = "select * from Customer";
        try{
            PreparedStatement pst = con.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();
            DefaultTableModel model = (DefaultTableModel) tblcustomer.getModel();
            model.setRowCount(0);
            while(rs.next()){
                model.addRow(new String[]{rs.getString(1), rs.getString(2), rs.getString(3), rs.getString(4),rs.getString(5),rs.getString(6), rs.getString(7),rs.getString(8),rs.getString(9)});
            }
        }catch(Exception ex){
            System.out.println("Error : " +ex.getMessage());
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        String sql ="insert into Customer"
        + "(CustomerID,Customername,EmployeeID,ProductID,ProductName,Price,SoldDate,CustomerAddress,CustomerContact)"
        +"VALUES (?,?,?,?,?,?,?,?,?)";
        try{

            PreparedStatement pst  = con.prepareStatement(sql);

            DefaultTableModel model = (DefaultTableModel) tblcustomer.getModel();

            pst.setString(1,jtxtcustomerid.getText());
            pst.setString(2,jtxtname.getText());
            pst.setString(3,jtxtemployee.getText());
            pst.setString(4,jtxtproduct.getText());
            pst.setString(5,jtxtproductname.getText());
            pst.setString(6,jtxtprice.getText());
            pst.setString(7,jtxtdate.getText());
            pst.setString(8,jtxtaddress.getText());
            pst.setString(9,jtxtcontact.getText());
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Inserted Successfully");

        } catch (SQLException | HeadlessException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        String sql = "DELETE FROM Customer WHERE CustomerID =?";
        try{

            PreparedStatement pst  = con.prepareStatement(sql);
            DefaultTableModel model = (DefaultTableModel) tblcustomer.getModel();

            pst.setString(1,jtxtcustomerid.getText());
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Deleted Successfully");

        } catch (SQLException | HeadlessException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }

    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        String sql = "UPDATE Customer SET Customername=?,EmployeeID = ?,ProductID = ?, ProductName =?,Price =?,SoldDate =?, CustomerAddress=?,CustomerContact=? WHERE CustomerID = ?";
        try{

            PreparedStatement pst  = con.prepareStatement(sql);

            DefaultTableModel model = (DefaultTableModel) tblcustomer.getModel();

            pst.setString(9,jtxtcustomerid.getText());
            pst.setString(1,jtxtname.getText());
            pst.setString(2,jtxtemployee.getText());
            pst.setString(3,jtxtproduct.getText());
            pst.setString(4,jtxtproductname.getText());
            pst.setString(5,jtxtprice.getText());
            pst.setString(6,jtxtdate.getText());
            pst.setString(7,jtxtaddress.getText());
            pst.setString(8,jtxtcontact.getText());
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Updated Successfully");

        } catch (SQLException | HeadlessException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jtxtdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtdateActionPerformed

    private void jtxtaddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtaddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtaddressActionPerformed

    private void jtxtsearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxtsearchMouseClicked
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jtxtsearchMouseClicked

    private void jtxtsearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtsearchKeyReleased
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) tblcustomer.getModel();
        TableRowSorter<DefaultTableModel> obj=new TableRowSorter<>(model);
        tblcustomer.setRowSorter(obj);
        obj.setRowFilter(RowFilter.regexFilter(jtxtsearch.getText()));
    }//GEN-LAST:event_jtxtsearchKeyReleased

    private void jtxtemployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtemployeeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtemployeeActionPerformed

    private void tblcustomerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblcustomerMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) tblcustomer.getModel();

        String tblCustomerID = model.getValueAt(tblcustomer.getSelectedRow(),0).toString();
        String tblCustomerName = model.getValueAt(tblcustomer.getSelectedRow(),1).toString();
        String tblEmployeeID  = model.getValueAt(tblcustomer.getSelectedRow(),2).toString();
        String tblProductID= model.getValueAt(tblcustomer.getSelectedRow(),3).toString();
        String tblProductName= model.getValueAt(tblcustomer.getSelectedRow(),4).toString();
        String tblPrice= model.getValueAt(tblcustomer.getSelectedRow(),5).toString();
        String tblSoldDate= model.getValueAt(tblcustomer.getSelectedRow(),6).toString();
        String tblCustomerAddress= model.getValueAt(tblcustomer.getSelectedRow(),7).toString();
        String tblCustomerContact= model.getValueAt(tblcustomer.getSelectedRow(),8).toString();

        jtxtcustomerid.setText(tblCustomerID);
        jtxtname.setText(tblCustomerName);
        jtxtemployee.setText(tblEmployeeID);
        jtxtproduct.setText(tblProductID);
        jtxtproductname.setText(tblProductName);
        jtxtprice.setText(tblPrice);
        jtxtdate.setText(tblSoldDate);
        jtxtaddress.setText(tblCustomerAddress);
        jtxtcontact.setText(tblCustomerContact);

    }//GEN-LAST:event_tblcustomerMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AdminCollaborativedesktop;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jtxtaddress;
    private javax.swing.JTextField jtxtcontact;
    private javax.swing.JTextField jtxtcustomerid;
    private javax.swing.JTextField jtxtdate;
    private javax.swing.JTextField jtxtemployee;
    private javax.swing.JTextField jtxtname;
    private javax.swing.JTextField jtxtprice;
    private javax.swing.JTextField jtxtproduct;
    private javax.swing.JTextField jtxtproductname;
    private javax.swing.JTextField jtxtsearch;
    private javax.swing.JTable tblcustomer;
    // End of variables declaration//GEN-END:variables

         
}
