/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CarDealerSystem;

import java.awt.Color;
import java.awt.Font;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Angela
 */
public class AdminStockProducts extends javax.swing.JInternalFrame {
    Connection con;
    /**
     * Creates new form AdminStockProducts
     */
    public AdminStockProducts() {
        initComponents();
        
        String url = "jdbc:mysql://localhost:3306/car_dealers";
        String user = "root";
        String pass = "";
        try{
            con= DriverManager.getConnection(url,user,pass);
        }catch(Exception ex){
            System.out.println("Error:" + ex.getMessage());
        }
        
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0)); //no space
        BasicInternalFrameUI bui = (BasicInternalFrameUI) this.getUI();
        bui.setNorthPane(null);
        
        
        tblstocks.getTableHeader().setFont(new Font ("Segoe UI", Font.PLAIN,16));
        tblstocks.getTableHeader().setOpaque(false);
        tblstocks.getTableHeader().setForeground(new Color(204,0,0));
        tblstocks.setRowHeight(25);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblstocks = new javax.swing.JTable();
        ViewStocks = new javax.swing.JButton();
        Add = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jtxtstockid = new javax.swing.JTextField();
        jtxtproduct = new javax.swing.JTextField();
        jtxtquantity = new javax.swing.JTextField();
        jtxtpurchaseprice = new javax.swing.JTextField();
        Delete = new javax.swing.JButton();
        Update = new javax.swing.JButton();
        jtxtsearch = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(1002, 500));
        setPreferredSize(new java.awt.Dimension(1002, 500));

        jPanel1.setBackground(new java.awt.Color(204, 0, 0));
        jPanel1.setMinimumSize(new java.awt.Dimension(1002, 500));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblstocks.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "StockID", "ProductID", "QuantityInStock", "PurchasePrice"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblstocks.setFocusable(false);
        tblstocks.setIntercellSpacing(new java.awt.Dimension(0, 0));
        tblstocks.setRowHeight(25);
        tblstocks.getTableHeader().setReorderingAllowed(false);
        tblstocks.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblstocksMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblstocks);
        if (tblstocks.getColumnModel().getColumnCount() > 0) {
            tblstocks.getColumnModel().getColumn(0).setResizable(false);
            tblstocks.getColumnModel().getColumn(1).setResizable(false);
            tblstocks.getColumnModel().getColumn(2).setResizable(false);
            tblstocks.getColumnModel().getColumn(3).setResizable(false);
        }

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 960, 160));

        ViewStocks.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        ViewStocks.setText("View Stocks");
        ViewStocks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewStocksActionPerformed(evt);
            }
        });
        jPanel1.add(ViewStocks, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 120, 30));

        Add.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Add.setText("Add");
        Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddActionPerformed(evt);
            }
        });
        jPanel1.add(Add, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 50, 90, 30));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("StockID");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 100, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ProductID");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 120, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("QuantityInStock");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 60, 180, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("PurchasePrice");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 120, 160, 30));

        jtxtstockid.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel1.add(jtxtstockid, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 140, 30));
        jPanel1.add(jtxtproduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 140, 30));

        jtxtquantity.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtxtquantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtquantityActionPerformed(evt);
            }
        });
        jPanel1.add(jtxtquantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 60, 160, 30));

        jtxtpurchaseprice.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtxtpurchaseprice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtpurchasepriceActionPerformed(evt);
            }
        });
        jPanel1.add(jtxtpurchaseprice, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 120, 160, 30));

        Delete.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Delete.setText("Delete");
        Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteActionPerformed(evt);
            }
        });
        jPanel1.add(Delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 130, 90, 30));

        Update.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Update.setText("Update");
        Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateActionPerformed(evt);
            }
        });
        jPanel1.add(Update, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 90, 90, 30));

        jtxtsearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtxtsearchKeyReleased(evt);
            }
        });
        jPanel1.add(jtxtsearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 250, 140, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Search");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 250, -1, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1002, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 504, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ViewStocksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewStocksActionPerformed
        // TODO add your handling code here:
        String sql = "select * from StockProducts";
        try{
            PreparedStatement pst = con.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();
            DefaultTableModel model = (DefaultTableModel) tblstocks.getModel();
            model.setRowCount(0);
            while(rs.next()){
                model.addRow(new String[]{rs.getString(1), rs.getString(2), rs.getString(3),rs.getString(4)});
            }
        }catch(Exception ex){
            System.out.println("Error : " +ex.getMessage());
        }
    }//GEN-LAST:event_ViewStocksActionPerformed

    private void jtxtquantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtquantityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtquantityActionPerformed

    private void jtxtpurchasepriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtpurchasepriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtpurchasepriceActionPerformed

    private void AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddActionPerformed
      
     String sql ="insert into StockProducts"
        + "(StockID, ProductID, QuantityInStock, PurchasePrice)"
        +"VALUES (?,?,?,?)";
        try{

            PreparedStatement pst  = con.prepareStatement(sql);

            DefaultTableModel model = (DefaultTableModel) tblstocks.getModel();

            pst.setString(1,jtxtstockid.getText());
            pst.setString(2,jtxtproduct.getText());
            pst.setString(3,jtxtquantity.getText());
            pst.setString(4,jtxtpurchaseprice.getText());
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Inserted Successfully");

        } catch (SQLException | HeadlessException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
  
    }//GEN-LAST:event_AddActionPerformed

    private void DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteActionPerformed
        // TODO add your handling code here:
        String sql = "DELETE FROM StockProducts WHERE StockID =?";
        try{

            PreparedStatement pst  = con.prepareStatement(sql);
            DefaultTableModel model = (DefaultTableModel) tblstocks.getModel();

            pst.setString(1,jtxtstockid.getText());
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Deleted Successfully");

        } catch (SQLException | HeadlessException ex) {
            JOptionPane.showMessageDialog(null, ex);
        } 
    }//GEN-LAST:event_DeleteActionPerformed

    private void UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateActionPerformed
        // TODO add your handling code here:
        String sql = "UPDATE StockProducts SET ProductID=?, QuantityInStock=?, PurchasePrice=? WHERE StockID = ?";
        try{

            PreparedStatement pst  = con.prepareStatement(sql);

             DefaultTableModel model = (DefaultTableModel) tblstocks.getModel();

            pst.setString(4,jtxtstockid.getText());
            pst.setString(1,jtxtproduct.getText());
            pst.setString(2,jtxtquantity.getText());
            pst.setString(3,jtxtpurchaseprice.getText());
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Updated Successfully");

        } catch (SQLException | HeadlessException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_UpdateActionPerformed

    private void tblstocksMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblstocksMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) tblstocks.getModel();
        
        String tblStockID = model.getValueAt(tblstocks.getSelectedRow(),0).toString();
        String tblProductID= model.getValueAt(tblstocks.getSelectedRow(),1).toString();
        String tblQuantityInStock = model.getValueAt(tblstocks.getSelectedRow(),2).toString();
        String tblPurchasePrice = model.getValueAt(tblstocks.getSelectedRow(),3).toString();
        
        
       jtxtstockid.setText(tblStockID);
       jtxtproduct.setText(tblProductID);
       jtxtquantity.setText(tblQuantityInStock);
       jtxtpurchaseprice.setText(tblPurchasePrice);
       
    }//GEN-LAST:event_tblstocksMouseClicked

    private void jtxtsearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtsearchKeyReleased
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) tblstocks.getModel();
        TableRowSorter<DefaultTableModel> obj=new TableRowSorter<>(model);
        tblstocks.setRowSorter(obj);
        obj.setRowFilter(RowFilter.regexFilter(jtxtsearch.getText()));        
    }//GEN-LAST:event_jtxtsearchKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add;
    private javax.swing.JButton Delete;
    private javax.swing.JButton Update;
    private javax.swing.JButton ViewStocks;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jtxtproduct;
    private javax.swing.JTextField jtxtpurchaseprice;
    private javax.swing.JTextField jtxtquantity;
    private javax.swing.JTextField jtxtsearch;
    private javax.swing.JTextField jtxtstockid;
    private javax.swing.JTable tblstocks;
    // End of variables declaration//GEN-END:variables
}
