/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CarDealerSystem;

import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author Angela
 */
public class AdminAccounting extends javax.swing.JInternalFrame {

    /**
     * Creates new form AdminAccounting
     */
    public AdminAccounting() {
        initComponents();
        
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0)); //no space
        BasicInternalFrameUI bui = (BasicInternalFrameUI) this.getUI();
        bui.setNorthPane(null);
        
        jButton1.setBorder(BorderFactory.createEmptyBorder(4, 4, 4, 4));
        jButton1.setContentAreaFilled(false); 
        
        jButton4.setBorder(BorderFactory.createEmptyBorder(4, 4, 4, 4));
        jButton4.setContentAreaFilled(false); 
        
        jButton5.setBorder(BorderFactory.createEmptyBorder(4, 4, 4, 4));
        jButton5.setContentAreaFilled(false); 
        
        jButton6.setBorder(BorderFactory.createEmptyBorder(4, 4, 4, 4));
        jButton6.setContentAreaFilled(false); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panelborder = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        Accountingdesktop = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(1050, 768));
        setMinimumSize(new java.awt.Dimension(1050, 768));
        setPreferredSize(new java.awt.Dimension(1050, 768));

        jPanel1.setMinimumSize(new java.awt.Dimension(1137, 799));
        jPanel1.setPreferredSize(new java.awt.Dimension(1137, 799));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelborder.setBackground(new java.awt.Color(204, 0, 0));
        panelborder.setMinimumSize(new java.awt.Dimension(1110, 100));
        panelborder.setPreferredSize(new java.awt.Dimension(1110, 100));
        panelborder.setLayout(null);

        jButton1.setBackground(new java.awt.Color(204, 0, 0));
        jButton1.setFont(new java.awt.Font("Felix Titling", 1, 20)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Payroll");
        jButton1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(141, 1, 1), 2, true));
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton1MousePressed(evt);
            }
        });
        panelborder.add(jButton1);
        jButton1.setBounds(40, 40, 162, 40);

        jButton6.setBackground(new java.awt.Color(204, 0, 0));
        jButton6.setFont(new java.awt.Font("Felix Titling", 1, 20)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("Sold Products");
        jButton6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(141, 1, 1), 2, true));
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton6MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton6MousePressed(evt);
            }
        });
        panelborder.add(jButton6);
        jButton6.setBounds(750, 40, 246, 40);

        jButton5.setBackground(new java.awt.Color(204, 0, 0));
        jButton5.setFont(new java.awt.Font("Felix Titling", 1, 20)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Purchase Products");
        jButton5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(141, 1, 1), 2, true));
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton5MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton5MousePressed(evt);
            }
        });
        panelborder.add(jButton5);
        jButton5.setBounds(430, 40, 289, 40);

        jButton4.setBackground(new java.awt.Color(204, 0, 0));
        jButton4.setFont(new java.awt.Font("Felix Titling", 1, 20)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Bonuses");
        jButton4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(141, 1, 1), 2, true));
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton4MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton4MousePressed(evt);
            }
        });
        panelborder.add(jButton4);
        jButton4.setBounds(240, 40, 162, 40);

        jPanel1.add(panelborder, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, -1));

        Accountingdesktop.setBackground(new java.awt.Color(204, 0, 0));
        Accountingdesktop.setMaximumSize(new java.awt.Dimension(1002, 500));
        Accountingdesktop.setMinimumSize(new java.awt.Dimension(1002, 500));
        Accountingdesktop.setPreferredSize(new java.awt.Dimension(1002, 500));

        javax.swing.GroupLayout AccountingdesktopLayout = new javax.swing.GroupLayout(Accountingdesktop);
        Accountingdesktop.setLayout(AccountingdesktopLayout);
        AccountingdesktopLayout.setHorizontalGroup(
            AccountingdesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1002, Short.MAX_VALUE)
        );
        AccountingdesktopLayout.setVerticalGroup(
            AccountingdesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );

        jPanel1.add(Accountingdesktop, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        jLabel1.setFont(new java.awt.Font("Felix Titling", 1, 14)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CarDealerSystem/car1099.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1140, 800));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1080, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 770, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MousePressed
        // TODO add your handling code here:
        jButton6.setContentAreaFilled(false);
        jButton4.setContentAreaFilled(false);
        jButton5.setContentAreaFilled(false);
        
        jButton1.setContentAreaFilled(true);
        jButton1.setBackground(new Color(148, 1, 1));
        jButton1.setOpaque(true);
        
        AdmMngrSalary emp = new AdmMngrSalary();
        Accountingdesktop.removeAll();
        Accountingdesktop.add(emp).setVisible(true);
    }//GEN-LAST:event_jButton1MousePressed

    private void jButton1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseExited
        // TODO add your handling code here:
        jButton1.setContentAreaFilled(true);
    }//GEN-LAST:event_jButton1MouseExited

    private void jButton4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MousePressed
        // TODO add your handling code here:
        jButton6.setContentAreaFilled(false);
        jButton1.setContentAreaFilled(false);
        jButton5.setContentAreaFilled(false);
        
        jButton4.setContentAreaFilled(true);
        jButton4.setBackground(new Color(148, 1, 1));
        jButton4.setOpaque(true);
        
        AdmMngrBonuses emp = new AdmMngrBonuses();
        Accountingdesktop.removeAll();
        Accountingdesktop.add(emp).setVisible(true);
    }//GEN-LAST:event_jButton4MousePressed

    private void jButton4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseExited
        // TODO add your handling code here:
        jButton4.setContentAreaFilled(true);
    }//GEN-LAST:event_jButton4MouseExited

    private void jButton5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MousePressed
        // TODO add your handling code here:
        jButton6.setContentAreaFilled(false);
        jButton1.setContentAreaFilled(false);
        jButton4.setContentAreaFilled(false);
        
        jButton5.setContentAreaFilled(true);
        jButton5.setBackground(new Color(148, 1, 1));
        jButton5.setOpaque(true);
        
        AdmPurchaseProducts emp = new AdmPurchaseProducts();
        Accountingdesktop.removeAll();
        Accountingdesktop.add(emp).setVisible(true);
    }//GEN-LAST:event_jButton5MousePressed

    private void jButton5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseExited
        // TODO add your handling code here:
        jButton5.setContentAreaFilled(true);
    }//GEN-LAST:event_jButton5MouseExited

    private void jButton6MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MousePressed
        // TODO add your handling code here:
        jButton5.setContentAreaFilled(false);
        jButton1.setContentAreaFilled(false);
        jButton4.setContentAreaFilled(false);
        
        jButton6.setContentAreaFilled(true);
        jButton6.setBackground(new Color(148, 1, 1));
        jButton6.setOpaque(true);
        
        AdmSoldProducts emp = new AdmSoldProducts();
        Accountingdesktop.removeAll();
        Accountingdesktop.add(emp).setVisible(true);
    }//GEN-LAST:event_jButton6MousePressed

    private void jButton6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseExited
        // TODO add your handling code here:
        jButton6.setContentAreaFilled(true);
    }//GEN-LAST:event_jButton6MouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Accountingdesktop;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel panelborder;
    // End of variables declaration//GEN-END:variables
}
