/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CarDealerSystem;

import java.awt.Color;
import java.awt.Font;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Angela
 */
public class AdminPosition extends javax.swing.JInternalFrame {
    
    Connection con;
    /**
     * Creates new form AdminPosition
     */
    public AdminPosition() {
        initComponents();
        String url = "jdbc:mysql://localhost:3306/car_dealers";
        String user = "root";
        String pass = "";
        try{
            con= DriverManager.getConnection(url,user,pass);
        }catch(Exception ex){
            System.out.println("Error:" + ex.getMessage());
        }
        
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0)); //no space
        BasicInternalFrameUI bui = (BasicInternalFrameUI) this.getUI();
        bui.setNorthPane(null);
        
        tblposition.getTableHeader().setFont(new Font ("Segoe UI", Font.PLAIN,16));
        tblposition.getTableHeader().setOpaque(false);
        tblposition.getTableHeader().setForeground(new Color(204,0,0));
        tblposition.setRowHeight(25);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblposition = new javax.swing.JTable();
        ViewPosition = new javax.swing.JButton();
        Add = new javax.swing.JButton();
        Delete = new javax.swing.JButton();
        Update = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jtxtposition = new javax.swing.JTextField();
        jtxtname = new javax.swing.JTextField();

        setMaximumSize(new java.awt.Dimension(1002, 900));
        setMinimumSize(new java.awt.Dimension(1002, 900));
        setPreferredSize(new java.awt.Dimension(1002, 900));

        jPanel1.setBackground(new java.awt.Color(204, 0, 0));
        jPanel1.setMinimumSize(new java.awt.Dimension(1002, 500));
        jPanel1.setPreferredSize(new java.awt.Dimension(1002, 500));
        jPanel1.setLayout(null);

        tblposition.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "PositionID", "PositionName"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblposition.setFocusable(false);
        tblposition.setIntercellSpacing(new java.awt.Dimension(0, 0));
        tblposition.setRowHeight(25);
        tblposition.getTableHeader().setReorderingAllowed(false);
        tblposition.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblpositionMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblposition);
        if (tblposition.getColumnModel().getColumnCount() > 0) {
            tblposition.getColumnModel().getColumn(0).setResizable(false);
            tblposition.getColumnModel().getColumn(1).setResizable(false);
        }

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(10, 260, 960, 185);

        ViewPosition.setText("View Position");
        ViewPosition.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewPositionActionPerformed(evt);
            }
        });
        jPanel1.add(ViewPosition);
        ViewPosition.setBounds(10, 220, 120, 30);

        Add.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Add.setText("Add");
        Add.setMaximumSize(new java.awt.Dimension(57, 28));
        Add.setMinimumSize(new java.awt.Dimension(57, 28));
        Add.setPreferredSize(new java.awt.Dimension(57, 28));
        Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddActionPerformed(evt);
            }
        });
        jPanel1.add(Add);
        Add.setBounds(320, 170, 110, 30);

        Delete.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Delete.setText("Delete");
        Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteActionPerformed(evt);
            }
        });
        jPanel1.add(Delete);
        Delete.setBounds(520, 170, 110, 30);

        Update.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Update.setText("Update");
        Update.setMaximumSize(new java.awt.Dimension(57, 28));
        Update.setMinimumSize(new java.awt.Dimension(57, 28));
        Update.setPreferredSize(new java.awt.Dimension(57, 28));
        Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateActionPerformed(evt);
            }
        });
        jPanel1.add(Update);
        Update.setBounds(430, 170, 90, 30);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("PositionID");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(320, 50, 120, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("PositionName");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(320, 110, 140, 30);

        jtxtposition.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtxtposition.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtpositionActionPerformed(evt);
            }
        });
        jPanel1.add(jtxtposition);
        jtxtposition.setBounds(470, 50, 160, 30);

        jtxtname.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtxtname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtnameActionPerformed(evt);
            }
        });
        jPanel1.add(jtxtname);
        jtxtname.setBounds(470, 110, 160, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ViewPositionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewPositionActionPerformed
        // TODO add your handling code here:
        String sql = "select * from Positions";
        try{
            PreparedStatement pst = con.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();
            DefaultTableModel model = (DefaultTableModel) tblposition.getModel();
            model.setRowCount(0);
        while(rs.next()){
                model.addRow(new String[]{rs.getString(1), rs.getString(2)});
            }
        }catch(Exception ex){
            System.out.println("Error : " +ex.getMessage());
        } 
    }//GEN-LAST:event_ViewPositionActionPerformed

    private void UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateActionPerformed
        // TODO add your handling code here:
        String sql = "UPDATE Positions SET PositionName=? WHERE PositionID = ?";
        try{

            PreparedStatement pst  = con.prepareStatement(sql);

             DefaultTableModel model = (DefaultTableModel) tblposition.getModel();

            pst.setString(2,jtxtposition.getText());
            pst.setString(1,jtxtname.getText());
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Updated Successfully");

        } catch (SQLException | HeadlessException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_UpdateActionPerformed

    private void DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteActionPerformed
        // TODO add your handling code here:
        String sql = "DELETE FROM Positions WHERE PositionID =?";
        try{

            PreparedStatement pst  = con.prepareStatement(sql);
            DefaultTableModel model = (DefaultTableModel) tblposition.getModel();

            pst.setString(1,jtxtposition.getText());
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Deleted Successfully");

        } catch (SQLException | HeadlessException ex) {
            JOptionPane.showMessageDialog(null, ex);
        } 
    }//GEN-LAST:event_DeleteActionPerformed

    private void AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddActionPerformed
        // TODO add your handling code here:
        String sql ="insert into Positions"
        + "(PositionID, PositionName)"
        +"VALUES (?,?)";
       
        try{
            PreparedStatement pst  = con.prepareStatement(sql);
            DefaultTableModel model = (DefaultTableModel) tblposition.getModel();

            pst.setString(1,jtxtposition.getText());
            pst.setString(2,jtxtname.getText());
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Inserted Successfully");
        } catch (SQLException | HeadlessException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }  
    }//GEN-LAST:event_AddActionPerformed

    private void jtxtpositionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtpositionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtpositionActionPerformed

    private void jtxtnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtnameActionPerformed

    private void tblpositionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblpositionMouseClicked
        // TODO add your handling code here:
       DefaultTableModel model = (DefaultTableModel) tblposition.getModel();
        
        String tblPositionID = model.getValueAt(tblposition.getSelectedRow(),0).toString();
        String tblPositionName= model.getValueAt(tblposition.getSelectedRow(),1).toString();
                      
       jtxtposition.setText(tblPositionID);
       jtxtname.setText(tblPositionName);
    }//GEN-LAST:event_tblpositionMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add;
    private javax.swing.JButton Delete;
    private javax.swing.JButton Update;
    private javax.swing.JButton ViewPosition;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jtxtname;
    private javax.swing.JTextField jtxtposition;
    private javax.swing.JTable tblposition;
    // End of variables declaration//GEN-END:variables
}
