/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CarDealerSystem;

import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author Angela
 */
public class AdminCollaborative extends javax.swing.JInternalFrame {

    /**
     * Creates new form AdminCollaborate
     */
    public AdminCollaborative() {
        initComponents();
        
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0)); //no space
        BasicInternalFrameUI bui = (BasicInternalFrameUI) this.getUI();
        bui.setNorthPane(null);
        
        jButton1.setBorder(BorderFactory.createEmptyBorder(4, 4, 4, 4));
        jButton1.setContentAreaFilled(false); 
        
        jButton2.setBorder(BorderFactory.createEmptyBorder(4, 4, 4, 4));
        jButton2.setContentAreaFilled(false); 
        
        jButton3.setBorder(BorderFactory.createEmptyBorder(4, 4, 4, 4));
        jButton3.setContentAreaFilled(false); 
        
        jButton4.setBorder(BorderFactory.createEmptyBorder(4, 4, 4, 4));
        jButton4.setContentAreaFilled(false); 
        
        jButton5.setBorder(BorderFactory.createEmptyBorder(4, 4, 4, 4));
        jButton5.setContentAreaFilled(false); 
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panelborder = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        AdminCollaborativedesktop = new javax.swing.JPanel();
        car = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(1050, 768));
        setMinimumSize(new java.awt.Dimension(1050, 768));
        setPreferredSize(new java.awt.Dimension(1050, 768));

        jPanel1.setLayout(null);

        panelborder.setBackground(new java.awt.Color(204, 0, 0));
        panelborder.setMinimumSize(new java.awt.Dimension(1050, 100));
        panelborder.setPreferredSize(new java.awt.Dimension(1050, 100));
        panelborder.setLayout(null);

        jButton1.setBackground(new java.awt.Color(204, 0, 0));
        jButton1.setFont(new java.awt.Font("Felix Titling", 1, 20)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Suppliers");
        jButton1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(148, 1, 1), 2, true));
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton1MousePressed(evt);
            }
        });
        panelborder.add(jButton1);
        jButton1.setBounds(0, 39, 173, 41);

        jButton2.setBackground(new java.awt.Color(204, 0, 0));
        jButton2.setFont(new java.awt.Font("Felix Titling", 1, 20)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Customers");
        jButton2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(148, 1, 1), 2, true));
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton2MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton2MousePressed(evt);
            }
        });
        panelborder.add(jButton2);
        jButton2.setBounds(200, 40, 186, 41);

        jButton3.setBackground(new java.awt.Color(204, 0, 0));
        jButton3.setFont(new java.awt.Font("Felix Titling", 1, 20)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Positions");
        jButton3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(148, 1, 1), 2, true));
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton3MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton3MousePressed(evt);
            }
        });
        panelborder.add(jButton3);
        jButton3.setBounds(410, 40, 193, 41);

        jButton4.setBackground(new java.awt.Color(204, 0, 0));
        jButton4.setFont(new java.awt.Font("Felix Titling", 1, 18)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("TimeSheet");
        jButton4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(148, 1, 1), 2, true));
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton4MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton4MousePressed(evt);
            }
        });
        panelborder.add(jButton4);
        jButton4.setBounds(630, 40, 193, 41);

        jButton5.setBackground(new java.awt.Color(204, 0, 0));
        jButton5.setFont(new java.awt.Font("Felix Titling", 1, 18)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("employee Lists");
        jButton5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(148, 1, 1), 2, true));
        jButton5.setMaximumSize(new java.awt.Dimension(147, 23));
        jButton5.setMinimumSize(new java.awt.Dimension(147, 23));
        jButton5.setPreferredSize(new java.awt.Dimension(147, 23));
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton5MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton5MousePressed(evt);
            }
        });
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        panelborder.add(jButton5);
        jButton5.setBounds(840, 40, 193, 41);

        jPanel1.add(panelborder);
        panelborder.setBounds(0, 0, 1080, 100);

        AdminCollaborativedesktop.setBackground(new java.awt.Color(204, 0, 0));
        AdminCollaborativedesktop.setMinimumSize(new java.awt.Dimension(811, 465));
        AdminCollaborativedesktop.setPreferredSize(new java.awt.Dimension(811, 465));

        javax.swing.GroupLayout AdminCollaborativedesktopLayout = new javax.swing.GroupLayout(AdminCollaborativedesktop);
        AdminCollaborativedesktop.setLayout(AdminCollaborativedesktopLayout);
        AdminCollaborativedesktopLayout.setHorizontalGroup(
            AdminCollaborativedesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1002, Short.MAX_VALUE)
        );
        AdminCollaborativedesktopLayout.setVerticalGroup(
            AdminCollaborativedesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );

        jPanel1.add(AdminCollaborativedesktop);
        AdminCollaborativedesktop.setBounds(20, 150, 1002, 500);

        car.setIcon(new javax.swing.ImageIcon("C:\\Users\\Angela\\OneDrive\\Desktop\\Pictures For OOP_DB\\Pictures and Icons\\car1099.png")); // NOI18N
        jPanel1.add(car);
        car.setBounds(-20, 0, 1099, 800);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CarDealerSystem/car1099.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(770, 120, 1137, 799);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1080, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 770, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MousePressed
        // TODO add your handling code here:
        jButton2.setContentAreaFilled(false);
        jButton3.setContentAreaFilled(false);
        jButton4.setContentAreaFilled(false);
        jButton5.setContentAreaFilled(false);
        
        jButton1.setContentAreaFilled(true);
        jButton1.setBackground(new Color(148, 1, 1));
        jButton1.setOpaque(true);
        
        AdminSupplier emp = new AdminSupplier();
        AdminCollaborativedesktop.removeAll();
        AdminCollaborativedesktop.add(emp).setVisible(true);
    }//GEN-LAST:event_jButton1MousePressed

    private void jButton1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseExited
        // TODO add your handling code here:
        jButton1.setContentAreaFilled(true);
    }//GEN-LAST:event_jButton1MouseExited

    private void jButton2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MousePressed
        // TODO add your handling code here:
        jButton1.setContentAreaFilled(false);
        jButton3.setContentAreaFilled(false);
        jButton4.setContentAreaFilled(false);
        jButton5.setContentAreaFilled(false);
        
        jButton2.setContentAreaFilled(true);
        jButton2.setBackground(new Color(148, 1, 1));
        jButton2.setOpaque(true);
        
        AdminCustomers emp = new AdminCustomers();
        AdminCollaborativedesktop.removeAll();
        AdminCollaborativedesktop.add(emp).setVisible(true);
    }//GEN-LAST:event_jButton2MousePressed

    private void jButton2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseExited
        // TODO add your handling code here:
        jButton2.setContentAreaFilled(true);
    }//GEN-LAST:event_jButton2MouseExited

    private void jButton3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MousePressed
        // TODO add your handling code here:
        jButton1.setContentAreaFilled(false);
        jButton2.setContentAreaFilled(false);
        jButton4.setContentAreaFilled(false);
        jButton5.setContentAreaFilled(false);
        
        jButton3.setContentAreaFilled(true);
        jButton3.setBackground(new Color(148, 1, 1));
        jButton3.setOpaque(true);
        
        AdminPosition emp = new AdminPosition();
        AdminCollaborativedesktop.removeAll();
        AdminCollaborativedesktop.add(emp).setVisible(true);
    }//GEN-LAST:event_jButton3MousePressed

    private void jButton3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseExited
        // TODO add your handling code here:
        jButton3.setContentAreaFilled(true);
    }//GEN-LAST:event_jButton3MouseExited

    private void jButton4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MousePressed
        // TODO add your handling code here:
        jButton1.setContentAreaFilled(false);
        jButton2.setContentAreaFilled(false);
        jButton3.setContentAreaFilled(false);
        jButton5.setContentAreaFilled(false);
        
        jButton4.setContentAreaFilled(true);
        jButton4.setBackground(new Color(148, 1, 1));
        jButton4.setOpaque(true);
        
        AdmMngrtimesheet emp = new AdmMngrtimesheet();
        AdminCollaborativedesktop.removeAll();
        AdminCollaborativedesktop.add(emp).setVisible(true);
    }//GEN-LAST:event_jButton4MousePressed

    private void jButton4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseExited
        // TODO add your handling code here:
        jButton4.setContentAreaFilled(true);
    }//GEN-LAST:event_jButton4MouseExited

    private void jButton5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MousePressed
        // TODO add your handling code here:
        jButton1.setContentAreaFilled(false);
        jButton2.setContentAreaFilled(false);
        jButton3.setContentAreaFilled(false);
        jButton4.setContentAreaFilled(false);
        
        jButton5.setContentAreaFilled(true);
        jButton5.setBackground(new Color(148, 1, 1));
        jButton5.setOpaque(true);
        
        
        //SALARY
        AdmEmpList emp = new AdmEmpList();
        AdminCollaborativedesktop.removeAll();
        AdminCollaborativedesktop.add(emp).setVisible(true);
    }//GEN-LAST:event_jButton5MousePressed

    private void jButton5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseExited
        // TODO add your handling code here:
        jButton5.setContentAreaFilled(true);
    }//GEN-LAST:event_jButton5MouseExited

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AdminCollaborativedesktop;
    private javax.swing.JLabel car;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel panelborder;
    // End of variables declaration//GEN-END:variables
}
