/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CarDealerSystem;

import java.awt.Color;
import java.awt.Font;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Angela
 */
public class AdmMngrBonuses extends javax.swing.JInternalFrame {
    Connection con;
    /**
     * Creates new form AdmMngrBonuses
     */
    public AdmMngrBonuses() {
        initComponents();
        
        String url = "jdbc:mysql://localhost:3306/car_dealers";
        String user = "root";
        String pass = "";
        try{
            con= DriverManager.getConnection(url,user,pass);
        }catch(Exception ex){
            System.out.println("Error:" + ex.getMessage());
        }
        
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0)); //no space
        BasicInternalFrameUI bui = (BasicInternalFrameUI) this.getUI();
        bui.setNorthPane(null);
        
        
        tblbonus.getTableHeader().setFont(new Font ("Segoe UI", Font.PLAIN,14));
        tblbonus.getTableHeader().setOpaque(false);
        tblbonus.getTableHeader().setForeground(new Color(204,0,0));
        tblbonus.setRowHeight(25);
        
        tblbonus1.getTableHeader().setFont(new Font ("Segoe UI", Font.PLAIN,14));
        tblbonus1.getTableHeader().setOpaque(false);
        tblbonus1.getTableHeader().setForeground(new Color(204,0,0));
        tblbonus1.setRowHeight(25);
        
        jScrollPane2.getVerticalScrollBar().setUnitIncrement(16);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel15 = new javax.swing.JPanel();
        jScrollPane11 = new javax.swing.JScrollPane();
        tblbonus = new javax.swing.JTable();
        ViewManager = new javax.swing.JButton();
        CheckTotalManager = new javax.swing.JButton();
        jtxtamountmanager = new javax.swing.JTextField();
        AddManager = new javax.swing.JButton();
        DeleteManager = new javax.swing.JButton();
        UpdateManager = new javax.swing.JButton();
        jtxtbonus = new javax.swing.JTextField();
        jtxtmanager = new javax.swing.JTextField();
        jtxttitle = new javax.swing.JTextField();
        jtxtdate = new javax.swing.JTextField();
        jtxtamount = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jtxtsearch = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblbonus1 = new javax.swing.JTable();
        ViewEmloyee = new javax.swing.JButton();
        CheckTotalEmployee = new javax.swing.JButton();
        jtxtemployeeamount = new javax.swing.JTextField();
        AddEmployee = new javax.swing.JButton();
        DeleteEmployee = new javax.swing.JButton();
        UpdateEmployee = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jtxtbonus1 = new javax.swing.JTextField();
        jtxtemployee = new javax.swing.JTextField();
        jtxttitle1 = new javax.swing.JTextField();
        jtxtdate1 = new javax.swing.JTextField();
        jtxtamount1 = new javax.swing.JTextField();
        jtxtsearchbar = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(1002, 500));
        setMinimumSize(new java.awt.Dimension(1002, 500));
        setPreferredSize(new java.awt.Dimension(1002, 500));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setBorder(null);
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setPreferredSize(new java.awt.Dimension(1002, 500));

        jPanel15.setBackground(new java.awt.Color(204, 0, 0));
        jPanel15.setPreferredSize(new java.awt.Dimension(1067, 1200));
        jPanel15.setLayout(null);

        tblbonus.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "BonusID", "ManagerID", "BonusTitle", "Date", "Amount"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblbonus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblbonusMouseClicked(evt);
            }
        });
        jScrollPane11.setViewportView(tblbonus);
        if (tblbonus.getColumnModel().getColumnCount() > 0) {
            tblbonus.getColumnModel().getColumn(0).setResizable(false);
            tblbonus.getColumnModel().getColumn(1).setResizable(false);
            tblbonus.getColumnModel().getColumn(2).setResizable(false);
            tblbonus.getColumnModel().getColumn(3).setResizable(false);
            tblbonus.getColumnModel().getColumn(4).setResizable(false);
        }

        jPanel15.add(jScrollPane11);
        jScrollPane11.setBounds(10, 290, 940, 220);

        ViewManager.setText("View Mangers Bonuses");
        ViewManager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel15.add(ViewManager);
        ViewManager.setBounds(10, 250, 160, 30);

        CheckTotalManager.setText("Check total");
        CheckTotalManager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel15.add(CheckTotalManager);
        CheckTotalManager.setBounds(680, 520, 100, 30);
        jPanel15.add(jtxtamountmanager);
        jtxtamountmanager.setBounds(790, 520, 160, 30);

        AddManager.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        AddManager.setText("Add");
        AddManager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddManagerActionPerformed1(evt);
            }
        });
        jPanel15.add(AddManager);
        AddManager.setBounds(240, 250, 80, 30);

        DeleteManager.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        DeleteManager.setText("Delete");
        DeleteManager.setPreferredSize(new java.awt.Dimension(55, 23));
        DeleteManager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteManagerActionPerformed1(evt);
            }
        });
        jPanel15.add(DeleteManager);
        DeleteManager.setBounds(400, 250, 80, 30);

        UpdateManager.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        UpdateManager.setText("Update");
        UpdateManager.setPreferredSize(new java.awt.Dimension(55, 23));
        UpdateManager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateManagerActionPerformed(evt);
            }
        });
        jPanel15.add(UpdateManager);
        UpdateManager.setBounds(320, 250, 80, 30);

        jtxtbonus.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel15.add(jtxtbonus);
        jtxtbonus.setBounds(130, 100, 120, 30);

        jtxtmanager.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel15.add(jtxtmanager);
        jtxtmanager.setBounds(400, 100, 140, 30);

        jtxttitle.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtxttitle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxttitleActionPerformed(evt);
            }
        });
        jPanel15.add(jtxttitle);
        jtxttitle.setBounds(130, 140, 120, 30);

        jtxtdate.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel15.add(jtxtdate);
        jtxtdate.setBounds(400, 140, 140, 30);

        jtxtamount.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel15.add(jtxtamount);
        jtxtamount.setBounds(660, 100, 130, 30);

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("BonusID");
        jPanel15.add(jLabel12);
        jLabel12.setBounds(20, 100, 100, 30);

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("ManagerID");
        jPanel15.add(jLabel8);
        jLabel8.setBounds(280, 100, 110, 30);

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Bonus Title");
        jPanel15.add(jLabel9);
        jLabel9.setBounds(20, 140, 120, 30);

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Date");
        jPanel15.add(jLabel10);
        jLabel10.setBounds(280, 140, 70, 30);

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Amount");
        jPanel15.add(jLabel11);
        jLabel11.setBounds(570, 100, 70, 30);

        jtxtsearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtxtsearchKeyReleased(evt);
            }
        });
        jPanel15.add(jtxtsearch);
        jtxtsearch.setBounds(830, 250, 120, 30);

        jLabel1.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("EMPLOYEE");
        jPanel15.add(jLabel1);
        jLabel1.setBounds(20, 630, 170, 40);

        jLabel2.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("MANAGER");
        jPanel15.add(jLabel2);
        jLabel2.setBounds(20, 30, 140, 40);

        tblbonus1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "BonusID", "EmployeeID", "Bonus Title", "Date", "Amount"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblbonus1.setFocusable(false);
        tblbonus1.setIntercellSpacing(new java.awt.Dimension(0, 0));
        tblbonus1.setRowHeight(25);
        tblbonus1.getTableHeader().setReorderingAllowed(false);
        tblbonus1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblbonus1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblbonus1);
        if (tblbonus1.getColumnModel().getColumnCount() > 0) {
            tblbonus1.getColumnModel().getColumn(0).setResizable(false);
            tblbonus1.getColumnModel().getColumn(1).setResizable(false);
            tblbonus1.getColumnModel().getColumn(2).setResizable(false);
            tblbonus1.getColumnModel().getColumn(3).setResizable(false);
            tblbonus1.getColumnModel().getColumn(4).setResizable(false);
        }

        jPanel15.add(jScrollPane2);
        jScrollPane2.setBounds(10, 870, 940, 210);

        ViewEmloyee.setText("View Employee Bonuses");
        ViewEmloyee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewEmloyeeActionPerformed(evt);
            }
        });
        jPanel15.add(ViewEmloyee);
        ViewEmloyee.setBounds(10, 830, 180, 30);

        CheckTotalEmployee.setText("Check Total");
        CheckTotalEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckTotalEmployeeActionPerformed(evt);
            }
        });
        jPanel15.add(CheckTotalEmployee);
        CheckTotalEmployee.setBounds(650, 1090, 130, 30);
        jPanel15.add(jtxtemployeeamount);
        jtxtemployeeamount.setBounds(790, 1090, 160, 30);

        AddEmployee.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        AddEmployee.setText("Add");
        AddEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddEmployeeActionPerformed(evt);
            }
        });
        jPanel15.add(AddEmployee);
        AddEmployee.setBounds(250, 830, 80, 30);

        DeleteEmployee.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        DeleteEmployee.setText("Delete");
        DeleteEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteEmployeeActionPerformed(evt);
            }
        });
        jPanel15.add(DeleteEmployee);
        DeleteEmployee.setBounds(410, 830, 80, 30);

        UpdateEmployee.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        UpdateEmployee.setText("Update");
        UpdateEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateEmployeeActionPerformed(evt);
            }
        });
        jPanel15.add(UpdateEmployee);
        UpdateEmployee.setBounds(330, 830, 80, 30);

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("EmployeeID");
        jPanel15.add(jLabel13);
        jLabel13.setBounds(310, 700, 160, 30);

        jLabel14.setBackground(new java.awt.Color(255, 255, 255));
        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Bonus Title");
        jPanel15.add(jLabel14);
        jLabel14.setBounds(20, 740, 120, 30);

        jLabel15.setBackground(new java.awt.Color(255, 255, 255));
        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Date");
        jPanel15.add(jLabel15);
        jLabel15.setBounds(310, 740, 70, 30);

        jLabel16.setBackground(new java.awt.Color(255, 255, 255));
        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Amount");
        jPanel15.add(jLabel16);
        jLabel16.setBounds(600, 700, 140, 30);

        jLabel17.setBackground(new java.awt.Color(255, 255, 255));
        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("BonusID");
        jPanel15.add(jLabel17);
        jLabel17.setBounds(20, 700, 140, 30);
        jPanel15.add(jtxtbonus1);
        jtxtbonus1.setBounds(130, 700, 140, 30);
        jPanel15.add(jtxtemployee);
        jtxtemployee.setBounds(430, 700, 140, 30);
        jPanel15.add(jtxttitle1);
        jtxttitle1.setBounds(130, 740, 140, 30);
        jPanel15.add(jtxtdate1);
        jtxtdate1.setBounds(430, 740, 140, 30);

        jtxtamount1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtamount1ActionPerformed(evt);
            }
        });
        jPanel15.add(jtxtamount1);
        jtxtamount1.setBounds(680, 700, 130, 30);

        jtxtsearchbar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtsearchbarActionPerformed(evt);
            }
        });
        jtxtsearchbar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtxtsearchbarKeyReleased(evt);
            }
        });
        jPanel15.add(jtxtsearchbar);
        jtxtsearchbar.setBounds(830, 830, 120, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Search");
        jPanel15.add(jLabel3);
        jLabel3.setBounds(770, 830, 60, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Search");
        jPanel15.add(jLabel4);
        jLabel4.setBounds(770, 250, 60, 30);

        jScrollPane1.setViewportView(jPanel15);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1002, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
         try {
    String searchText = jtxtsearch.getText();
    String sqlTotalAmount = "SELECT SUM(Amount) AS TotalAmount FROM ManagerBonuses WHERE " + 
            "BonusID LIKE ? OR ManagerID LIKE ? OR Bonus_Title LIKE ? OR Date LIKE ? OR Amount LIKE ?";

    PreparedStatement totalAmountStatement = con.prepareStatement(sqlTotalAmount);

    for (int i = 1; i <= 5; i++) {
        totalAmountStatement.setString(i, "%" + searchText + "%");
    }

    ResultSet resultSet = totalAmountStatement.executeQuery();

    if (resultSet.next()) {
        double totalAmount = resultSet.getDouble("TotalAmount");

        String formattedTotalAmount = String.format("%.2f", totalAmount);
        jtxtamountmanager.setText(formattedTotalAmount);
    } else {
        jtxtamountmanager.setText("0.00"); 
    }

    resultSet.close();
    totalAmountStatement.close();
} catch (SQLException ex) {
    JOptionPane.showMessageDialog(null, ex);
}
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        String sql = "select * from ManagerBonuses";
        try{
            PreparedStatement pst = con.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();
            DefaultTableModel model = (DefaultTableModel) tblbonus.getModel();
            model.setRowCount(0);
            while(rs.next()){
                model.addRow(new String[]{rs.getString(1), rs.getString(2), rs.getString(3),rs.getString(4), rs.getString(5)});
            }
        }catch(Exception ex){
            System.out.println("Error : " +ex.getMessage());
        }       
    }//GEN-LAST:event_jButton4ActionPerformed

    private void AddManagerActionPerformed1(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddManagerActionPerformed1
        // TODO add your handling code here:
        String sql = "INSERT INTO ManagerBonuses (BonusID, ManagerID, Bonus_Title, Date, Amount) VALUES (?,?,?,?,?)";
        try {
            PreparedStatement pst = con.prepareStatement(sql);
            DefaultTableModel model = (DefaultTableModel) tblbonus.getModel();
            pst.setString(1, jtxtbonus.getText());
            pst.setString(2, jtxtmanager.getText());
            pst.setString(3, jtxttitle.getText());
            pst.setString(4, jtxtdate.getText());
            pst.setString(5, jtxtamount.getText());
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Inserted Successfully");
        } catch (SQLException | HeadlessException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_AddManagerActionPerformed1

    private void DeleteManagerActionPerformed1(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteManagerActionPerformed1
        // TODO add your handling code here:
        String sql ="DELETE FROM ManagerBonuses WHERE BonusID =?";
        try{

            PreparedStatement pst  = con.prepareStatement(sql);

            DefaultTableModel model = (DefaultTableModel) tblbonus.getModel();

            pst.setString(1,jtxtbonus.getText());
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Deleted Successfully");

        } catch (SQLException | HeadlessException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_DeleteManagerActionPerformed1

    private void UpdateManagerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateManagerActionPerformed
        // TODO add your handling code here:
        String sql = "UPDATE ManagerBonuses SET  ManagerID=?, Bonus_Title=?, Date=?, Amount=? WHERE BonusID=?";
        try{

            PreparedStatement pst  = con.prepareStatement(sql);

            DefaultTableModel model = (DefaultTableModel) tblbonus.getModel();

            pst.setString(5,jtxtbonus.getText());
            pst.setString(1,jtxtmanager.getText());
            pst.setString(2,jtxttitle.getText());
            pst.setString(3,jtxtdate.getText());
            pst.setString(4,jtxtamount.getText());
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Updated Successfully");

        } catch (SQLException | HeadlessException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_UpdateManagerActionPerformed

    private void jtxttitleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxttitleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxttitleActionPerformed

    private void tblbonusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblbonusMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) tblbonus.getModel();
        
        String tblBonusID = model.getValueAt(tblbonus.getSelectedRow(),0).toString();
        String tblManagerID = model.getValueAt(tblbonus.getSelectedRow(),1).toString();
        String tblBonusTitle  = model.getValueAt(tblbonus.getSelectedRow(),2).toString();
        String tblDate = model.getValueAt(tblbonus.getSelectedRow(),3).toString();
        String tblAmount= model.getValueAt(tblbonus.getSelectedRow(),4).toString();
                
       jtxtbonus.setText(tblBonusID);
       jtxtmanager.setText(tblManagerID);
       jtxttitle.setText(tblBonusTitle);
       jtxtdate.setText(tblDate);
       jtxtamount.setText(tblAmount);
      
    }//GEN-LAST:event_tblbonusMouseClicked

    private void jtxtsearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtsearchKeyReleased
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) tblbonus.getModel();
        TableRowSorter<DefaultTableModel> obj=new TableRowSorter<>(model);
        tblbonus.setRowSorter(obj);
        obj.setRowFilter(RowFilter.regexFilter(jtxtsearch.getText()));
        
    }//GEN-LAST:event_jtxtsearchKeyReleased

    private void tblbonus1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblbonus1MouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) tblbonus1.getModel();

        String tblBonusID = model.getValueAt(tblbonus1.getSelectedRow(),0).toString();
        String tblEmployeeID = model.getValueAt(tblbonus1.getSelectedRow(),1).toString();
        String tblBonusTitle  = model.getValueAt(tblbonus1.getSelectedRow(),2).toString();
        String tblDate = model.getValueAt(tblbonus1.getSelectedRow(),3).toString();
        String tblAmount= model.getValueAt(tblbonus1.getSelectedRow(),4).toString();

        jtxtbonus1.setText(tblBonusID);
        jtxtemployee.setText(tblEmployeeID);
        jtxttitle1.setText(tblBonusTitle);
        jtxtdate1.setText(tblDate);
        jtxtamount1.setText(tblAmount);
    }//GEN-LAST:event_tblbonus1MouseClicked

    private void ViewEmloyeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewEmloyeeActionPerformed
        // TODO add your handling code here:
        String sql = "select * from EmployeeBonuses";
        try{
            PreparedStatement pst = con.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();
            DefaultTableModel model = (DefaultTableModel) tblbonus1.getModel();
            model.setRowCount(0);
            while(rs.next()){
                model.addRow(new String[]{rs.getString(1), rs.getString(2), rs.getString(3),rs.getString(4), rs.getString(5)});
            }
        }catch(Exception ex){
            System.out.println("Error : " +ex.getMessage());
        }
    }//GEN-LAST:event_ViewEmloyeeActionPerformed

    private void CheckTotalEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckTotalEmployeeActionPerformed
        // TODO add your handling code here:
        try {
            String searchText = jtxtsearchbar.getText();
            String sqlTotalAmount = "SELECT SUM(Amount) AS TotalAmount FROM EmployeeBonuses WHERE " +
            "BonusID LIKE ? OR EmployeeID LIKE ? OR Bonus_Title LIKE ? OR Date LIKE ? OR Amount LIKE ?";

            PreparedStatement totalAmountStatement = con.prepareStatement(sqlTotalAmount);

            for (int i = 1; i <= 5; i++) {
                totalAmountStatement.setString(i, "%" + searchText + "%");
            }

            ResultSet resultSet = totalAmountStatement.executeQuery();

            if (resultSet.next()) {
                double totalAmount = resultSet.getDouble("TotalAmount");

                String formattedTotalAmount = String.format("%.2f", totalAmount);
                jtxtemployeeamount.setText(formattedTotalAmount);
            } else {
                jtxtemployeeamount.setText("0.00");
            }

            resultSet.close();
            totalAmountStatement.close();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_CheckTotalEmployeeActionPerformed

    private void AddEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddEmployeeActionPerformed
        // TODO add your handling code here:
        String sql = "INSERT INTO EmployeeBonuses (BonusID, EmployeeID, Bonus_Title, Date, Amount)  VALUES (?,?,?,?,?)";
        try {
            PreparedStatement pst = con.prepareStatement(sql);
            DefaultTableModel model = (DefaultTableModel) tblbonus1.getModel();
            pst.setString(1, jtxtbonus1.getText());
            pst.setString(2, jtxtemployee.getText());
            pst.setString(3, jtxttitle1.getText());
            pst.setString(4, jtxtdate1.getText());
            pst.setString(5, jtxtamount1.getText());
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Inserted Successfully");
        } catch (SQLException | HeadlessException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_AddEmployeeActionPerformed

    private void DeleteEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteEmployeeActionPerformed
        // TODO add your handling code here:
        String sql ="DELETE FROM EmployeeBonuses WHERE BonusID =?";
        try{

            PreparedStatement pst  = con.prepareStatement(sql);

            DefaultTableModel model = (DefaultTableModel) tblbonus1.getModel();

            pst.setString(1,jtxtbonus1.getText());
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Deleted Successfully");

        } catch (SQLException | HeadlessException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_DeleteEmployeeActionPerformed

    private void UpdateEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateEmployeeActionPerformed
        // TODO add your handling code here:
        String sql = "UPDATE EmployeeBonuses SET  EmployeeID=?, Bonus_Title=?, Date=?, Amount=? WHERE BonusID=?";
        try{

            PreparedStatement pst  = con.prepareStatement(sql);

            DefaultTableModel model = (DefaultTableModel) tblbonus1.getModel();

            pst.setString(5,jtxtbonus1.getText());
            pst.setString(1,jtxtemployee.getText());
            pst.setString(2,jtxttitle1.getText());
            pst.setString(3,jtxtdate1.getText());
            pst.setString(4,jtxtamount1.getText());
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Updated Successfully");

        } catch (SQLException | HeadlessException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_UpdateEmployeeActionPerformed

    private void jtxtamount1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtamount1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtamount1ActionPerformed

    private void jtxtsearchbarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtsearchbarActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) tblbonus1.getModel();
        TableRowSorter<DefaultTableModel> obj=new TableRowSorter<>(model);
        tblbonus1.setRowSorter(obj);
        obj.setRowFilter(RowFilter.regexFilter(jtxtsearchbar.getText()));
    }//GEN-LAST:event_jtxtsearchbarActionPerformed

    private void jtxtsearchbarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtsearchbarKeyReleased
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) tblbonus1.getModel();
        TableRowSorter<DefaultTableModel> obj=new TableRowSorter<>(model);
        tblbonus1.setRowSorter(obj);
        obj.setRowFilter(RowFilter.regexFilter(jtxtsearchbar.getText()));
    }//GEN-LAST:event_jtxtsearchbarKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddEmployee;
    private javax.swing.JButton AddManager;
    private javax.swing.JButton CheckTotalEmployee;
    private javax.swing.JButton CheckTotalManager;
    private javax.swing.JButton DeleteEmployee;
    private javax.swing.JButton DeleteManager;
    private javax.swing.JButton UpdateEmployee;
    private javax.swing.JButton UpdateManager;
    private javax.swing.JButton ViewEmloyee;
    private javax.swing.JButton ViewManager;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jtxtamount;
    private javax.swing.JTextField jtxtamount1;
    private javax.swing.JTextField jtxtamountmanager;
    private javax.swing.JTextField jtxtbonus;
    private javax.swing.JTextField jtxtbonus1;
    private javax.swing.JTextField jtxtdate;
    private javax.swing.JTextField jtxtdate1;
    private javax.swing.JTextField jtxtemployee;
    private javax.swing.JTextField jtxtemployeeamount;
    private javax.swing.JTextField jtxtmanager;
    private javax.swing.JTextField jtxtsearch;
    private javax.swing.JTextField jtxtsearchbar;
    private javax.swing.JTextField jtxttitle;
    private javax.swing.JTextField jtxttitle1;
    private javax.swing.JTable tblbonus;
    private javax.swing.JTable tblbonus1;
    // End of variables declaration//GEN-END:variables
}
