/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CarDealerSystem;

import java.awt.Color;
import java.awt.Font;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Angela
 */
public class AdmMngrSalary extends javax.swing.JInternalFrame {
    Connection con;
    /**
     * Creates new form AdmMangrSalary
     */
    public AdmMngrSalary() {
        initComponents();
        
        String url = "jdbc:mysql://localhost:3306/car_dealers";
        String user = "root";
        String pass = "";
        try{
            con= DriverManager.getConnection(url,user,pass);
        }catch(Exception ex){
            System.out.println("Error:" + ex.getMessage());
        }
        
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0)); //no space
        BasicInternalFrameUI bui = (BasicInternalFrameUI) this.getUI();
        bui.setNorthPane(null);
        
        tblmanager.getTableHeader().setFont(new Font ("Segoe UI", Font.PLAIN,14));
        tblmanager.getTableHeader().setOpaque(false);
        tblmanager.getTableHeader().setForeground(new Color(204,0,0));
        tblmanager.setRowHeight(25);
        
        tblemployee.getTableHeader().setFont(new Font ("Segoe UI", Font.PLAIN,14));
        tblemployee.getTableHeader().setOpaque(false);
        tblemployee.getTableHeader().setForeground(new Color(204,0,0));
        tblemployee.setRowHeight(25);
        
        jScrollPane1.getVerticalScrollBar().setUnitIncrement(16);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jtxtsearch = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jtxtemployee = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jtxtdate = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jtxtsalary = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jtxtpayrollID = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jtxtname = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jtxtamount = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblemployee = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblmanager = new javax.swing.JTable();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jtxtamount1 = new javax.swing.JTextField();
        jButton12 = new javax.swing.JButton();
        jtxtsearch1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jtxtmanager = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jtxtdate1 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jtxtsalary1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jtxtpayrollID1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jtxtname1 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(1002, 500));
        setMinimumSize(new java.awt.Dimension(1002, 500));
        setPreferredSize(new java.awt.Dimension(1002, 500));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane3.setBorder(null);
        jScrollPane3.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane3.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPane3.setPreferredSize(new java.awt.Dimension(1002, 500));

        jPanel1.setBackground(new java.awt.Color(204, 0, 0));
        jPanel1.setPreferredSize(new java.awt.Dimension(1067, 1200));
        jPanel1.setLayout(null);

        jButton1.setText("View Manager Salary");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(10, 263, 150, 30);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setText("Add");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(260, 850, 80, 30);

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton3.setText("Delete");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(430, 850, 90, 30);

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton4.setText("Update ");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(340, 850, 90, 30);

        jtxtsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtsearchActionPerformed(evt);
            }
        });
        jtxtsearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtxtsearchKeyReleased(evt);
            }
        });
        jPanel1.add(jtxtsearch);
        jtxtsearch.setBounds(830, 850, 120, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("EmployeeID");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(20, 750, 130, 30);

        jtxtemployee.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtxtemployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtemployeeActionPerformed(evt);
            }
        });
        jPanel1.add(jtxtemployee);
        jtxtemployee.setBounds(140, 750, 130, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Date");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(300, 750, 70, 30);

        jtxtdate.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtxtdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtdateActionPerformed(evt);
            }
        });
        jPanel1.add(jtxtdate);
        jtxtdate.setBounds(370, 750, 150, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Amount");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(550, 700, 80, 30);

        jtxtsalary.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtxtsalary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtsalaryActionPerformed(evt);
            }
        });
        jPanel1.add(jtxtsalary);
        jtxtsalary.setBounds(630, 700, 130, 30);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("PayrollID ");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(20, 700, 90, 30);

        jtxtpayrollID.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtxtpayrollID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtpayrollIDActionPerformed(evt);
            }
        });
        jPanel1.add(jtxtpayrollID);
        jtxtpayrollID.setBounds(140, 700, 130, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Name");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(300, 700, 60, 30);

        jtxtname.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtxtname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtnameActionPerformed(evt);
            }
        });
        jPanel1.add(jtxtname);
        jtxtname.setBounds(370, 700, 150, 30);

        jButton6.setText("Check Amount");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6);
        jButton6.setBounds(680, 1060, 110, 30);

        jtxtamount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtamountActionPerformed(evt);
            }
        });
        jPanel1.add(jtxtamount);
        jtxtamount.setBounds(800, 1060, 150, 30);

        tblemployee.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Payroll ID", "Employee ID", "Name ", "Date ", "Amount"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblemployee.setFocusable(false);
        tblemployee.setIntercellSpacing(new java.awt.Dimension(0, 0));
        tblemployee.setRowHeight(25);
        tblemployee.getTableHeader().setReorderingAllowed(false);
        tblemployee.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblemployeeMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblemployee);
        if (tblemployee.getColumnModel().getColumnCount() > 0) {
            tblemployee.getColumnModel().getColumn(0).setResizable(false);
            tblemployee.getColumnModel().getColumn(1).setResizable(false);
            tblemployee.getColumnModel().getColumn(2).setResizable(false);
            tblemployee.getColumnModel().getColumn(3).setResizable(false);
            tblemployee.getColumnModel().getColumn(4).setResizable(false);
        }

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(10, 890, 940, 160);

        tblmanager.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Payroll ID", "Manager ID", "Name ", "Date ", "Amount"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblmanager.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblmanagerMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblmanager);
        if (tblmanager.getColumnModel().getColumnCount() > 0) {
            tblmanager.getColumnModel().getColumn(0).setResizable(false);
            tblmanager.getColumnModel().getColumn(1).setResizable(false);
            tblmanager.getColumnModel().getColumn(2).setResizable(false);
            tblmanager.getColumnModel().getColumn(3).setResizable(false);
            tblmanager.getColumnModel().getColumn(4).setResizable(false);
        }

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(10, 300, 940, 160);

        jButton7.setText("View Employee Salary");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7);
        jButton7.setBounds(10, 853, 170, 30);

        jButton8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton8.setText("Add");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton8);
        jButton8.setBounds(260, 260, 80, 30);

        jButton9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton9.setText("Delete");
        jButton9.setPreferredSize(new java.awt.Dimension(55, 23));
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton9);
        jButton9.setBounds(430, 260, 90, 30);

        jButton11.setText("Check Amount");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton11);
        jButton11.setBounds(680, 470, 110, 30);

        jtxtamount1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtamount1ActionPerformed(evt);
            }
        });
        jPanel1.add(jtxtamount1);
        jtxtamount1.setBounds(800, 470, 150, 30);

        jButton12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton12.setText("Update ");
        jButton12.setPreferredSize(new java.awt.Dimension(55, 23));
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton12);
        jButton12.setBounds(340, 260, 90, 30);

        jtxtsearch1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtsearch1ActionPerformed(evt);
            }
        });
        jtxtsearch1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtxtsearch1KeyReleased(evt);
            }
        });
        jPanel1.add(jtxtsearch1);
        jtxtsearch1.setBounds(830, 260, 120, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("ManagerID");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(20, 150, 120, 30);

        jtxtmanager.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtxtmanager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtmanagerActionPerformed(evt);
            }
        });
        jPanel1.add(jtxtmanager);
        jtxtmanager.setBounds(140, 150, 130, 30);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Date");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(300, 150, 100, 30);

        jtxtdate1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel1.add(jtxtdate1);
        jtxtdate1.setBounds(370, 150, 150, 30);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Search");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(760, 850, 70, 30);

        jtxtsalary1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtsalary1ActionPerformed(evt);
            }
        });
        jPanel1.add(jtxtsalary1);
        jtxtsalary1.setBounds(630, 110, 130, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("PayrollID ");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(20, 110, 100, 30);

        jtxtpayrollID1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtxtpayrollID1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtpayrollID1ActionPerformed(evt);
            }
        });
        jPanel1.add(jtxtpayrollID1);
        jtxtpayrollID1.setBounds(140, 110, 130, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Name");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(300, 110, 80, 30);

        jtxtname1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtxtname1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtname1ActionPerformed(evt);
            }
        });
        jPanel1.add(jtxtname1);
        jtxtname1.setBounds(370, 110, 150, 30);

        jLabel11.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 36)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("MANAGER");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(20, 30, 140, 40);

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Amount");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(550, 110, 80, 30);

        jLabel13.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 36)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("EMPLOYEE");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(20, 630, 170, 40);

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Search");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(760, 260, 80, 30);

        jScrollPane3.setViewportView(jPanel1);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String sql = "select * from ManagerSalary ";
        try{
            PreparedStatement pst = con.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();
            DefaultTableModel model = (DefaultTableModel) tblmanager.getModel();
            model.setRowCount(0);
            while(rs.next()){
                model.addRow(new String[]{rs.getString(1), rs.getString(2), rs.getString(3),rs.getString(4),rs.getString(5)});
            }
        }catch(Exception ex){
            System.out.println("Error : " +ex.getMessage());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String sql ="insert into EmployeeSalary"
        + "(PayrollID,EmployeeID,Name, Date, Amount)"
        +"VALUES (?,?,?,?,?)";
        try{

            PreparedStatement pst  = con.prepareStatement(sql);

            DefaultTableModel model = (DefaultTableModel) tblmanager.getModel();

            pst.setString(1,jtxtpayrollID.getText());
            pst.setString(2,jtxtemployee.getText());
            pst.setString(3,jtxtname.getText());
            pst.setString(4,jtxtdate .getText());
            pst.setString(5,jtxtsalary.getText());
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Inserted Successfully");

        } catch (SQLException | HeadlessException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        String sql = "UPDATE EmployeeSalary SET  EmployeeID=?, Name=?, Date=?,Amount = ? WHERE PayrollID=?";
        try{

            PreparedStatement pst  = con.prepareStatement(sql);

            DefaultTableModel model = (DefaultTableModel) tblmanager.getModel();

            pst.setString(5,jtxtpayrollID.getText());
            pst.setString(1,jtxtemployee.getText());
            pst.setString(2,jtxtname.getText());
            pst.setString(3,jtxtdate .getText());
            pst.setString(4,jtxtsalary.getText());
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Updated Successfully");

        } catch (SQLException | HeadlessException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jtxtnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtnameActionPerformed

    private void jtxtsalaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtsalaryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtsalaryActionPerformed

    private void jtxtemployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtemployeeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtemployeeActionPerformed

    private void jtxtsearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtsearchKeyReleased
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) tblemployee.getModel();
        TableRowSorter<DefaultTableModel> obj=new TableRowSorter<>(model);
        tblemployee.setRowSorter(obj);
        obj.setRowFilter(RowFilter.regexFilter(jtxtsearch.getText()));
    }//GEN-LAST:event_jtxtsearchKeyReleased

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        try {
    String searchText = jtxtsearch.getText();
    String sqlTotalAmount = "SELECT SUM(Amount) AS TotalAmount FROM EmployeeSalary WHERE " + 
            "PayrollID LIKE ? OR EmployeeID LIKE ? OR Name LIKE ? OR Date LIKE ? OR Amount LIKE ?";

    PreparedStatement totalAmountStatement = con.prepareStatement(sqlTotalAmount);

    for (int i = 1; i <= 5; i++) {
        totalAmountStatement.setString(i, "%" + searchText + "%");
    }

    ResultSet resultSet = totalAmountStatement.executeQuery();

    if (resultSet.next()) {
        double totalAmount = resultSet.getDouble("TotalAmount");

        String formattedTotalAmount = String.format("%.2f", totalAmount);
        jtxtamount.setText(formattedTotalAmount);
    } else {
        jtxtamount.setText("0.00"); 
    }

    resultSet.close();
    totalAmountStatement.close();
} catch (SQLException ex) {
    JOptionPane.showMessageDialog(null, ex);
}
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jtxtamountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtamountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtamountActionPerformed

    private void jtxtsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtsearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtsearchActionPerformed

    private void jtxtpayrollIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtpayrollIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtpayrollIDActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here
        String sql ="insert into ManagerSalary (PayrollID,ManagerID,Name, Date, Amount) VALUES (?,?,?,?,?)";
        try{

            PreparedStatement pst  = con.prepareStatement(sql);

            DefaultTableModel model = (DefaultTableModel) tblmanager.getModel();

            pst.setString(1,jtxtpayrollID1.getText());
            pst.setString(2,jtxtmanager.getText());
            pst.setString(3,jtxtname1.getText());
            pst.setString(4,jtxtdate1 .getText());
            pst.setString(5,jtxtsalary1.getText());
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Inserted Successfully");

        } catch (SQLException | HeadlessException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        String sql ="DELETE FROM ManagerSalary WHERE PayrollID =?";
        try{

            PreparedStatement pst  = con.prepareStatement(sql);

            DefaultTableModel model = (DefaultTableModel) tblmanager.getModel();

            pst.setString(1,jtxtpayrollID1.getText());
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Deleted Successfully");

        } catch (SQLException | HeadlessException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
        try {
    String searchText = jtxtsearch1.getText();
    String sqlTotalAmount = "SELECT SUM(Amount) AS TotalAmount FROM ManagerSalary WHERE " + 
            "PayrollID LIKE ? OR ManagerID LIKE ? OR Name LIKE ? OR Date LIKE ? OR Amount LIKE ?";

    PreparedStatement totalAmountStatement = con.prepareStatement(sqlTotalAmount);

    for (int i = 1; i <= 5; i++) {
        totalAmountStatement.setString(i, "%" + searchText + "%");
    }

    ResultSet resultSet = totalAmountStatement.executeQuery();

    if (resultSet.next()) {
        double totalAmount = resultSet.getDouble("TotalAmount");

        String formattedTotalAmount = String.format("%.2f", totalAmount);
        jtxtamount1.setText(formattedTotalAmount);
    } else {
        jtxtamount1.setText("0.00"); 
    }

    resultSet.close();
    totalAmountStatement.close();
} catch (SQLException ex) {
    JOptionPane.showMessageDialog(null, ex);
}
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jtxtamount1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtamount1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtamount1ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
        String sql = "UPDATE ManagerSalary SET  ManagerID=?, Name=?, Date=?,Amount = ? WHERE PayrollID=?";
        try{

            PreparedStatement pst  = con.prepareStatement(sql);

            DefaultTableModel model = (DefaultTableModel) tblmanager.getModel();

            pst.setString(5,jtxtpayrollID1.getText());
            pst.setString(1,jtxtmanager.getText());
            pst.setString(2,jtxtname1.getText());
            pst.setString(3,jtxtdate1 .getText());
            pst.setString(4,jtxtsalary1.getText());
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Updated Successfully");

        } catch (SQLException | HeadlessException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jtxtsearch1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtsearch1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtsearch1ActionPerformed

    private void jtxtsearch1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtsearch1KeyReleased
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) tblmanager.getModel();
        TableRowSorter<DefaultTableModel> obj=new TableRowSorter<>(model);
        tblmanager.setRowSorter(obj);
        obj.setRowFilter(RowFilter.regexFilter(jtxtsearch1.getText()));
    }//GEN-LAST:event_jtxtsearch1KeyReleased

    private void jtxtmanagerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtmanagerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtmanagerActionPerformed

    private void jtxtsalary1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtsalary1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtsalary1ActionPerformed

    private void jtxtpayrollID1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtpayrollID1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtpayrollID1ActionPerformed

    private void jtxtname1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtname1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtname1ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
         String sql = "select * from EmployeeSalary ";
        try{
            PreparedStatement pst = con.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();
            DefaultTableModel model = (DefaultTableModel) tblemployee.getModel();
            model.setRowCount(0);
            while(rs.next()){
                model.addRow(new String[]{rs.getString(1), rs.getString(2), rs.getString(3),rs.getString(4),rs.getString(5)});
            }
        }catch(Exception ex){
            System.out.println("Error : " +ex.getMessage());
        }
        
    }//GEN-LAST:event_jButton7ActionPerformed

    private void tblmanagerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblmanagerMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) tblmanager.getModel();
        
        String tblPayrollID = model.getValueAt(tblmanager.getSelectedRow(),0).toString();
        String tblManagerID = model.getValueAt(tblmanager.getSelectedRow(),1).toString();
        String tblName  = model.getValueAt(tblmanager.getSelectedRow(),2).toString();
        String tblDate = model.getValueAt(tblmanager.getSelectedRow(),3).toString();
        String tblAmount= model.getValueAt(tblmanager.getSelectedRow(),4).toString();
                
       jtxtpayrollID1.setText(tblPayrollID);
       jtxtmanager.setText(tblManagerID);
       jtxtname1.setText(tblName);
       jtxtdate1.setText(tblDate);
       jtxtsalary1.setText(tblAmount);
    }//GEN-LAST:event_tblmanagerMouseClicked

    private void tblemployeeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblemployeeMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) tblemployee.getModel();
        
        String tblPayrollID = model.getValueAt(tblemployee.getSelectedRow(),0).toString();
        String tblEmployeeID = model.getValueAt(tblemployee.getSelectedRow(),1).toString();
        String tblName  = model.getValueAt(tblemployee.getSelectedRow(),2).toString();
        String tblDate = model.getValueAt(tblemployee.getSelectedRow(),3).toString();
        String tblAmount= model.getValueAt(tblemployee.getSelectedRow(),4).toString();
                
       jtxtpayrollID.setText(tblPayrollID);
       jtxtemployee.setText(tblEmployeeID);
       jtxtname.setText(tblName);
       jtxtdate.setText(tblDate);
       jtxtsalary.setText(tblAmount);
    }//GEN-LAST:event_tblemployeeMouseClicked

    private void jtxtdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtdateActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        String sql ="DELETE FROM EmployeeSalary WHERE PayrollID =?";
        try{

            PreparedStatement pst  = con.prepareStatement(sql);

            DefaultTableModel model = (DefaultTableModel) tblemployee.getModel();

            pst.setString(1,jtxtpayrollID.getText());
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Deleted Successfully");

        } catch (SQLException | HeadlessException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_jButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jtxtamount;
    private javax.swing.JTextField jtxtamount1;
    private javax.swing.JTextField jtxtdate;
    private javax.swing.JTextField jtxtdate1;
    private javax.swing.JTextField jtxtemployee;
    private javax.swing.JTextField jtxtmanager;
    private javax.swing.JTextField jtxtname;
    private javax.swing.JTextField jtxtname1;
    private javax.swing.JTextField jtxtpayrollID;
    private javax.swing.JTextField jtxtpayrollID1;
    private javax.swing.JTextField jtxtsalary;
    private javax.swing.JTextField jtxtsalary1;
    private javax.swing.JTextField jtxtsearch;
    private javax.swing.JTextField jtxtsearch1;
    private javax.swing.JTable tblemployee;
    private javax.swing.JTable tblmanager;
    // End of variables declaration//GEN-END:variables
}
