/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CarDealerSystem;

import java.awt.Color;
import java.awt.Font;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Timestamp;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Angela
 */
public class AdmMngrtimesheet extends javax.swing.JInternalFrame implements Runnable{
    Connection con;
    int hour,second,minute;
    /**
     * Creates new form AdmMngrtimesheet
     */
    public AdmMngrtimesheet() {
        initComponents();
        
        String url = "jdbc:mysql://localhost:3306/car_dealers";
        String user = "root";
        String pass = "";
        try{
            con= DriverManager.getConnection(url,user,pass);
        }catch(Exception ex){
            System.out.println("Error:" + ex.getMessage());
        }
        
        Thread t = new Thread(this);
        t.start();
        
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0)); //no space
        BasicInternalFrameUI bui = (BasicInternalFrameUI) this.getUI();
        bui.setNorthPane(null);
        
        tbltimesheet.getTableHeader().setFont(new Font ("Segoe UI", Font.PLAIN,16));
        tbltimesheet.getTableHeader().setOpaque(false);
        tbltimesheet.getTableHeader().setForeground(new Color(204,0,0));
        tbltimesheet.setRowHeight(25);
        
      jScrollPane2.getVerticalScrollBar().setUnitIncrement(16);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbltimesheet = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jtxtclock = new javax.swing.JLabel();
        jtxttimesheet = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jtxtmanager = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbltimesheet1 = new javax.swing.JTable();
        jButton6 = new javax.swing.JButton();
        deletebutton = new javax.swing.JButton();
        updatebutton = new javax.swing.JButton();
        jtxtemployee = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jtxttimesheet1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(1002, 900));
        setMinimumSize(new java.awt.Dimension(1002, 900));
        setPreferredSize(new java.awt.Dimension(1002, 900));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane2.setBorder(null);
        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPane2.setMinimumSize(new java.awt.Dimension(1002, 500));
        jScrollPane2.setPreferredSize(new java.awt.Dimension(1002, 500));

        jPanel1.setBackground(new java.awt.Color(204, 0, 0));
        jPanel1.setMaximumSize(new java.awt.Dimension(1002, 1080));
        jPanel1.setMinimumSize(new java.awt.Dimension(1002, 1080));
        jPanel1.setPreferredSize(new java.awt.Dimension(1002, 1080));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbltimesheet.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "TimeSheetID", "MangerID", "Date", "ClockInTime", "ClockOutTime", "TotalHoursWorked"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbltimesheet.setFocusable(false);
        tbltimesheet.setIntercellSpacing(new java.awt.Dimension(0, 0));
        tbltimesheet.setRowHeight(25);
        tbltimesheet.getTableHeader().setReorderingAllowed(false);
        tbltimesheet.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbltimesheetMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbltimesheet);
        if (tbltimesheet.getColumnModel().getColumnCount() > 0) {
            tbltimesheet.getColumnModel().getColumn(0).setResizable(false);
            tbltimesheet.getColumnModel().getColumn(1).setResizable(false);
            tbltimesheet.getColumnModel().getColumn(2).setResizable(false);
            tbltimesheet.getColumnModel().getColumn(3).setResizable(false);
            tbltimesheet.getColumnModel().getColumn(4).setResizable(false);
            tbltimesheet.getColumnModel().getColumn(5).setResizable(false);
        }

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 950, 180));

        jButton1.setText("Check TimeSheet");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 190, 30));

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton3.setText("Delete");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 240, 130, 30));

        jtxtclock.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jtxtclock.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jtxtclock, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, 350, 21));

        jtxttimesheet.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel1.add(jtxttimesheet, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 140, 160, 30));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("TimeSheetID ");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 140, 140, 30));

        jtxtmanager.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel1.add(jtxtmanager, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 190, 160, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ManagerID");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 190, 100, 30));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("CLOCK ");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, 38));

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton4.setText("Update ");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 240, 130, 30));

        jButton5.setText("LOGOUT");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 290, 100, -1));

        tbltimesheet1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "TimeSheetID", "EmployeeID", "Date", "ClockInTime", "ClockOutTime", "TotalHoursWorked"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbltimesheet1.setFocusable(false);
        tbltimesheet1.setIntercellSpacing(new java.awt.Dimension(0, 0));
        tbltimesheet1.setRowHeight(25);
        tbltimesheet1.getTableHeader().setReorderingAllowed(false);
        tbltimesheet1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbltimesheet1MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tbltimesheet1);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 810, 950, 200));

        jButton6.setText("Check TimeSheet");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 763, 170, 30));

        deletebutton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        deletebutton.setText("Delete");
        deletebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletebuttonActionPerformed(evt);
            }
        });
        jPanel1.add(deletebutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 740, 130, 30));

        updatebutton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        updatebutton.setText("Update ");
        updatebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatebuttonActionPerformed(evt);
            }
        });
        jPanel1.add(updatebutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 740, 130, 30));

        jtxtemployee.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtxtemployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtemployeeActionPerformed(evt);
            }
        });
        jPanel1.add(jtxtemployee, new org.netbeans.lib.awtextra.AbsoluteConstraints(469, 690, 160, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("EmployeeID");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 690, -1, 30));

        jtxttimesheet1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel1.add(jtxttimesheet1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 640, 160, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("TimeSheetID ");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 640, 150, 30));

        jButton7.setText("LOGOUT");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 780, 90, -1));

        jLabel19.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 36)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("MANAGER");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        jLabel20.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 36)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("EMPLOYEE");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 590, -1, -1));

        jScrollPane2.setViewportView(jPanel1);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String sql = "select * from ManagerTimeSheet";
        try{
            PreparedStatement pst = con.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();
            DefaultTableModel model = (DefaultTableModel) tbltimesheet.getModel();
            model.setRowCount(0);
            while(rs.next()){
                model.addRow(new String[]{rs.getString(1), rs.getString(2), rs.getString(3),rs.getString(4),rs.getString(5),rs.getString(6) });
            }
        }catch(Exception ex){
            System.out.println("Error : " +ex.getMessage());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        String sql ="DELETE FROM ManagerTimeSheet WHERE TimeSheetID =?";
        try{

            PreparedStatement pst  = con.prepareStatement(sql);

            DefaultTableModel model = (DefaultTableModel) tbltimesheet.getModel();

            pst.setString(1,jtxttimesheet.getText());
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Deleted Successfully");

        } catch (SQLException | HeadlessException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        String sql = "UPDATE ManagerTimesheet SET ManagerID = ?,ProductID = ?, Date =?,ClockInTime =?, ClockOutTime =? WHERE TimeSheetID = ?";
        try{

            PreparedStatement pst  = con.prepareStatement(sql);

             DefaultTableModel model = (DefaultTableModel) tbltimesheet.getModel();

            
            pst.setString(1,jtxtmanager.getText());

            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Updated Successfully");

        } catch (SQLException | HeadlessException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void tbltimesheetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbltimesheetMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) tbltimesheet.getModel();
        
        String tblTimeSheetID = model.getValueAt(tbltimesheet.getSelectedRow(),0).toString();
        String tblManagerID = model.getValueAt(tbltimesheet.getSelectedRow(),1).toString();
        String tblDate = model.getValueAt(tbltimesheet.getSelectedRow(),2).toString();
        String tblClockInTime = model.getValueAt(tbltimesheet.getSelectedRow(),3).toString();
        String tblClockOutTime = model.getValueAt(tbltimesheet.getSelectedRow(),4).toString();
        String tblTotalHoursWorked = model.getValueAt(tbltimesheet.getSelectedRow(),5).toString();
        
       jtxttimesheet.setText(tblTimeSheetID);
       jtxtmanager.setText(tblManagerID);
    }//GEN-LAST:event_tbltimesheetMouseClicked

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        String sql = "UPDATE ManagerTimeSheet SET ClockOutTime=? WHERE TimesheetID=?";
try {
    PreparedStatement pst = con.prepareStatement(sql);

    // Get the current time as the ClockoutTime
    Timestamp ClockOutTime = new Timestamp(System.currentTimeMillis());

    // Set the ClockoutTime and TimesheetID
    pst.setTimestamp(1, ClockOutTime);
    pst.setString(2, jtxttimesheet.getText());

    int rowsUpdated = pst.executeUpdate();
    if (rowsUpdated > 0) {
        JOptionPane.showMessageDialog(null, "ClockoutTime updated successfully");
    } else {
        JOptionPane.showMessageDialog(null, "Error updating ClockoutTime");
    }
} catch (SQLException | HeadlessException ex) {
    JOptionPane.showMessageDialog(null, ex);
}
    }//GEN-LAST:event_jButton5ActionPerformed

    private void tbltimesheet1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbltimesheet1MouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) tbltimesheet1.getModel();

        String tblTimeSheetID = model.getValueAt(tbltimesheet1.getSelectedRow(),0).toString();
        String tblManagerID = model.getValueAt(tbltimesheet1.getSelectedRow(),1).toString();
        String tblDate = model.getValueAt(tbltimesheet1.getSelectedRow(),2).toString();
        String tblClockInTime = model.getValueAt(tbltimesheet1.getSelectedRow(),3).toString();
        String tblClockOutTime = model.getValueAt(tbltimesheet1.getSelectedRow(),4).toString();
        String tblTotalHoursWorked = model.getValueAt(tbltimesheet1.getSelectedRow(),5).toString();

        jtxttimesheet1.setText(tblTimeSheetID);
        jtxtemployee.setText(tblManagerID);
    }//GEN-LAST:event_tbltimesheet1MouseClicked

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        String sql = "select * from EmployeeTimeSheet";
        try{
            PreparedStatement pst = con.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();
            DefaultTableModel model = (DefaultTableModel) tbltimesheet1.getModel();
            model.setRowCount(0);
            while(rs.next()){
                model.addRow(new String[]{rs.getString(1), rs.getString(2), rs.getString(3),rs.getString(4),rs.getString(5),rs.getString(6) });
            }
        }catch(Exception ex){
            System.out.println("Error : " +ex.getMessage());
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void deletebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletebuttonActionPerformed
        // TODO add your handling code here:
        String sql ="DELETE FROM EmployeeTimeSheet WHERE TimeSheetID =?";
        try{

            PreparedStatement pst  = con.prepareStatement(sql);

            DefaultTableModel model = (DefaultTableModel) tbltimesheet1.getModel();

            pst.setString(1,jtxttimesheet.getText());
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Deleted Successfully");

        } catch (SQLException | HeadlessException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_deletebuttonActionPerformed

    private void updatebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatebuttonActionPerformed
        // TODO add your handling code here:
        String sql = "UPDATE EmployeeTimeSheet SET  EmployeeID=?, Date=?, ClockInTime=?, ClockoutTime=?, TotalHoursWorked=? WHERE TimesheetID=?";
        try{

            PreparedStatement pst  = con.prepareStatement(sql);

            DefaultTableModel model = (DefaultTableModel) tbltimesheet1.getModel();

            pst.setString(6,jtxttimesheet.getText());
            pst.setString(1,jtxtemployee.getText());
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Updated Successfully");

        } catch (SQLException | HeadlessException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_updatebuttonActionPerformed

    private void jtxtemployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtemployeeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtemployeeActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        String sql = "UPDATE EmployeeTimeSheet SET ClockoutTime=? WHERE TimesheetID=?";
        try {
            PreparedStatement pst = con.prepareStatement(sql);

            // Get the current time as the ClockoutTime
            Timestamp clockoutTime = new Timestamp(System.currentTimeMillis());

            // Set the ClockoutTime and TimesheetID
            pst.setTimestamp(1, clockoutTime);
            pst.setString(2, jtxttimesheet1.getText());

            int rowsUpdated = pst.executeUpdate();
            if (rowsUpdated > 0) {
                JOptionPane.showMessageDialog(null, "ClockoutTime updated successfully");
            } else {
                JOptionPane.showMessageDialog(null, "Error updating ClockoutTime");
            }
        } catch (SQLException | HeadlessException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_jButton7ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton deletebutton;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel jtxtclock;
    private javax.swing.JTextField jtxtemployee;
    private javax.swing.JTextField jtxtmanager;
    private javax.swing.JTextField jtxttimesheet;
    private javax.swing.JTextField jtxttimesheet1;
    private javax.swing.JTable tbltimesheet;
    private javax.swing.JTable tbltimesheet1;
    private javax.swing.JButton updatebutton;
    // End of variables declaration//GEN-END:variables

    
    public void run() {
        while (true) {
    Calendar cal = Calendar.getInstance();
    hour = cal.get(Calendar.HOUR_OF_DAY);
    minute = cal.get(Calendar.MINUTE);
    second = cal.get(Calendar.SECOND);

    SimpleDateFormat sdf24 = new SimpleDateFormat("HH:mm:ss");
    SimpleDateFormat sdfDate = new SimpleDateFormat("yyyy-MM-dd"); 

    Date dat = cal.getTime();
    String time24 = sdf24.format(dat);
    String date = sdfDate.format(dat); 

    String dateTime = date + " " + time24; 

    jtxtclock.setText(dateTime);
}
    }

}
