/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CarDealerSystem;

import java.awt.Color;
import java.awt.Font;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Angela
 */
public class AdmPurchaseProducts extends javax.swing.JInternalFrame {
    Connection con;
    /**
     * Creates new form AdmPurchaseProducts
     */
    public AdmPurchaseProducts() {
        initComponents();
        
        String url = "jdbc:mysql://localhost:3306/car_dealers";
        String user = "root";
        String pass = "";
        try{
            con= DriverManager.getConnection(url,user,pass);
        }catch(Exception ex){
            System.out.println("Error:" + ex.getMessage());
        }
        
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0)); //no space
        BasicInternalFrameUI bui = (BasicInternalFrameUI) this.getUI();
        bui.setNorthPane(null);
        
        tblpurchaseproducts.getTableHeader().setFont(new Font ("Segoe UI", Font.PLAIN,14));
        tblpurchaseproducts.getTableHeader().setOpaque(false);
        tblpurchaseproducts.getTableHeader().setForeground(new Color(204,0,0));
        tblpurchaseproducts.setRowHeight(25);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblpurchaseproducts = new javax.swing.JTable();
        jtxtsearch = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jtxtpurchase = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jtxtquantity = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jtxtprice = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jtxtpurchaseID = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jtxtsupplier = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jtxtproduct = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jtxttotalprice = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(1002, 500));
        setMinimumSize(new java.awt.Dimension(1002, 500));
        setPreferredSize(new java.awt.Dimension(1002, 500));

        jPanel2.setBackground(new java.awt.Color(204, 0, 0));
        jPanel2.setMinimumSize(new java.awt.Dimension(811, 465));
        jPanel2.setLayout(null);

        tblpurchaseproducts.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "PurchaseID", "SupplierID", "ProductID", "PurchaseDate", "PurchaseQuantity", "PurchasePrice"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblpurchaseproducts.setFocusable(false);
        tblpurchaseproducts.setIntercellSpacing(new java.awt.Dimension(0, 0));
        tblpurchaseproducts.setRowHeight(25);
        tblpurchaseproducts.getTableHeader().setReorderingAllowed(false);
        tblpurchaseproducts.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblpurchaseproductsMouseClicked(evt);
            }
        });
        tblpurchaseproducts.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tblpurchaseproductsKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tblpurchaseproducts);
        if (tblpurchaseproducts.getColumnModel().getColumnCount() > 0) {
            tblpurchaseproducts.getColumnModel().getColumn(0).setResizable(false);
            tblpurchaseproducts.getColumnModel().getColumn(1).setResizable(false);
            tblpurchaseproducts.getColumnModel().getColumn(2).setResizable(false);
            tblpurchaseproducts.getColumnModel().getColumn(3).setResizable(false);
            tblpurchaseproducts.getColumnModel().getColumn(4).setResizable(false);
            tblpurchaseproducts.getColumnModel().getColumn(5).setResizable(false);
        }

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(10, 250, 950, 170);

        jtxtsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtsearchActionPerformed(evt);
            }
        });
        jtxtsearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtxtsearchKeyReleased(evt);
            }
        });
        jPanel2.add(jtxtsearch);
        jtxtsearch.setBounds(830, 210, 130, 30);

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton5.setText("Update");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton5);
        jButton5.setBounds(280, 210, 100, 30);

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton4.setText("Delete");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4);
        jButton4.setBounds(380, 210, 100, 30);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setText("Add");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2);
        jButton2.setBounds(200, 210, 80, 30);

        jButton1.setText("Check Expenses");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);
        jButton1.setBounds(10, 210, 130, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("PurchaseDate");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(20, 100, 150, 30);

        jtxtpurchase.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtxtpurchase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtpurchaseActionPerformed(evt);
            }
        });
        jPanel2.add(jtxtpurchase);
        jtxtpurchase.setBounds(150, 100, 130, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Purchase Quantity");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(310, 100, 162, 30);

        jtxtquantity.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel2.add(jtxtquantity);
        jtxtquantity.setBounds(480, 100, 130, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Purchase Price");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(640, 100, 140, 30);

        jtxtprice.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel2.add(jtxtprice);
        jtxtprice.setBounds(780, 100, 150, 30);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("PurchaseID");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(20, 50, 120, 30);

        jtxtpurchaseID.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtxtpurchaseID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtpurchaseIDActionPerformed(evt);
            }
        });
        jPanel2.add(jtxtpurchaseID);
        jtxtpurchaseID.setBounds(150, 50, 130, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("SupplierID");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(310, 50, 93, 30);

        jtxtsupplier.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel2.add(jtxtsupplier);
        jtxtsupplier.setBounds(480, 50, 130, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("ProductID");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(640, 50, 100, 30);

        jtxtproduct.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtxtproduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtproductActionPerformed(evt);
            }
        });
        jPanel2.add(jtxtproduct);
        jtxtproduct.setBounds(780, 50, 147, 30);

        jButton3.setText("Check Total");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3);
        jButton3.setBounds(710, 430, 120, 30);
        jPanel2.add(jtxttotalprice);
        jtxttotalprice.setBounds(840, 430, 120, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Search");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(770, 210, 60, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 986, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 502, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtxtsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtsearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtsearchActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        String sql = "UPDATE PurchaseProducts SET SupplierID=?, ProductID=?, PurchaseDate =?, PurchaseQuantity = ?, PurchasePrice =? WHERE PurchaseID=?";
        try{

            PreparedStatement pst  = con.prepareStatement(sql);

            DefaultTableModel model = (DefaultTableModel) tblpurchaseproducts.getModel();

            pst.setString(6,jtxtpurchaseID.getText());
            pst.setString(1,jtxtsupplier.getText());
            pst.setString(2,jtxtproduct.getText());
            pst.setString(3,jtxtpurchase.getText());
            pst.setString(4,jtxtquantity.getText());
            pst.setString(5,jtxtprice.getText());
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Updated Successfully");

        } catch (SQLException | HeadlessException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        String sql ="DELETE FROM PurchaseProducts WHERE PurchaseID =?";
        try{

            PreparedStatement pst  = con.prepareStatement(sql);

            DefaultTableModel model = (DefaultTableModel) tblpurchaseproducts.getModel();

            pst.setString(1,jtxtpurchaseID.getText());
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Deleted Successfully");

        } catch (SQLException | HeadlessException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String sql ="insert into PurchaseProducts"
        + "(PurchaseID, SupplierID, ProductID, PurchaseDate, PurchaseQuantity, PurchasePrice)"
        +"VALUES (?,?,?,?,?,?)";
        try{

            PreparedStatement pst  = con.prepareStatement(sql);

            DefaultTableModel model = (DefaultTableModel) tblpurchaseproducts.getModel();

            pst.setString(1,jtxtpurchaseID.getText());
            pst.setString(2,jtxtsupplier.getText());
            pst.setString(3,jtxtproduct.getText());
            pst.setString(4,jtxtpurchase.getText());
            pst.setString(5,jtxtquantity.getText());
            pst.setString(6,jtxtprice.getText());
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Inserted Successfully");

        } catch (SQLException | HeadlessException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String sql = "select * from purchaseproducts";
        try{
            PreparedStatement pst = con.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();
            DefaultTableModel model = (DefaultTableModel) tblpurchaseproducts.getModel();
            model.setRowCount(0);

            while(rs.next()){
                model.addRow(new String[]{rs.getString(1), rs.getString(2), rs.getString(3),rs.getString(4), rs.getString(5), rs.getString(6)});
            }
        }catch(Exception ex){
            System.out.println("Error : " +ex.getMessage());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jtxtproductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtproductActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtproductActionPerformed

    private void jtxtpurchaseIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtpurchaseIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtpurchaseIDActionPerformed

    private void tblpurchaseproductsKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblpurchaseproductsKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_tblpurchaseproductsKeyReleased

    private void jtxtpurchaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtpurchaseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtpurchaseActionPerformed

    private void jtxtsearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtsearchKeyReleased
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) tblpurchaseproducts.getModel();
        TableRowSorter<DefaultTableModel> obj=new TableRowSorter<>(model);
        tblpurchaseproducts.setRowSorter(obj);
        obj.setRowFilter(RowFilter.regexFilter(jtxtsearch.getText()));
    }//GEN-LAST:event_jtxtsearchKeyReleased

    private void tblpurchaseproductsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblpurchaseproductsMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) tblpurchaseproducts.getModel();
        
        String tblPurchaseID = model.getValueAt(tblpurchaseproducts.getSelectedRow(),0).toString();
        String tblSupplierID = model.getValueAt(tblpurchaseproducts.getSelectedRow(),1).toString();
        String tblProductID = model.getValueAt(tblpurchaseproducts.getSelectedRow(),2).toString();
        String tblPurchaseDate = model.getValueAt(tblpurchaseproducts.getSelectedRow(),3).toString();
        String tblPurchaseQuantity = model.getValueAt(tblpurchaseproducts.getSelectedRow(),4).toString();
        String tblPurchasePrice = model.getValueAt(tblpurchaseproducts.getSelectedRow(),5).toString();
        
       jtxtpurchaseID.setText(tblPurchaseID);
       jtxtsupplier.setText(tblSupplierID);
       jtxtproduct.setText(tblProductID);
       jtxtpurchase.setText(tblPurchaseDate);
       jtxtquantity.setText(tblPurchaseQuantity);
       jtxtprice.setText(tblPurchasePrice);
       
    }//GEN-LAST:event_tblpurchaseproductsMouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    try {
    String searchText = jtxtsearch.getText();
    String sqlTotalAmount = "SELECT SUM(PurchasePrice) AS TotalPurchasePrice FROM PurchaseProducts WHERE " + 
            "PurchaseID LIKE ? OR SupplierID LIKE ? OR ProductID LIKE ? OR PurchaseDate LIKE ? OR PurchaseQuantity LIKE ? OR PurchasePrice LIKE ?";

    PreparedStatement totalAmountStatement = con.prepareStatement(sqlTotalAmount);

    for (int i = 1; i <= 6; i++) {
        totalAmountStatement.setString(i, "%" + searchText + "%");
    }

    ResultSet resultSet = totalAmountStatement.executeQuery();

    if (resultSet.next()) {
        double totalAmount = resultSet.getDouble("TotalPurchasePrice");

        String formattedTotalAmount = String.format("%.2f", totalAmount);
        jtxttotalprice.setText(formattedTotalAmount);
    } else {
        jtxttotalprice.setText("0.00"); 
    }

    resultSet.close();
    totalAmountStatement.close();
} catch (SQLException ex) {
    JOptionPane.showMessageDialog(null, ex);
}
    }//GEN-LAST:event_jButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jtxtprice;
    private javax.swing.JTextField jtxtproduct;
    private javax.swing.JTextField jtxtpurchase;
    private javax.swing.JTextField jtxtpurchaseID;
    private javax.swing.JTextField jtxtquantity;
    private javax.swing.JTextField jtxtsearch;
    private javax.swing.JTextField jtxtsupplier;
    private javax.swing.JTextField jtxttotalprice;
    private javax.swing.JTable tblpurchaseproducts;
    // End of variables declaration//GEN-END:variables
}
