/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CarDealerSystem;

import java.awt.Color;
import java.awt.Font;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Angela
 */
public class AdmSoldProducts extends javax.swing.JInternalFrame {
    Connection con;
    /**
     * Creates new form AdmSoldProducts
     */
    public AdmSoldProducts() {
        initComponents();
        
        String url = "jdbc:mysql://localhost:3306/car_dealers";
        String user = "root";
        String pass = "";
        try{
            con= DriverManager.getConnection(url,user,pass);
        }catch(Exception ex){
            System.out.println("Error:" + ex.getMessage());
        }
        
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0)); //no space
        BasicInternalFrameUI bui = (BasicInternalFrameUI) this.getUI();
        bui.setNorthPane(null);
        
        tblsold.getTableHeader().setFont(new Font ("Segoe UI", Font.PLAIN,14));
        tblsold.getTableHeader().setOpaque(false);
        tblsold.getTableHeader().setForeground(new Color(204,0,0));
        tblsold.setRowHeight(25);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblsold = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jtxtsaleid = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jtxtproduct = new javax.swing.JTextField();
        jtxtproductname = new javax.swing.JTextField();
        jtxtcustomer = new javax.swing.JTextField();
        jtxtsaledate = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jtxtsalequantity = new javax.swing.JTextField();
        jtxtsaleprice = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton40 = new javax.swing.JButton();
        jtxttotalamount = new javax.swing.JTextField();
        jtxtsearch = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(1002, 500));
        setMinimumSize(new java.awt.Dimension(1002, 500));
        setPreferredSize(new java.awt.Dimension(1002, 500));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane2.setBorder(null);
        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        jPanel1.setBackground(new java.awt.Color(204, 0, 0));
        jPanel1.setPreferredSize(new java.awt.Dimension(1040, 745));
        jPanel1.setLayout(null);

        tblsold.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "SaleID", "ProductID", "ProductName", "CustomerID", "SaleDate", "SaleQuantity", "SalePrice"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblsold.setFocusable(false);
        tblsold.setIntercellSpacing(new java.awt.Dimension(0, 0));
        tblsold.setRowHeight(25);
        tblsold.getTableHeader().setReorderingAllowed(false);
        tblsold.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblsoldMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblsold);
        if (tblsold.getColumnModel().getColumnCount() > 0) {
            tblsold.getColumnModel().getColumn(0).setResizable(false);
            tblsold.getColumnModel().getColumn(1).setResizable(false);
            tblsold.getColumnModel().getColumn(2).setResizable(false);
            tblsold.getColumnModel().getColumn(3).setResizable(false);
            tblsold.getColumnModel().getColumn(4).setResizable(false);
            tblsold.getColumnModel().getColumn(5).setResizable(false);
            tblsold.getColumnModel().getColumn(6).setResizable(false);
        }

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(10, 340, 960, 260);

        jButton2.setText("View Sold Products");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(10, 290, 150, 30);

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton4.setText("Delete");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(380, 290, 80, 30);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ProductID");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(370, 40, 110, 25);

        jtxtsaleid.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel1.add(jtxtsaleid);
        jtxtsaleid.setBounds(180, 40, 150, 30);

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton5.setText("Add");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5);
        jButton5.setBounds(220, 290, 80, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("CustomerID");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(370, 90, 130, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("SaleDate");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(30, 140, 100, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("SalePrice");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(30, 200, 130, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("SaleID");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(30, 40, 70, 25);

        jtxtproduct.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel1.add(jtxtproduct);
        jtxtproduct.setBounds(510, 40, 150, 30);

        jtxtproductname.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel1.add(jtxtproductname);
        jtxtproductname.setBounds(180, 90, 150, 30);

        jtxtcustomer.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtxtcustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtcustomerActionPerformed(evt);
            }
        });
        jPanel1.add(jtxtcustomer);
        jtxtcustomer.setBounds(510, 90, 150, 30);

        jtxtsaledate.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel1.add(jtxtsaledate);
        jtxtsaledate.setBounds(180, 140, 150, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("ProductName");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(30, 90, 160, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("SaleQuantity");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(370, 140, 150, 30);

        jtxtsalequantity.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtxtsalequantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtsalequantityActionPerformed(evt);
            }
        });
        jPanel1.add(jtxtsalequantity);
        jtxtsalequantity.setBounds(510, 140, 150, 30);

        jtxtsaleprice.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel1.add(jtxtsaleprice);
        jtxtsaleprice.setBounds(180, 200, 150, 30);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setText("Update");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(300, 290, 80, 30);

        jButton40.setText("Check total");
        jButton40.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton40jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton40);
        jButton40.setBounds(690, 606, 100, 30);

        jtxttotalamount.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel1.add(jtxttotalamount);
        jtxttotalamount.setBounds(800, 606, 170, 30);

        jtxtsearch.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtxtsearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtxtsearchKeyReleased(evt);
            }
        });
        jPanel1.add(jtxtsearch);
        jtxtsearch.setBounds(840, 300, 130, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Search");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(770, 300, 70, 30);

        jScrollPane2.setViewportView(jPanel1);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1002, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String sql = "select * from soldproducts";
        try{
            PreparedStatement pst = con.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();
            DefaultTableModel model = (DefaultTableModel) tblsold.getModel();
            model.setRowCount(0);
            while(rs.next()){
                model.addRow(new String[]{rs.getString(1), rs.getString(2), rs.getString(3), rs.getString(4), rs.getString(5), rs.getString(6),rs.getString(7)});
            }
        }catch(Exception ex){
            System.out.println("Error : " +ex.getMessage());
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
         String sql ="DELETE FROM SoldProducts WHERE SaleID =?";
        try{

            PreparedStatement pst  = con.prepareStatement(sql);

            DefaultTableModel model = (DefaultTableModel) tblsold.getModel();

            pst.setString(1,jtxtsaleid.getText());
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Deleted Successfully");

        } catch (SQLException | HeadlessException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        String sql ="insert into soldproducts"
        + "(SaleID, ProductID, ProductName, CustomerID, SaleDate, SaleQuantity,SalePrice)"
        +"VALUES (?,?,?,?,?,?,?)";
        try{

            PreparedStatement pst  = con.prepareStatement(sql);

            DefaultTableModel model = (DefaultTableModel) tblsold.getModel();

            pst.setString(1,jtxtsaleid.getText());
            pst.setString(2,jtxtproduct.getText());
            pst.setString(3,jtxtproductname.getText());
            pst.setString(4,jtxtcustomer.getText());
            pst.setString(5,jtxtsaledate.getText());
            pst.setString(6,jtxtsalequantity.getText());
            pst.setString(7,jtxtsaleprice.getText());
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Inserted Successfully");

        } catch (SQLException | HeadlessException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jtxtcustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtcustomerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtcustomerActionPerformed

    private void jtxtsalequantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtsalequantityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtsalequantityActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String sql = "UPDATE Soldproducts SET ProductID=?,ProductName = ?,CustomerID = ?, SaleDate =?,SaleQuantity=?,SalePrice =? WHERE SaleID = ?";
        try{

            PreparedStatement pst  = con.prepareStatement(sql);

             DefaultTableModel model = (DefaultTableModel) tblsold.getModel();

            pst.setString(7,jtxtsaleid.getText());
            pst.setString(1,jtxtproduct.getText());
            pst.setString(2,jtxtproductname.getText());
            pst.setString(3,jtxtcustomer.getText());
            pst.setString(4,jtxtsaledate.getText());
            pst.setString(5,jtxtsalequantity.getText());
            pst.setString(6,jtxtsaleprice.getText());
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Updated Successfully");

        } catch (SQLException | HeadlessException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tblsoldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblsoldMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) tblsold.getModel();
        
        String tblSaleID = model.getValueAt(tblsold.getSelectedRow(),0).toString();
        String tblProductID = model.getValueAt(tblsold.getSelectedRow(),1).toString();
        String tblProductName = model.getValueAt(tblsold.getSelectedRow(),2).toString();
        String tblCustomerID = model.getValueAt(tblsold.getSelectedRow(),3).toString();
        String tblSaleDate = model.getValueAt(tblsold.getSelectedRow(),4).toString();
        String tblSaleQuantity = model.getValueAt(tblsold.getSelectedRow(),5).toString();
        String tblSalePrice = model.getValueAt(tblsold.getSelectedRow(),6).toString();
        
       jtxtsaleid.setText(tblSaleID);
       jtxtproduct.setText(tblProductID);
       jtxtproductname.setText(tblProductName);
       jtxtcustomer.setText(tblCustomerID);
       jtxtsaledate.setText(tblSaleDate);
       jtxtsalequantity.setText(tblSaleQuantity);
       jtxtsaleprice.setText(tblSalePrice);
       
    }//GEN-LAST:event_tblsoldMouseClicked

    private void jButton40jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton40jButton5ActionPerformed
        try {
    String searchText = jtxtsearch.getText();
    String sqlTotalAmount = "SELECT SUM(SalePrice) AS TotalSalePrice FROM SoldProducts WHERE " +
            "SaleID LIKE ? OR ProductID LIKE ? OR ProductName LIKE ? OR CustomerID LIKE ? OR " +
            "SaleDate LIKE ? OR SaleQuantity LIKE ? OR SalePrice LIKE ?";

    PreparedStatement totalAmountStatement = con.prepareStatement(sqlTotalAmount);


    for (int i = 1; i <= 7; i++) {
        totalAmountStatement.setString(i, "%" + searchText + "%");
    }

    ResultSet resultSet = totalAmountStatement.executeQuery();

    if (resultSet.next()) {
        double totalAmount = resultSet.getDouble("TotalSalePrice");

        String formattedTotalAmount = String.format("%.2f", totalAmount);
        jtxttotalamount.setText(formattedTotalAmount);
    } else {
        jtxttotalamount.setText("0.00"); 
    }

    resultSet.close();
    totalAmountStatement.close();
} catch (SQLException ex) {
    JOptionPane.showMessageDialog(null, ex);
}
    }//GEN-LAST:event_jButton40jButton5ActionPerformed

    private void jtxtsearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtsearchKeyReleased
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) tblsold.getModel();
        TableRowSorter<DefaultTableModel> obj=new TableRowSorter<>(model);
        tblsold.setRowSorter(obj);
        obj.setRowFilter(RowFilter.regexFilter(jtxtsearch.getText()));
    }//GEN-LAST:event_jtxtsearchKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton40;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jtxtcustomer;
    private javax.swing.JTextField jtxtproduct;
    private javax.swing.JTextField jtxtproductname;
    private javax.swing.JTextField jtxtsaledate;
    private javax.swing.JTextField jtxtsaleid;
    private javax.swing.JTextField jtxtsaleprice;
    private javax.swing.JTextField jtxtsalequantity;
    private javax.swing.JTextField jtxtsearch;
    private javax.swing.JTextField jtxttotalamount;
    private javax.swing.JTable tblsold;
    // End of variables declaration//GEN-END:variables

   
}
