/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CarDealerSystem;

import java.awt.Color;
import java.awt.Font;
import java.awt.HeadlessException;
import java.awt.font.TextAttribute;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.AttributedString;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Angela
 */
public class EmpCustomers extends javax.swing.JInternalFrame {
   
    Connection con;
    /**
     * Creates new form EmpCustomers
     */
    public EmpCustomers() {
        initComponents();
        
        String url = "jdbc:mysql://localhost:3306/car_dealers";
        String user = "root";
        String pass = "";
        try{
            con= DriverManager.getConnection(url,user,pass);
        }catch(Exception ex){
            System.out.println("Error:" + ex.getMessage());
        }
        
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0)); //no space
        BasicInternalFrameUI bui = (BasicInternalFrameUI) this.getUI();
        bui.setNorthPane(null);
        
        tblcustomer.getTableHeader().setFont(new Font ("Segoe UI", Font.PLAIN,14));
        tblcustomer.getTableHeader().setOpaque(false);
        tblcustomer.getTableHeader().setForeground(new Color(204,0,0));
        tblcustomer.setRowHeight(25);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        AdminCollaborativedesktop = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblcustomer = new javax.swing.JTable();
        ViewCustomerlist = new javax.swing.JButton();
        Add = new javax.swing.JButton();
        Delete = new javax.swing.JButton();
        Update = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jtxtcustomerid = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jtxtname = new javax.swing.JTextField();
        jtxtemployee = new javax.swing.JTextField();
        jtxtproduct = new javax.swing.JTextField();
        jtxtproductname = new javax.swing.JTextField();
        jtxtprice = new javax.swing.JTextField();
        jtxtdate = new javax.swing.JTextField();
        jtxtaddress = new javax.swing.JTextField();
        jtxtcontact = new javax.swing.JTextField();
        jtxtsearch = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        receipt = new javax.swing.JTextArea();
        CheckReciept = new javax.swing.JButton();
        customerid = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        PrintReciept = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(1002, 900));
        setMinimumSize(new java.awt.Dimension(1002, 900));
        setPreferredSize(new java.awt.Dimension(1002, 900));
        getContentPane().setLayout(null);

        jScrollPane2.setBorder(null);
        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPane2.setMinimumSize(new java.awt.Dimension(1002, 500));
        jScrollPane2.setPreferredSize(new java.awt.Dimension(1002, 1200));

        AdminCollaborativedesktop.setBackground(new java.awt.Color(204, 0, 0));
        AdminCollaborativedesktop.setMaximumSize(new java.awt.Dimension(1002, 1000));
        AdminCollaborativedesktop.setMinimumSize(new java.awt.Dimension(1002, 1000));
        AdminCollaborativedesktop.setPreferredSize(new java.awt.Dimension(1002, 1000));
        AdminCollaborativedesktop.setLayout(null);

        jScrollPane1.setBorder(null);

        tblcustomer.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "CustomerID", "CustomerName", "EmployeeID", "ProductID", "ProductName", "Price ", "SoldDate", "CustomerAddress", "CustomerContact"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblcustomer.getTableHeader().setReorderingAllowed(false);
        tblcustomer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblcustomerMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblcustomer);
        if (tblcustomer.getColumnModel().getColumnCount() > 0) {
            tblcustomer.getColumnModel().getColumn(0).setResizable(false);
            tblcustomer.getColumnModel().getColumn(1).setResizable(false);
            tblcustomer.getColumnModel().getColumn(2).setResizable(false);
            tblcustomer.getColumnModel().getColumn(3).setResizable(false);
            tblcustomer.getColumnModel().getColumn(4).setResizable(false);
            tblcustomer.getColumnModel().getColumn(5).setResizable(false);
            tblcustomer.getColumnModel().getColumn(6).setResizable(false);
            tblcustomer.getColumnModel().getColumn(7).setResizable(false);
            tblcustomer.getColumnModel().getColumn(8).setResizable(false);
        }

        AdminCollaborativedesktop.add(jScrollPane1);
        jScrollPane1.setBounds(10, 600, 960, 300);

        ViewCustomerlist.setText("View Customer List");
        ViewCustomerlist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewCustomerlistActionPerformed(evt);
            }
        });
        AdminCollaborativedesktop.add(ViewCustomerlist);
        ViewCustomerlist.setBounds(10, 550, 170, 40);

        Add.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Add.setText("Add");
        Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddActionPerformed(evt);
            }
        });
        AdminCollaborativedesktop.add(Add);
        Add.setBounds(330, 210, 100, 30);

        Delete.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Delete.setText("Delete");
        Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteActionPerformed(evt);
            }
        });
        AdminCollaborativedesktop.add(Delete);
        Delete.setBounds(540, 210, 100, 30);

        Update.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Update.setText("Update ");
        Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateActionPerformed(evt);
            }
        });
        AdminCollaborativedesktop.add(Update);
        Update.setBounds(430, 210, 110, 30);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Name");
        AdminCollaborativedesktop.add(jLabel1);
        jLabel1.setBounds(300, 30, 150, 30);

        jtxtcustomerid.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        AdminCollaborativedesktop.add(jtxtcustomerid);
        jtxtcustomerid.setBounds(140, 30, 140, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ProductID");
        AdminCollaborativedesktop.add(jLabel2);
        jLabel2.setBounds(20, 90, 110, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("SaleDate");
        AdminCollaborativedesktop.add(jLabel3);
        jLabel3.setBounds(20, 150, 110, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("CustomerID");
        AdminCollaborativedesktop.add(jLabel4);
        jLabel4.setBounds(20, 30, 140, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Price");
        AdminCollaborativedesktop.add(jLabel5);
        jLabel5.setBounds(650, 90, 50, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Contact");
        AdminCollaborativedesktop.add(jLabel6);
        jLabel6.setBounds(650, 150, 110, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("EmployeeID");
        AdminCollaborativedesktop.add(jLabel7);
        jLabel7.setBounds(650, 30, 120, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Product");
        AdminCollaborativedesktop.add(jLabel8);
        jLabel8.setBounds(300, 90, 100, 30);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Address");
        AdminCollaborativedesktop.add(jLabel9);
        jLabel9.setBounds(300, 150, 170, 30);

        jtxtname.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        AdminCollaborativedesktop.add(jtxtname);
        jtxtname.setBounds(400, 30, 220, 30);

        jtxtemployee.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        AdminCollaborativedesktop.add(jtxtemployee);
        jtxtemployee.setBounds(780, 30, 180, 30);

        jtxtproduct.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        AdminCollaborativedesktop.add(jtxtproduct);
        jtxtproduct.setBounds(140, 90, 140, 30);

        jtxtproductname.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        AdminCollaborativedesktop.add(jtxtproductname);
        jtxtproductname.setBounds(400, 90, 220, 30);

        jtxtprice.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtxtprice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtpriceActionPerformed(evt);
            }
        });
        AdminCollaborativedesktop.add(jtxtprice);
        jtxtprice.setBounds(780, 90, 180, 30);

        jtxtdate.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtxtdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtdateActionPerformed(evt);
            }
        });
        AdminCollaborativedesktop.add(jtxtdate);
        jtxtdate.setBounds(140, 150, 140, 30);

        jtxtaddress.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtxtaddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtaddressActionPerformed(evt);
            }
        });
        AdminCollaborativedesktop.add(jtxtaddress);
        jtxtaddress.setBounds(400, 150, 220, 30);

        jtxtcontact.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtxtcontact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtcontactActionPerformed(evt);
            }
        });
        AdminCollaborativedesktop.add(jtxtcontact);
        jtxtcontact.setBounds(780, 150, 180, 30);

        jtxtsearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtxtsearchKeyReleased(evt);
            }
        });
        AdminCollaborativedesktop.add(jtxtsearch);
        jtxtsearch.setBounds(820, 560, 150, 30);

        receipt.setEditable(false);
        receipt.setColumns(20);
        receipt.setRows(5);
        jScrollPane3.setViewportView(receipt);

        AdminCollaborativedesktop.add(jScrollPane3);
        jScrollPane3.setBounds(320, 270, 340, 230);

        CheckReciept.setText("Check Receipt");
        CheckReciept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckRecieptActionPerformed(evt);
            }
        });
        AdminCollaborativedesktop.add(CheckReciept);
        CheckReciept.setBounds(550, 510, 110, 30);

        customerid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customeridActionPerformed(evt);
            }
        });
        AdminCollaborativedesktop.add(customerid);
        customerid.setBounds(420, 510, 120, 30);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("CustomerID");
        AdminCollaborativedesktop.add(jLabel10);
        jLabel10.setBounds(320, 500, 100, 40);

        PrintReciept.setText("Print Reciept");
        PrintReciept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrintRecieptActionPerformed(evt);
            }
        });
        AdminCollaborativedesktop.add(PrintReciept);
        PrintReciept.setBounds(320, 550, 340, 30);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Search");
        AdminCollaborativedesktop.add(jLabel11);
        jLabel11.setBounds(760, 560, 60, 30);

        jScrollPane2.setViewportView(AdminCollaborativedesktop);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(0, 0, 1000, 500);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ViewCustomerlistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewCustomerlistActionPerformed
        // TODO add your handling code here:
        String sql = "select * from Customer";
        try{
            PreparedStatement pst = con.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();
            DefaultTableModel model = (DefaultTableModel) tblcustomer.getModel();
            model.setRowCount(0);
            while(rs.next()){
                model.addRow(new String[]{rs.getString(1), rs.getString(2), rs.getString(3), rs.getString(4),rs.getString(5),rs.getString(6), rs.getString(7),rs.getString(8),rs.getString(9)});
            }
        }catch(Exception ex){
            System.out.println("Error : " +ex.getMessage());
        }
    }//GEN-LAST:event_ViewCustomerlistActionPerformed

    private void AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddActionPerformed
        // TODO add your handling code here:
        String sql ="insert into Customer"
        + "(CustomerID,Customername,EmployeeID,ProductID,ProductName,Price,SoldDate,CustomerAddress,CustomerContact)"
        +"VALUES (?,?,?,?,?,?,?,?,?)";
        try{

            PreparedStatement pst  = con.prepareStatement(sql);

            DefaultTableModel model = (DefaultTableModel) tblcustomer.getModel();

            pst.setString(1,jtxtcustomerid.getText());
            pst.setString(2,jtxtname.getText());
            pst.setString(3,jtxtemployee.getText());
            pst.setString(4,jtxtproduct.getText());
            pst.setString(5,jtxtproductname.getText());
            pst.setString(6,jtxtprice.getText());
            pst.setString(7,jtxtdate.getText());
           pst.setString(8,jtxtaddress.getText());
            pst.setString(9,jtxtcontact.getText());
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Inserted Successfully");

        } catch (SQLException | HeadlessException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_AddActionPerformed

    private void DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteActionPerformed
        // TODO add your handling code here:
     String sql = "DELETE FROM Customer WHERE CustomerID =?";
        try{

            PreparedStatement pst  = con.prepareStatement(sql);
            DefaultTableModel model = (DefaultTableModel) tblcustomer.getModel();

            pst.setString(1,jtxtcustomerid.getText());
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Deleted Successfully");

        } catch (SQLException | HeadlessException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }   
        
    }//GEN-LAST:event_DeleteActionPerformed

    private void UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateActionPerformed
        // TODO add your handling code here:
        String sql = "UPDATE Customer SET Customername=?,EmployeeID = ?,ProductID = ?, ProductName =?,Price =?,SoldDate =?, CustomerAddress=?,CustomerContact=? WHERE CustomerID = ?";
        try{

            PreparedStatement pst  = con.prepareStatement(sql);

             DefaultTableModel model = (DefaultTableModel) tblcustomer.getModel();

            pst.setString(9,jtxtcustomerid.getText());
            pst.setString(1,jtxtname.getText());
            pst.setString(2,jtxtemployee.getText());
            pst.setString(3,jtxtproduct.getText());
            pst.setString(4,jtxtproductname.getText());
            pst.setString(5,jtxtprice.getText());
            pst.setString(6,jtxtdate.getText());
           pst.setString(7,jtxtaddress.getText());
            pst.setString(8,jtxtcontact.getText());
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Updated Successfully");

        } catch (SQLException | HeadlessException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_UpdateActionPerformed

    private void jtxtdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtdateActionPerformed

    private void jtxtaddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtaddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtaddressActionPerformed

    private void CheckRecieptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckRecieptActionPerformed
        // TODO add your handling code here:
        String enteredCustomersID = customerid.getText(); // Use the correct name of the text field
        displaySalesDetails(enteredCustomersID);

    }//GEN-LAST:event_CheckRecieptActionPerformed

    private void customeridActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customeridActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_customeridActionPerformed

    private void jtxtpriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtpriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtpriceActionPerformed

    private void jtxtcontactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtcontactActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtcontactActionPerformed

    private void PrintRecieptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrintRecieptActionPerformed
        // TODO add your handling code here:
        try
        {
            receipt.print();
        }
        catch (Exception e)
        {

        }
    }//GEN-LAST:event_PrintRecieptActionPerformed

    private void jtxtsearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtsearchKeyReleased
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) tblcustomer.getModel();
        TableRowSorter<DefaultTableModel> obj=new TableRowSorter<>(model);
        tblcustomer.setRowSorter(obj);
        obj.setRowFilter(RowFilter.regexFilter(jtxtsearch.getText()));
    }//GEN-LAST:event_jtxtsearchKeyReleased

    private void tblcustomerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblcustomerMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) tblcustomer.getModel();
        
        String tblCustomerID = model.getValueAt(tblcustomer.getSelectedRow(),0).toString();
        String tblCustomerName = model.getValueAt(tblcustomer.getSelectedRow(),1).toString();
        String tblEmployeeID  = model.getValueAt(tblcustomer.getSelectedRow(),2).toString();
        String tblProductID= model.getValueAt(tblcustomer.getSelectedRow(),3).toString();
        String tblProductName= model.getValueAt(tblcustomer.getSelectedRow(),4).toString();
        String tblPrice= model.getValueAt(tblcustomer.getSelectedRow(),5).toString();
        String tblSoldDate= model.getValueAt(tblcustomer.getSelectedRow(),6).toString();
        String tblCustomerAddress= model.getValueAt(tblcustomer.getSelectedRow(),7).toString();
        String tblCustomerContact= model.getValueAt(tblcustomer.getSelectedRow(),8).toString();
                
       jtxtcustomerid.setText(tblCustomerID);
       jtxtname.setText(tblCustomerName);
       jtxtemployee.setText(tblEmployeeID);
       jtxtproduct.setText(tblProductID);
       jtxtproductname.setText(tblProductName);
       jtxtprice.setText(tblPrice);
       jtxtdate.setText(tblSoldDate);
       jtxtaddress.setText(tblCustomerAddress);
       jtxtcontact.setText(tblCustomerContact);
       
    }//GEN-LAST:event_tblcustomerMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add;
    private javax.swing.JPanel AdminCollaborativedesktop;
    private javax.swing.JButton CheckReciept;
    private javax.swing.JButton Delete;
    private javax.swing.JButton PrintReciept;
    private javax.swing.JButton Update;
    private javax.swing.JButton ViewCustomerlist;
    private javax.swing.JTextField customerid;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jtxtaddress;
    private javax.swing.JTextField jtxtcontact;
    private javax.swing.JTextField jtxtcustomerid;
    private javax.swing.JTextField jtxtdate;
    private javax.swing.JTextField jtxtemployee;
    private javax.swing.JTextField jtxtname;
    private javax.swing.JTextField jtxtprice;
    private javax.swing.JTextField jtxtproduct;
    private javax.swing.JTextField jtxtproductname;
    private javax.swing.JTextField jtxtsearch;
    private javax.swing.JTextArea receipt;
    private javax.swing.JTable tblcustomer;
    // End of variables declaration//GEN-END:variables

    private void displaySalesDetails(String enteredCustomersID) {
receipt.setText("--------------------------------------------------------------------\n");
receipt.append("                        CUSTOMER DETAILS\n");
receipt.append("--------------------------------------------------------------------\n");

Date currentDate = new Date();
String date = currentDate.toString();
receipt.append("\n" + date + "\n\n");
receipt.append("--------------------------------------------------------------------\n");
receipt.append("Sales ID: " + customerid.getText() + "");

// Retrieve customer information using the entered customer name
// Assuming you have a jtxtcustomername field for user input
try {
    String sql = "SELECT CustomerName, EmployeeID, ProductID, ProductName, Price, SoldDate, CustomerAddress, CustomerContact FROM Customer WHERE CustomerID = ?";
    PreparedStatement pst = con.prepareStatement(sql);
    pst.setString(1, customerid.getText());  // Use the entered customer name
    ResultSet rs = pst.executeQuery();

    receipt.append("\n");

     while (rs.next()) {
        String customername = rs.getString("CustomerName");
        String employeeID = rs.getString("EmployeeID");
        String productID = rs.getString("ProductID");
        String productName = rs.getString("ProductName");
        String price = rs.getString("Price");
        String soldDate = rs.getString("SoldDate"); // Replace "saleDate" with "soldDate"
        String customerAddress = rs.getString("CustomerAddress");
        String customerContact = rs.getString("CustomerContact"); // Replace "customerContacts" with "customer contact"
        
        
        
        receipt.append("Customer Name: " + customername + "\n");
        receipt.append("Employee ID: " + employeeID + "\n");
        receipt.append("Product ID: " + productID + "\n");
        receipt.append("Product Name: " + productName + "\n");
        receipt.append("Price: Php " + price + "\n");
        receipt.append("Sold Date: " + soldDate + "\n"); // Replace "Sale Date" with "Sold Date"
        receipt.append("Customer Address: " + customerAddress + "\n");
        receipt.append("Customer Contact: " + customerContact + "\n"); // Replace "Customer Contacts" with "Customer Contact"
    }
} catch (SQLException ex) {
    JOptionPane.showMessageDialog(null, "Error: " + ex.getMessage());
}

receipt.append("--------------------------------------------------------------------\n");
receipt.append("          THANK YOU FOR YOUR PURCHASE!\n");
    }      
}

