/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CarDealerSystem;

import java.awt.Color;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Angela
 */
public class EmpCollaborative extends javax.swing.JInternalFrame {
 
    Connection con;
    /**
     * Creates new form tryCollaborative
     */
    public EmpCollaborative() {
        initComponents();
        
        String url = "jdbc:mysql://localhost:3306/db_oop_finalproject";
        String user = "root";
        String pass = "";
        try{
            con= DriverManager.getConnection(url,user,pass);
        }catch(Exception ex){
            System.out.println("Error:" + ex.getMessage());
        }
        
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0)); //no space
        BasicInternalFrameUI bui = (BasicInternalFrameUI) this.getUI();
        bui.setNorthPane(null);
        
        Customers.setBorder(BorderFactory.createEmptyBorder(4, 4, 4, 4));
        Customers.setContentAreaFilled(false); 
        
        EmployeeList.setBorder(BorderFactory.createEmptyBorder(4, 4, 4, 4));
        EmployeeList.setContentAreaFilled(false); 
        
        EmployeeTimesheet.setBorder(BorderFactory.createEmptyBorder(4, 4, 4, 4));
        EmployeeTimesheet.setContentAreaFilled(false); 
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Collaborativedesktop = new javax.swing.JPanel();
        panelborder = new javax.swing.JPanel();
        EmployeeTimesheet = new javax.swing.JButton();
        EmployeeList = new javax.swing.JButton();
        Customers = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        car = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1099, 768));

        jPanel1.setLayout(null);

        Collaborativedesktop.setBackground(new java.awt.Color(204, 0, 0));
        Collaborativedesktop.setMinimumSize(new java.awt.Dimension(811, 465));

        javax.swing.GroupLayout CollaborativedesktopLayout = new javax.swing.GroupLayout(Collaborativedesktop);
        Collaborativedesktop.setLayout(CollaborativedesktopLayout);
        CollaborativedesktopLayout.setHorizontalGroup(
            CollaborativedesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1002, Short.MAX_VALUE)
        );
        CollaborativedesktopLayout.setVerticalGroup(
            CollaborativedesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );

        jPanel1.add(Collaborativedesktop);
        Collaborativedesktop.setBounds(20, 150, 1002, 500);

        panelborder.setBackground(new java.awt.Color(204, 0, 0));
        panelborder.setMinimumSize(new java.awt.Dimension(1050, 100));

        EmployeeTimesheet.setBackground(new java.awt.Color(204, 0, 0));
        EmployeeTimesheet.setFont(new java.awt.Font("Felix Titling", 1, 20)); // NOI18N
        EmployeeTimesheet.setForeground(new java.awt.Color(255, 255, 255));
        EmployeeTimesheet.setText("EMPLOYEE TIMESHEET");
        EmployeeTimesheet.setBorder(null);
        EmployeeTimesheet.setPreferredSize(new java.awt.Dimension(117, 23));
        EmployeeTimesheet.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                EmployeeTimesheetMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                EmployeeTimesheetMousePressed(evt);
            }
        });
        EmployeeTimesheet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmployeeTimesheetActionPerformed(evt);
            }
        });

        EmployeeList.setBackground(new java.awt.Color(204, 0, 0));
        EmployeeList.setFont(new java.awt.Font("Felix Titling", 1, 20)); // NOI18N
        EmployeeList.setForeground(new java.awt.Color(255, 255, 255));
        EmployeeList.setText("EMPLOYEE LIST");
        EmployeeList.setBorder(null);
        EmployeeList.setPreferredSize(new java.awt.Dimension(117, 23));
        EmployeeList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                EmployeeListMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                EmployeeListMousePressed(evt);
            }
        });
        EmployeeList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmployeeListActionPerformed(evt);
            }
        });

        Customers.setBackground(new java.awt.Color(204, 0, 0));
        Customers.setFont(new java.awt.Font("Felix Titling", 1, 20)); // NOI18N
        Customers.setForeground(new java.awt.Color(255, 255, 255));
        Customers.setText("CUSTOMER LISTS");
        Customers.setBorder(null);
        Customers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                CustomersMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                CustomersMousePressed(evt);
            }
        });

        javax.swing.GroupLayout panelborderLayout = new javax.swing.GroupLayout(panelborder);
        panelborder.setLayout(panelborderLayout);
        panelborderLayout.setHorizontalGroup(
            panelborderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelborderLayout.createSequentialGroup()
                .addGap(127, 127, 127)
                .addComponent(EmployeeTimesheet, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Customers, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(EmployeeList, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(227, Short.MAX_VALUE))
        );
        panelborderLayout.setVerticalGroup(
            panelborderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelborderLayout.createSequentialGroup()
                .addContainerGap(49, Short.MAX_VALUE)
                .addGroup(panelborderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EmployeeTimesheet, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EmployeeList, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Customers, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel1.add(panelborder);
        panelborder.setBounds(0, 0, 1080, 100);
        jPanel1.add(jLabel10);
        jLabel10.setBounds(0, 0, 1110, 0);

        car.setIcon(new javax.swing.ImageIcon("C:\\Users\\Angela\\OneDrive\\Desktop\\Pictures For OOP_DB\\Pictures and Icons\\car1099.png")); // NOI18N
        jPanel1.add(car);
        car.setBounds(-20, 0, 1099, 800);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EmployeeTimesheetMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EmployeeTimesheetMousePressed
        // TODO add your handling code here:
                // TODO add your handling code here:
        Customers.setContentAreaFilled(false);
        EmployeeList.setContentAreaFilled(false);
        
        EmployeeTimesheet.setContentAreaFilled(true);
        EmployeeTimesheet.setBackground(new Color(148, 1, 1));
        EmployeeTimesheet.setOpaque(true);
        
        EmpTimesheet emp = new EmpTimesheet();
        Collaborativedesktop.removeAll();
        Collaborativedesktop.add(emp).setVisible(true);
    }//GEN-LAST:event_EmployeeTimesheetMousePressed

    private void EmployeeTimesheetMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EmployeeTimesheetMouseExited
        // TODO add your handling code here:
        EmployeeTimesheet.setContentAreaFilled(true);
    }//GEN-LAST:event_EmployeeTimesheetMouseExited

    private void CustomersMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CustomersMousePressed
        // TODO add your handling code here:
        EmployeeTimesheet.setContentAreaFilled(false);
        EmployeeList.setContentAreaFilled(false);
        
        Customers.setContentAreaFilled(true);
        Customers.setBackground(new Color(148, 1, 1));
        Customers.setOpaque(true);
        
        EmpCustomers emp = new EmpCustomers();
        Collaborativedesktop.removeAll();
        Collaborativedesktop.add(emp).setVisible(true); 
    }//GEN-LAST:event_CustomersMousePressed

    private void CustomersMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CustomersMouseExited
        // TODO add your handling code here:
        Customers.setContentAreaFilled(true);
    }//GEN-LAST:event_CustomersMouseExited

    private void EmployeeListMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EmployeeListMousePressed
        // TODO add your handling code here:
        EmployeeTimesheet.setContentAreaFilled(false);
        Customers.setContentAreaFilled(false);
        
        EmployeeList.setContentAreaFilled(true);
        EmployeeList.setBackground(new Color(148, 1, 1));
        EmployeeList.setOpaque(true);
        
        EmpList emp = new EmpList();
        Collaborativedesktop.removeAll();
        Collaborativedesktop.add(emp).setVisible(true);
    }//GEN-LAST:event_EmployeeListMousePressed

    private void EmployeeListMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EmployeeListMouseExited
        // TODO add your handling code here:
        EmployeeList.setContentAreaFilled(true);
    }//GEN-LAST:event_EmployeeListMouseExited

    private void EmployeeListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmployeeListActionPerformed
        // TODO add your handling code here:
       EmpList emp = new EmpList();
       Collaborativedesktop.removeAll();
       Collaborativedesktop.add(emp).setVisible(true); 
    }//GEN-LAST:event_EmployeeListActionPerformed

    private void EmployeeTimesheetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmployeeTimesheetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmployeeTimesheetActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Collaborativedesktop;
    private javax.swing.JButton Customers;
    private javax.swing.JButton EmployeeList;
    private javax.swing.JButton EmployeeTimesheet;
    private javax.swing.JLabel car;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel panelborder;
    // End of variables declaration//GEN-END:variables
}
