/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CarDealerSystem;

import java.awt.Color;
import java.awt.Font;
import javax.swing.BorderFactory;
import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author Angela
 */
public class EmpInventory extends javax.swing.JInternalFrame {

    /**
     * Creates new form EmpInventory
     */
    public EmpInventory() {
        initComponents();
        
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0)); //no space
        BasicInternalFrameUI bui = (BasicInternalFrameUI) this.getUI();
        bui.setNorthPane(null);
        
        Products.setBorder(BorderFactory.createEmptyBorder(4, 4, 4, 4));
        Products.setContentAreaFilled(false); 
        
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        inventorydesktop = new javax.swing.JPanel();
        panelborder = new javax.swing.JPanel();
        Products = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        car = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setPreferredSize(new java.awt.Dimension(1099, 768));
        jPanel1.setLayout(null);

        inventorydesktop.setBackground(new java.awt.Color(204, 0, 0));
        inventorydesktop.setMinimumSize(new java.awt.Dimension(811, 465));

        javax.swing.GroupLayout inventorydesktopLayout = new javax.swing.GroupLayout(inventorydesktop);
        inventorydesktop.setLayout(inventorydesktopLayout);
        inventorydesktopLayout.setHorizontalGroup(
            inventorydesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1002, Short.MAX_VALUE)
        );
        inventorydesktopLayout.setVerticalGroup(
            inventorydesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );

        jPanel1.add(inventorydesktop);
        inventorydesktop.setBounds(20, 150, 1002, 500);

        panelborder.setBackground(new java.awt.Color(204, 0, 0));
        panelborder.setMinimumSize(new java.awt.Dimension(1050, 100));

        Products.setBackground(new java.awt.Color(204, 0, 0));
        Products.setFont(new java.awt.Font("Felix Titling", 1, 20)); // NOI18N
        Products.setForeground(new java.awt.Color(255, 255, 255));
        Products.setText("Products ");
        Products.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ProductsMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ProductsMousePressed(evt);
            }
        });

        javax.swing.GroupLayout panelborderLayout = new javax.swing.GroupLayout(panelborder);
        panelborder.setLayout(panelborderLayout);
        panelborderLayout.setHorizontalGroup(
            panelborderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelborderLayout.createSequentialGroup()
                .addGap(423, 423, 423)
                .addComponent(Products, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(470, Short.MAX_VALUE))
        );
        panelborderLayout.setVerticalGroup(
            panelborderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelborderLayout.createSequentialGroup()
                .addContainerGap(49, Short.MAX_VALUE)
                .addComponent(Products, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel1.add(panelborder);
        panelborder.setBounds(0, 0, 1080, 100);
        jPanel1.add(jLabel10);
        jLabel10.setBounds(0, 0, 0, 0);

        car.setIcon(new javax.swing.ImageIcon("C:\\Users\\Angela\\OneDrive\\Desktop\\Pictures For OOP_DB\\Pictures and Icons\\car1099.png")); // NOI18N
        jPanel1.add(car);
        car.setBounds(-20, 0, 1099, 800);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 31, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ProductsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProductsMousePressed
        // TODO add your handling code here:
        
        Products.setContentAreaFilled(true);
        Products.setBackground(new Color(148, 1, 1));
        Products.setOpaque(true);
        
        EmpProducts emp = new EmpProducts();
        inventorydesktop.removeAll();
        inventorydesktop.add(emp).setVisible(true);
    }//GEN-LAST:event_ProductsMousePressed

    private void ProductsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProductsMouseExited
        // TODO add your handling code here:
        Products.setContentAreaFilled(true);

    }//GEN-LAST:event_ProductsMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Products;
    private javax.swing.JLabel car;
    private javax.swing.JPanel inventorydesktop;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel panelborder;
    // End of variables declaration//GEN-END:variables
}
