/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CarDealerSystem;

import java.awt.Color;
import java.awt.Font;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Angela
 */
public class EmpList extends javax.swing.JInternalFrame {
    Connection con;
    /**
     * Creates new form EmpList
     */
    public EmpList() {
        initComponents();
        
        String url = "jdbc:mysql://localhost:3306/car_dealers";
        String user = "root";
        String pass = "";
        try{
            con= DriverManager.getConnection(url,user,pass);
        }catch(Exception ex){
            System.out.println("Error:" + ex.getMessage());
        }
       
        
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0)); //no space
        BasicInternalFrameUI bui = (BasicInternalFrameUI) this.getUI();
        bui.setNorthPane(null);
        

        tblemployee1.getTableHeader().setFont(new Font ("Segoe UI", Font.PLAIN,14));
        tblemployee1.getTableHeader().setOpaque(false);
        tblemployee1.getTableHeader().setForeground(new Color(204,0,0));
        tblemployee1.setRowHeight(25);
        
        jScrollPane2.getVerticalScrollBar().setUnitIncrement(16);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        ViewEmployee = new javax.swing.JButton();
        jtxtsearchmngr = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblemployee1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblmanager = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jtxtsearchemp = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(1021, 526));
        setMinimumSize(new java.awt.Dimension(1021, 526));
        setPreferredSize(new java.awt.Dimension(1021, 526));

        jScrollPane2.setBorder(null);
        jScrollPane2.setMinimumSize(new java.awt.Dimension(1002, 500));
        jScrollPane2.setPreferredSize(new java.awt.Dimension(1002, 500));

        jPanel1.setBackground(new java.awt.Color(204, 0, 0));
        jPanel1.setMaximumSize(new java.awt.Dimension(811, 465));
        jPanel1.setMinimumSize(new java.awt.Dimension(811, 465));
        jPanel1.setPreferredSize(new java.awt.Dimension(811, 1100));
        jPanel1.setLayout(null);

        ViewEmployee.setBackground(new java.awt.Color(255, 255, 255));
        ViewEmployee.setText("View Employee Lists");
        ViewEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewEmployeeActionPerformed(evt);
            }
        });
        jPanel1.add(ViewEmployee);
        ViewEmployee.setBounds(10, 110, 190, 30);

        jtxtsearchmngr.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtxtsearchmngrKeyReleased(evt);
            }
        });
        jPanel1.add(jtxtsearchmngr);
        jtxtsearchmngr.setBounds(830, 730, 150, 30);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Search");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(760, 730, 70, 30);

        tblemployee1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "EmployeeID", "Name", "PhoneNumber", "Address", "Position ID", "HiredDate", "ManagerID"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblemployee1.setFocusable(false);
        tblemployee1.setIntercellSpacing(new java.awt.Dimension(0, 0));
        tblemployee1.setRowHeight(25);
        tblemployee1.getTableHeader().setReorderingAllowed(false);
        jScrollPane3.setViewportView(tblemployee1);
        if (tblemployee1.getColumnModel().getColumnCount() > 0) {
            tblemployee1.getColumnModel().getColumn(0).setResizable(false);
            tblemployee1.getColumnModel().getColumn(1).setResizable(false);
            tblemployee1.getColumnModel().getColumn(2).setResizable(false);
            tblemployee1.getColumnModel().getColumn(3).setResizable(false);
            tblemployee1.getColumnModel().getColumn(4).setResizable(false);
            tblemployee1.getColumnModel().getColumn(5).setResizable(false);
            tblemployee1.getColumnModel().getColumn(6).setResizable(false);
        }

        jPanel1.add(jScrollPane3);
        jScrollPane3.setBounds(10, 150, 970, 310);

        jButton1.setText("View Manager List ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(10, 730, 180, 30);

        tblmanager.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ManagerID", "Name", "Phone Number", "Address", "PositionID", "HiredDate "
            }
        ));
        tblmanager.setFocusable(false);
        tblmanager.setIntercellSpacing(new java.awt.Dimension(0, 0));
        tblmanager.setRowHeight(25);
        tblmanager.getTableHeader().setReorderingAllowed(false);
        jScrollPane4.setViewportView(tblmanager);

        jPanel1.add(jScrollPane4);
        jScrollPane4.setBounds(10, 770, 970, 240);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Search");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(750, 110, 70, 30);

        jtxtsearchemp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtxtsearchempKeyReleased(evt);
            }
        });
        jPanel1.add(jtxtsearchemp);
        jtxtsearchemp.setBounds(830, 110, 150, 30);

        jLabel3.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("EMPLOYEE");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(20, 30, 190, 40);

        jLabel4.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("MANAGER");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(20, 630, 170, 40);

        jScrollPane2.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 3, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ViewEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewEmployeeActionPerformed
        // TODO add your handling code here:
        String sql = "select * from EmployeeList ";
        try{
            PreparedStatement pst = con.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();
            DefaultTableModel model = (DefaultTableModel) tblemployee1.getModel();
            model.setRowCount(0);
            while(rs.next()){
                model.addRow(new String[]{rs.getString(1), rs.getString(2), rs.getString(3),rs.getString(4),rs.getString(5),rs.getString(6), rs.getString(7)});
            }
        }catch(Exception ex){
            System.out.println("Error : " +ex.getMessage());
        }
    }//GEN-LAST:event_ViewEmployeeActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String sql = "select * from ManagerList ";
        try{
            PreparedStatement pst = con.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();
            DefaultTableModel model = (DefaultTableModel) tblmanager.getModel();
            model.setRowCount(0);
            while(rs.next()){
                model.addRow(new String[]{rs.getString(1), rs.getString(2), rs.getString(3),rs.getString(4),rs.getString(5),rs.getString(6)});
            }
        }catch(Exception ex){
            System.out.println("Error : " +ex.getMessage());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jtxtsearchempKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtsearchempKeyReleased
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) tblemployee1.getModel();
        TableRowSorter<DefaultTableModel> obj=new TableRowSorter<>(model);
        tblemployee1.setRowSorter(obj);
        obj.setRowFilter(RowFilter.regexFilter(jtxtsearchemp.getText()));
    }//GEN-LAST:event_jtxtsearchempKeyReleased

    private void jtxtsearchmngrKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtsearchmngrKeyReleased
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) tblmanager.getModel();
        TableRowSorter<DefaultTableModel> obj=new TableRowSorter<>(model);
        tblmanager.setRowSorter(obj);
        obj.setRowFilter(RowFilter.regexFilter(jtxtsearchmngr.getText()));
    }//GEN-LAST:event_jtxtsearchmngrKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ViewEmployee;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextField jtxtsearchemp;
    private javax.swing.JTextField jtxtsearchmngr;
    private javax.swing.JTable tblemployee1;
    private javax.swing.JTable tblmanager;
    // End of variables declaration//GEN-END:variables
}
