/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CarDealerSystem;

import java.awt.Color;
import java.awt.Font;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Angela
 */
public class EmpProducts extends javax.swing.JInternalFrame {

    Connection con;
    /**
     * Creates new form EmpProducts
     */
    public EmpProducts() {
        initComponents();
        
        String url = "jdbc:mysql://localhost:3306/car_dealers";
        String user = "root";
        String pass = "";
        try{
            con= DriverManager.getConnection(url,user,pass);
        }catch(Exception ex){
            System.out.println("Error:" + ex.getMessage());
        }
        
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0)); //no space
        BasicInternalFrameUI bui = (BasicInternalFrameUI) this.getUI();
        bui.setNorthPane(null);
        
        tblproducts.getTableHeader().setFont(new Font ("Segoe UI", Font.PLAIN,16));
        tblproducts.getTableHeader().setOpaque(false);
        tblproducts.getTableHeader().setForeground(new Color(204,0,0));
        tblproducts.setRowHeight(25);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ViewProducts = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblproducts = new javax.swing.JTable();

        setMaximumSize(new java.awt.Dimension(1002, 900));
        setMinimumSize(new java.awt.Dimension(1002, 900));
        setPreferredSize(new java.awt.Dimension(1002, 900));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(204, 0, 0));
        jPanel1.setMinimumSize(new java.awt.Dimension(1002, 500));
        jPanel1.setPreferredSize(new java.awt.Dimension(1002, 500));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ViewProducts.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        ViewProducts.setText("View Products");
        ViewProducts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewProductsActionPerformed(evt);
            }
        });
        jPanel1.add(ViewProducts, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 177, 30));

        tblproducts.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ProductID", "ProductName", "ProductQuantity", "Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblproducts.setFocusable(false);
        tblproducts.setIntercellSpacing(new java.awt.Dimension(0, 0));
        tblproducts.setRowHeight(25);
        tblproducts.getTableHeader().setReorderingAllowed(false);
        tblproducts.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblproductsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblproducts);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 960, 160));

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1002, 500);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ViewProductsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewProductsActionPerformed
        // TODO add your handling code here:
        String sql = "select * from Products";
        try{
            PreparedStatement pst = con.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();
            DefaultTableModel model = (DefaultTableModel) tblproducts.getModel();
            model.setRowCount(0);
            while(rs.next()){
                model.addRow(new String[]{rs.getString(1), rs.getString(2), rs.getString(3),rs.getString(4)});
            }
        }catch(Exception ex){
            System.out.println("Error : " +ex.getMessage());
        }
    }//GEN-LAST:event_ViewProductsActionPerformed

    private void tblproductsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblproductsMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_tblproductsMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ViewProducts;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblproducts;
    // End of variables declaration//GEN-END:variables
}
