/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CarDealerSystem;

import java.awt.Color;
import java.awt.Font;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Angela
 */
public class EmpStocksProducts extends javax.swing.JInternalFrame {
    
    Connection con;
    /**
     * Creates new form EmpStocksProducts
     */
    public EmpStocksProducts() {
        initComponents();
        
        String url = "jdbc:mysql://localhost:3306/car_dealers";
        String user = "root";
        String pass = "";
        try{
            con= DriverManager.getConnection(url,user,pass);
        }catch(Exception ex){
            System.out.println("Error:" + ex.getMessage());
        }
        
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0)); //no space
        BasicInternalFrameUI bui = (BasicInternalFrameUI) this.getUI();
        bui.setNorthPane(null);
        
        tblstocks.getTableHeader().setFont(new Font ("Segoe UI", Font.PLAIN,16));
        tblstocks.getTableHeader().setOpaque(false);
        tblstocks.getTableHeader().setForeground(new Color(204,0,0));
        tblstocks.setRowHeight(25);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblstocks = new javax.swing.JTable();
        ViewStocks = new javax.swing.JButton();

        setMinimumSize(new java.awt.Dimension(1002, 900));
        setPreferredSize(new java.awt.Dimension(1002, 900));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 0, 0));
        jPanel1.setMinimumSize(new java.awt.Dimension(1002, 500));
        jPanel1.setPreferredSize(new java.awt.Dimension(1002, 500));
        jPanel1.setLayout(null);

        tblstocks.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "StockID", "ProductID", "QuantityInStock", "PurchasePrice"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblstocks.setFocusable(false);
        tblstocks.setIntercellSpacing(new java.awt.Dimension(0, 0));
        tblstocks.setRowHeight(25);
        tblstocks.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tblstocks);
        if (tblstocks.getColumnModel().getColumnCount() > 0) {
            tblstocks.getColumnModel().getColumn(0).setResizable(false);
            tblstocks.getColumnModel().getColumn(1).setResizable(false);
            tblstocks.getColumnModel().getColumn(2).setResizable(false);
            tblstocks.getColumnModel().getColumn(3).setResizable(false);
        }

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(10, 150, 970, 270);

        ViewStocks.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        ViewStocks.setText("View Stocks");
        ViewStocks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewStocksActionPerformed(evt);
            }
        });
        jPanel1.add(ViewStocks);
        ViewStocks.setBounds(10, 100, 170, 30);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ViewStocksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewStocksActionPerformed
        // TODO add your handling code here:
        String sql = "select * from StockProducts";
        try{
            PreparedStatement pst = con.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();
            DefaultTableModel model = (DefaultTableModel) tblstocks.getModel();
            model.setRowCount(0);
            while(rs.next()){
                model.addRow(new String[]{rs.getString(1), rs.getString(2), rs.getString(3),rs.getString(4)});
            }
        }catch(Exception ex){
            System.out.println("Error : " +ex.getMessage());
        }
    }//GEN-LAST:event_ViewStocksActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ViewStocks;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblstocks;
    // End of variables declaration//GEN-END:variables
}
