/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CarDealerSystem;

import java.awt.Color;
import java.awt.Font;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Angela
 */
public class OwnerOtherExpenses extends javax.swing.JInternalFrame {
    
    Connection con;
    /**
     * Creates new form OwnerOtherExpenses
     */
    public OwnerOtherExpenses() {
        initComponents();
        
        String url = "jdbc:mysql://localhost:3306/car_dealers";
        String user = "root";
        String pass = "";
        try{
            con= DriverManager.getConnection(url,user,pass);
        }catch(Exception ex){
            System.out.println("Error:" + ex.getMessage());
        }
        
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0)); //no space
        BasicInternalFrameUI bui = (BasicInternalFrameUI) this.getUI();
        bui.setNorthPane(null);
        
        tblexpenses.getTableHeader().setFont(new Font ("Segoe UI", Font.PLAIN,14));
        tblexpenses.getTableHeader().setOpaque(false);
        tblexpenses.getTableHeader().setForeground(new Color(204,0,0));
        tblexpenses.setRowHeight(25);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jtxtamount = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jtxtexpensename = new javax.swing.JTextField();
        jtxtname = new javax.swing.JTextField();
        jtxtdate = new javax.swing.JTextField();
        jtxtexpense = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblexpenses = new javax.swing.JTable();
        ViewExpenses = new javax.swing.JButton();
        jtxtsearch = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jtxttotalotherexpenses = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(1270, 450));

        jPanel1.setBackground(new java.awt.Color(204, 0, 0));
        jPanel1.setForeground(new java.awt.Color(204, 204, 204));
        jPanel1.setPreferredSize(new java.awt.Dimension(1270, 450));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("OTHER EXPENSES");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(20, 10, 350, 44);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Date");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(70, 120, 80, 30);

        jtxtamount.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel1.add(jtxtamount);
        jtxtamount.setBounds(540, 120, 160, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Name");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(740, 70, 130, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Amount");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(380, 120, 80, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("ExpenseID");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(70, 70, 120, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("EmployeeName");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(380, 70, 170, 30);

        jtxtexpensename.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel1.add(jtxtexpensename);
        jtxtexpensename.setBounds(820, 70, 160, 30);

        jtxtname.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel1.add(jtxtname);
        jtxtname.setBounds(540, 70, 160, 30);

        jtxtdate.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel1.add(jtxtdate);
        jtxtdate.setBounds(190, 120, 160, 30);

        jtxtexpense.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel1.add(jtxtexpense);
        jtxtexpense.setBounds(190, 70, 160, 30);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setText("Delete");
        jButton1.setPreferredSize(new java.awt.Dimension(110, 30));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(560, 190, 110, 30);

        tblexpenses.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ExpenseID", "EmployeeName", "ExpenseName ", "Date ", "Amount"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblexpenses.setFocusable(false);
        tblexpenses.setIntercellSpacing(new java.awt.Dimension(0, 0));
        tblexpenses.setRowHeight(25);
        tblexpenses.getTableHeader().setReorderingAllowed(false);
        tblexpenses.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblexpensesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblexpenses);
        if (tblexpenses.getColumnModel().getColumnCount() > 0) {
            tblexpenses.getColumnModel().getColumn(0).setResizable(false);
            tblexpenses.getColumnModel().getColumn(1).setResizable(false);
            tblexpenses.getColumnModel().getColumn(2).setResizable(false);
            tblexpenses.getColumnModel().getColumn(3).setResizable(false);
            tblexpenses.getColumnModel().getColumn(4).setResizable(false);
        }

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(70, 230, 1090, 150);

        ViewExpenses.setText("View Expenses");
        ViewExpenses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewExpensesActionPerformed(evt);
            }
        });
        jPanel1.add(ViewExpenses);
        ViewExpenses.setBounds(70, 190, 150, 30);

        jtxtsearch.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtxtsearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtxtsearchKeyReleased(evt);
            }
        });
        jPanel1.add(jtxtsearch);
        jtxtsearch.setBounds(1000, 190, 160, 30);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setText("Add");
        jButton2.setPreferredSize(new java.awt.Dimension(110, 30));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(340, 190, 110, 30);

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton4.setText("Update");
        jButton4.setPreferredSize(new java.awt.Dimension(110, 30));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(450, 190, 110, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Search");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(930, 190, 70, 30);
        jPanel1.add(jtxttotalotherexpenses);
        jtxttotalotherexpenses.setBounds(1010, 400, 150, 30);

        jButton3.setText("Check Amount");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(880, 400, 120, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
          String sql ="DELETE FROM OtherExpenses WHERE ExpenseID =?";
        try{

            PreparedStatement pst  = con.prepareStatement(sql);

            DefaultTableModel model = (DefaultTableModel) tblexpenses.getModel();

            pst.setString(1,jtxtexpense.getText());
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Deleted Successfully");

        } catch (SQLException | HeadlessException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
      
    }//GEN-LAST:event_jButton1ActionPerformed

    private void ViewExpensesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewExpensesActionPerformed
        // TODO add your handling code here:
         String sql = "select * from OtherExpenses";
        try{
            PreparedStatement pst = con.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();
            DefaultTableModel model = (DefaultTableModel) tblexpenses.getModel();
            model.setRowCount(0);
        while(rs.next()){
                model.addRow(new String[]{rs.getString(1), rs.getString(2), rs.getString(3),rs.getString(4),rs.getString(5)});
            }
        }catch(Exception ex){
            System.out.println("Error : " +ex.getMessage());
        } 
    }//GEN-LAST:event_ViewExpensesActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         String sql = "insert into otherexpenses"
        + "(ExpenseID, Name, ExpenseName, Date, Amount)"
        + "VALUES (?,?,?,?,?)";
        try{

            PreparedStatement pst  = con.prepareStatement(sql);

            DefaultTableModel model = (DefaultTableModel) tblexpenses.getModel();

            pst.setString(1,jtxtexpense.getText());
            pst.setString(2,jtxtname.getText());
            pst.setString(3,jtxtexpensename.getText());
            pst.setString(4,jtxtdate.getText());
            pst.setString(5,jtxtamount.getText());
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Inserted Successfully");

        } catch (SQLException | HeadlessException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
          String sql = "UPDATE OtherExpenses SET Name=?, ExpenseName =?, Date=?, Amount=? WHERE ExpenseID=?";
        try{

            PreparedStatement pst  = con.prepareStatement(sql);

            DefaultTableModel model = (DefaultTableModel) tblexpenses.getModel();

            pst.setString(5,jtxtexpense.getText());
            pst.setString(1,jtxtname.getText());
            pst.setString(2,jtxtexpensename.getText());
            pst.setString(3,jtxtdate.getText());
            pst.setString(4,jtxtamount.getText());
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Updated Successfully");

        } catch (SQLException | HeadlessException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void tblexpensesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblexpensesMouseClicked
        // TODO add your handling code here:
        
        DefaultTableModel model = (DefaultTableModel) tblexpenses.getModel();
        
        String tblExpenseID = model.getValueAt(tblexpenses.getSelectedRow(),0).toString();
        String tblName = model.getValueAt(tblexpenses.getSelectedRow(),1).toString();
        String tblExpenseName = model.getValueAt (tblexpenses.getSelectedRow(),2).toString();
        String tblDate = model.getValueAt(tblexpenses.getSelectedRow(),3).toString();
        String tblAmount = model.getValueAt(tblexpenses.getSelectedRow(),4).toString();
               
       jtxtexpense.setText(tblExpenseID);
       jtxtname.setText(tblName);
       jtxtexpensename.setText(tblExpenseName);
       jtxtdate.setText(tblDate);
       jtxtamount.setText(tblAmount);
    }//GEN-LAST:event_tblexpensesMouseClicked

    private void jtxtsearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtsearchKeyReleased
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) tblexpenses.getModel();
        TableRowSorter<DefaultTableModel> obj=new TableRowSorter<>(model);
        tblexpenses.setRowSorter(obj);
        obj.setRowFilter(RowFilter.regexFilter(jtxtsearch.getText()));
    }//GEN-LAST:event_jtxtsearchKeyReleased

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        try {
            String searchText = jtxtsearch.getText();
            String sqlTotalAmount = "SELECT SUM(Amount) AS TotalAmount FROM OtherExpenses WHERE " +
            "ExpenseID LIKE ? OR Name LIKE ? OR ExpenseName LIKE ? OR Date LIKE ? OR Amount LIKE ? ";

            PreparedStatement totalAmountStatement = con.prepareStatement(sqlTotalAmount);

            for (int i = 1; i <= 5; i++) {
                totalAmountStatement.setString(i, "%" + searchText + "%");
            }

            ResultSet resultSet = totalAmountStatement.executeQuery();

            if (resultSet.next()) {
                double totalAmount = resultSet.getDouble("TotalAmount");

                String formattedTotalAmount = String.format("%.2f", totalAmount);
                jtxttotalotherexpenses.setText(formattedTotalAmount);
            } else {
                jtxttotalotherexpenses.setText("0.00");
            }

            resultSet.close();
            totalAmountStatement.close();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_jButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ViewExpenses;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jtxtamount;
    private javax.swing.JTextField jtxtdate;
    private javax.swing.JTextField jtxtexpense;
    private javax.swing.JTextField jtxtexpensename;
    private javax.swing.JTextField jtxtname;
    private javax.swing.JTextField jtxtsearch;
    private javax.swing.JTextField jtxttotalotherexpenses;
    private javax.swing.JTable tblexpenses;
    // End of variables declaration//GEN-END:variables
}
