/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CarDealerSystem;

import java.awt.Color;
import java.awt.Font;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Angela
 */
public class OwnerIncome extends javax.swing.JInternalFrame {
    
    Connection con;
    /**
     * Creates new form OwnerIncome
     */
    public OwnerIncome() {
        initComponents();
        
        String url = "jdbc:mysql://localhost:3306/car_dealers";
        String user = "root";
        String pass = "";
        try{
            con= DriverManager.getConnection(url,user,pass);
        }catch(Exception ex){
            System.out.println("Error:" + ex.getMessage());
        }

        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0)); //no space
        BasicInternalFrameUI bui = (BasicInternalFrameUI) this.getUI();
        bui.setNorthPane(null);
        
        tblIncome.getTableHeader().setFont(new Font ("Segoe UI", Font.PLAIN,14));
        tblIncome.getTableHeader().setOpaque(false);
        tblIncome.getTableHeader().setForeground(new Color(204,0,0));
        tblIncome.setRowHeight(25);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblIncome = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jtxtamount = new javax.swing.JTextField();
        jtxtIncome = new javax.swing.JTextField();
        jtxtdate = new javax.swing.JTextField();
        ViewIncome = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jtxtsearch = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jtxtincomeamount = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        setPreferredSize(new java.awt.Dimension(1270, 450));

        jPanel1.setBackground(new java.awt.Color(204, 0, 0));
        jPanel1.setPreferredSize(new java.awt.Dimension(1270, 450));
        jPanel1.setLayout(null);

        tblIncome.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Income ID", "Date", "Amount"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblIncome.setFocusable(false);
        tblIncome.setIntercellSpacing(new java.awt.Dimension(0, 0));
        tblIncome.setRowHeight(25);
        tblIncome.getTableHeader().setReorderingAllowed(false);
        tblIncome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblIncomeMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblIncome);
        if (tblIncome.getColumnModel().getColumnCount() > 0) {
            tblIncome.getColumnModel().getColumn(0).setResizable(false);
            tblIncome.getColumnModel().getColumn(1).setResizable(false);
            tblIncome.getColumnModel().getColumn(2).setResizable(false);
        }

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(70, 230, 1090, 170);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("INCOME");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(20, 10, 250, 44);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("IncomeID");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(70, 90, 140, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Date");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(400, 90, 80, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Amount");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(680, 90, 180, 30);

        jtxtamount.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel1.add(jtxtamount);
        jtxtamount.setBounds(790, 90, 220, 30);

        jtxtIncome.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel1.add(jtxtIncome);
        jtxtIncome.setBounds(190, 90, 180, 30);

        jtxtdate.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel1.add(jtxtdate);
        jtxtdate.setBounds(470, 90, 180, 30);

        ViewIncome.setText("View Income");
        ViewIncome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewIncomeActionPerformed(evt);
            }
        });
        jPanel1.add(ViewIncome);
        ViewIncome.setBounds(70, 190, 150, 30);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setText("Delete");
        jButton1.setPreferredSize(new java.awt.Dimension(110, 30));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(480, 190, 90, 30);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setText("Add");
        jButton2.setPreferredSize(new java.awt.Dimension(110, 30));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(300, 190, 90, 30);

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton3.setText("Update");
        jButton3.setPreferredSize(new java.awt.Dimension(110, 30));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(390, 190, 90, 30);

        jtxtsearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtxtsearchKeyReleased(evt);
            }
        });
        jPanel1.add(jtxtsearch);
        jtxtsearch.setBounds(980, 190, 180, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Search\n");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(920, 192, 60, 30);
        jPanel1.add(jtxtincomeamount);
        jtxtincomeamount.setBounds(1040, 410, 120, 30);

        jButton4.setText("Check Total");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(900, 410, 130, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ViewIncomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewIncomeActionPerformed
        // TODO add your handling code here:
         
        String sql = "select * from Income";
        try{
            PreparedStatement pst = con.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();
            DefaultTableModel model = (DefaultTableModel) tblIncome.getModel();
            model.setRowCount(0);
        while(rs.next()){
                model.addRow(new String[]{rs.getString(1), rs.getString(2), rs.getString(3)});
            }
        }catch(Exception ex){
            System.out.println("Error : " +ex.getMessage());
        } 
        
    }//GEN-LAST:event_ViewIncomeActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
       String sql ="DELETE FROM Income WHERE IncomeID =?";
        try{

            PreparedStatement pst  = con.prepareStatement(sql);

            DefaultTableModel model = (DefaultTableModel) tblIncome.getModel();

            pst.setString(1,jtxtIncome.getText());
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Deleted Successfully");

        } catch (SQLException | HeadlessException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         String sql = "insert into Income"
        + "(IncomeID, Date, Amount)"
        + "VALUES (?,?,?)";
        try{

            PreparedStatement pst  = con.prepareStatement(sql);

            DefaultTableModel model = (DefaultTableModel) tblIncome.getModel();

            pst.setString(1,jtxtIncome.getText());
            pst.setString(2,jtxtdate.getText());
            pst.setString(3,jtxtamount.getText());
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Inserted Successfully");

        } catch (SQLException | HeadlessException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        String sql = "UPDATE Income SET Date=?,Amount=? WHERE IncomeID=?";
        try{

            PreparedStatement pst  = con.prepareStatement(sql);

            DefaultTableModel model = (DefaultTableModel) tblIncome.getModel();

            pst.setString(3, jtxtIncome.getText());
            pst.setString(1,jtxtdate.getText());           
            pst.setString(2,jtxtamount.getText());
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Updated Successfully");

        } catch (SQLException | HeadlessException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void tblIncomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblIncomeMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) tblIncome.getModel();
        
        String tblIncomeID = model.getValueAt(tblIncome.getSelectedRow(),0).toString();
        String tblDate = model.getValueAt(tblIncome.getSelectedRow(),1).toString();
        String tblAmount = model.getValueAt (tblIncome.getSelectedRow(),2).toString();
                      
       jtxtIncome.setText(tblIncomeID);
       jtxtdate.setText(tblDate);
       jtxtamount.setText(tblAmount);
    }//GEN-LAST:event_tblIncomeMouseClicked

    private void jtxtsearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtsearchKeyReleased
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) tblIncome.getModel();
        TableRowSorter<DefaultTableModel> obj=new TableRowSorter<>(model);
        tblIncome.setRowSorter(obj);
        obj.setRowFilter(RowFilter.regexFilter(jtxtsearch.getText()));
    }//GEN-LAST:event_jtxtsearchKeyReleased

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        try {
            String searchText = jtxtsearch.getText();
            String sqlTotalAmount = "SELECT SUM(Amount) AS TotalAmount FROM Income WHERE " +
            "IncomeID LIKE ? OR Date LIKE ? OR Amount LIKE ? ";

            PreparedStatement totalAmountStatement = con.prepareStatement(sqlTotalAmount);

            for (int i = 1; i <= 3; i++) {
                totalAmountStatement.setString(i, "%" + searchText + "%");
            }

            ResultSet resultSet = totalAmountStatement.executeQuery();

            if (resultSet.next()) {
                double totalAmount = resultSet.getDouble("TotalAmount");

                String formattedTotalAmount = String.format("%.2f", totalAmount);
                jtxtincomeamount.setText(formattedTotalAmount);
            } else {
                jtxtincomeamount.setText("0.00");
            }

            resultSet.close();
            totalAmountStatement.close();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_jButton4ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ViewIncome;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jtxtIncome;
    private javax.swing.JTextField jtxtamount;
    private javax.swing.JTextField jtxtdate;
    private javax.swing.JTextField jtxtincomeamount;
    private javax.swing.JTextField jtxtsearch;
    private javax.swing.JTable tblIncome;
    // End of variables declaration//GEN-END:variables
}
