/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CarDealerSystem;

import java.awt.Color;
import java.awt.Font;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Angela
 */
public class OwnerExpense extends javax.swing.JInternalFrame {
    
    Connection con;
    /**
     * Creates new form OwnerExpense
     */
    public OwnerExpense() {
        initComponents();
        
        
        String url = "jdbc:mysql://localhost:3306/car_dealers";
        String user = "root";
        String pass = "";
        try{
            con= DriverManager.getConnection(url,user,pass);
        }catch(Exception ex){
            System.out.println("Error:" + ex.getMessage());
        }
       
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0)); //no space
        BasicInternalFrameUI bui = (BasicInternalFrameUI) this.getUI();
        bui.setNorthPane(null);
        
        tblexpenses.getTableHeader().setFont(new Font ("Segoe UI", Font.PLAIN,14));
        tblexpenses.getTableHeader().setOpaque(false);
        tblexpenses.getTableHeader().setForeground(new Color(204,0,0));
        tblexpenses.setRowHeight(25);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jtxtamount = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jtxtexpensename = new javax.swing.JTextField();
        jtxtname = new javax.swing.JTextField();
        jtxtdate = new javax.swing.JTextField();
        jtxtexpense = new javax.swing.JTextField();
        Delete = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblexpenses = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        Add = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        Update = new javax.swing.JButton();
        jtxtsearch = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jtxttotalownerexpenses = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(1270, 450));

        jPanel2.setBackground(new java.awt.Color(204, 0, 0));
        jPanel2.setForeground(new java.awt.Color(204, 204, 204));
        jPanel2.setPreferredSize(new java.awt.Dimension(1270, 450));
        jPanel2.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("EXPENSES");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(20, 10, 250, 44);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Date");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(460, 70, 80, 30);

        jtxtamount.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel2.add(jtxtamount);
        jtxtamount.setBounds(550, 120, 160, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Name of Expenses");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(70, 120, 200, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Amount");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(460, 120, 80, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("ExpenseID");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(70, 70, 140, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("OwnerName");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(740, 70, 140, 30);

        jtxtexpensename.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel2.add(jtxtexpensename);
        jtxtexpensename.setBounds(270, 120, 160, 30);

        jtxtname.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel2.add(jtxtname);
        jtxtname.setBounds(880, 70, 160, 30);

        jtxtdate.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel2.add(jtxtdate);
        jtxtdate.setBounds(550, 70, 160, 30);

        jtxtexpense.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel2.add(jtxtexpense);
        jtxtexpense.setBounds(210, 70, 220, 30);

        Delete.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Delete.setText("Delete");
        Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteActionPerformed(evt);
            }
        });
        jPanel2.add(Delete);
        Delete.setBounds(520, 190, 110, 30);

        tblexpenses.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ExpensesID", "Date", "OwnerName", "Name of Expenses", "Amount"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblexpenses.setFocusable(false);
        tblexpenses.setIntercellSpacing(new java.awt.Dimension(0, 0));
        tblexpenses.setRowHeight(25);
        tblexpenses.getTableHeader().setReorderingAllowed(false);
        tblexpenses.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblexpensesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblexpenses);
        if (tblexpenses.getColumnModel().getColumnCount() > 0) {
            tblexpenses.getColumnModel().getColumn(0).setResizable(false);
            tblexpenses.getColumnModel().getColumn(1).setResizable(false);
            tblexpenses.getColumnModel().getColumn(2).setResizable(false);
            tblexpenses.getColumnModel().getColumn(3).setResizable(false);
            tblexpenses.getColumnModel().getColumn(4).setResizable(false);
        }

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(70, 230, 1070, 170);

        jButton2.setText("View Expenses");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2);
        jButton2.setBounds(70, 190, 150, 30);

        Add.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Add.setText("Add");
        Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddActionPerformed(evt);
            }
        });
        jPanel2.add(Add);
        Add.setBounds(300, 190, 110, 30);

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton4.setText("Add");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4);
        jButton4.setBounds(300, 190, 110, 30);

        Update.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Update.setText("Update");
        Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateActionPerformed(evt);
            }
        });
        jPanel2.add(Update);
        Update.setBounds(410, 190, 110, 30);

        jtxtsearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtxtsearchKeyReleased(evt);
            }
        });
        jPanel2.add(jtxtsearch);
        jtxtsearch.setBounds(1000, 190, 140, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Search\n");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(932, 190, 80, 30);
        jPanel2.add(jtxttotalownerexpenses);
        jtxttotalownerexpenses.setBounds(990, 410, 150, 30);

        jButton1.setText("Check Amount");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);
        jButton1.setBounds(860, 410, 120, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 1254, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteActionPerformed
        // TODO add your handling code here:
         String sql ="DELETE FROM Expenses WHERE ExpensesID =?";
        try{

            PreparedStatement pst  = con.prepareStatement(sql);

            DefaultTableModel model = (DefaultTableModel) tblexpenses.getModel();

            pst.setString(1,jtxtexpense.getText());
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Deleted Successfully");

        } catch (SQLException | HeadlessException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_DeleteActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String sql = "select * from Expenses";
        try{
            PreparedStatement pst = con.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();
            DefaultTableModel model = (DefaultTableModel) tblexpenses.getModel();
            model.setRowCount(0);
            while(rs.next()){
                model.addRow(new String[]{rs.getString(1), rs.getString(2), rs.getString(3),rs.getString(4),rs.getString(5)});
            }
        }catch(Exception ex){
            System.out.println("Error : " +ex.getMessage());
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddActionPerformed
        // TODO add your handling code here:
           String sql = "insert into expenses"
        + "(ExpensesID, Date, OwnerName, NameofExpenses, Amount)"
        + "VALUES (?,?,?,?,?)";
        try{

            PreparedStatement pst  = con.prepareStatement(sql);

            DefaultTableModel model = (DefaultTableModel) tblexpenses.getModel();

            pst.setString(1,jtxtexpense.getText());
            pst.setString(2,jtxtdate.getText());
            pst.setString(3,jtxtname.getText());
            pst.setString(4,jtxtexpensename.getText());
            pst.setString(5,jtxtamount.getText());
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Inserted Successfully");

        } catch (SQLException | HeadlessException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_AddActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateActionPerformed
        // TODO add your handling code here:
         String sql = "UPDATE Expenses SET Date=?, OwnerName =?, NameofExpenses=?, Amount=? WHERE ExpensesID=?";
        try{

            PreparedStatement pst  = con.prepareStatement(sql);

            DefaultTableModel model = (DefaultTableModel) tblexpenses.getModel();

            pst.setString(5,jtxtexpense.getText());
            pst.setString(1,jtxtdate.getText());
            pst.setString(2,jtxtname.getText());
            pst.setString(3,jtxtexpensename.getText());
            pst.setString(4,jtxtamount.getText());
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Updated Successfully");

        } catch (SQLException | HeadlessException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_UpdateActionPerformed

    private void tblexpensesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblexpensesMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) tblexpenses.getModel();
        
        String tblExpenseID = model.getValueAt(tblexpenses.getSelectedRow(),0).toString();
        String tblDate = model.getValueAt(tblexpenses.getSelectedRow(),1).toString();
        String tblOwnerName = model.getValueAt (tblexpenses.getSelectedRow(),2).toString();
        String tblExpensesName = model.getValueAt(tblexpenses.getSelectedRow(),3).toString();
        String tblAmount = model.getValueAt(tblexpenses.getSelectedRow(),4).toString();
               
       jtxtexpense.setText(tblExpenseID);
       jtxtdate.setText(tblDate);
       jtxtname.setText(tblOwnerName);
       jtxtexpensename.setText(tblExpensesName);
       jtxtamount.setText(tblAmount);
    }//GEN-LAST:event_tblexpensesMouseClicked

    private void jtxtsearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtsearchKeyReleased
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) tblexpenses.getModel();
        TableRowSorter<DefaultTableModel> obj=new TableRowSorter<>(model);
        tblexpenses.setRowSorter(obj);
        obj.setRowFilter(RowFilter.regexFilter(jtxtsearch.getText()));
    }//GEN-LAST:event_jtxtsearchKeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try {
            String searchText = jtxtsearch.getText();
            String sqlTotalAmount = "SELECT SUM(Amount) AS TotalAmount FROM Expenses WHERE " +
            "ExpensesID LIKE ? OR Date LIKE ? OR OwnerName LIKE ? OR NameofExpenses LIKE ? OR Amount LIKE ? ";

            PreparedStatement totalAmountStatement = con.prepareStatement(sqlTotalAmount);

            for (int i = 1; i <= 5; i++) {
                totalAmountStatement.setString(i, "%" + searchText + "%");
            }

            ResultSet resultSet = totalAmountStatement.executeQuery();

            if (resultSet.next()) {
                double totalAmount = resultSet.getDouble("TotalAmount");

                String formattedTotalAmount = String.format("%.2f", totalAmount);
                jtxttotalownerexpenses.setText(formattedTotalAmount);
            } else {
                jtxttotalownerexpenses.setText("0.00");
            }

            resultSet.close();
            totalAmountStatement.close();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add;
    private javax.swing.JButton Delete;
    private javax.swing.JButton Update;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jtxtamount;
    private javax.swing.JTextField jtxtdate;
    private javax.swing.JTextField jtxtexpense;
    private javax.swing.JTextField jtxtexpensename;
    private javax.swing.JTextField jtxtname;
    private javax.swing.JTextField jtxtsearch;
    private javax.swing.JTextField jtxttotalownerexpenses;
    private javax.swing.JTable tblexpenses;
    // End of variables declaration//GEN-END:variables
}
